"""
Smoke tests for SUBS — generated by scripts/new_set/wire_set.py.

Asserts:
  - every card in the set imports without error
  - every card has a CardDefinition with name + characteristics
  - every starter deck builder runs without raising and returns a
    non-empty list of CardDefinitions

The "every card actually resolves in play" guarantee is enforced by the
balance-loop coverage stage (scripts/new_set/balance_loop.py +
scripts/new_set/coverage.py), which can detect missing implementations
via zero-play cards across the tournament — that check is engine-aware
where this scaffold is engine-agnostic by design.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src.cards.depths.submarine_fleet import SUBS_CARDS
from src.cards.depths.submarine_fleet.decks import make_subs_wolfpack_deck, make_subs_silent_hunter_deck, make_subs_carrier_deck, make_subs_deep_strike_deck


def test_every_card_loads():
    assert SUBS_CARDS, "SUBS card registry is empty"
    for name, card in SUBS_CARDS.items():
        assert card is not None, f"{name}: card def is None"
        assert card.name, f"{name}: card has no .name"
        assert card.characteristics is not None, \
            f"{name}: card has no .characteristics"


def test_deck_wolfpack_builds():
    deck = make_subs_wolfpack_deck()
    assert deck, "wolfpack builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "wolfpack contains a None card"
        assert getattr(cd, "name", None), "wolfpack contains a nameless card"

def test_deck_silent_hunter_builds():
    deck = make_subs_silent_hunter_deck()
    assert deck, "silent_hunter builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "silent_hunter contains a None card"
        assert getattr(cd, "name", None), "silent_hunter contains a nameless card"

def test_deck_carrier_builds():
    deck = make_subs_carrier_deck()
    assert deck, "carrier builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "carrier contains a None card"
        assert getattr(cd, "name", None), "carrier contains a nameless card"

def test_deck_deep_strike_builds():
    deck = make_subs_deep_strike_deck()
    assert deck, "deep_strike builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "deep_strike contains a None card"
        assert getattr(cd, "name", None), "deep_strike contains a nameless card"


def test_card_costs_propagate_to_characteristics():
    """Regression: SUBS factories must mirror mana_cost into Characteristics.

    Without this, deploy_vessel's cost-pay check short-circuits on a falsy
    cost_str (`if cost_str and not cs.pay_cost(...)`) — every card costs 0.
    The AI's cost parser also reads `characteristics.mana_cost`, so it would
    treat every card as free and play exponential curves.
    """
    missing: list[str] = []
    mismatched: list[str] = []
    for name, card in SUBS_CARDS.items():
        top_cost = getattr(card, "mana_cost", None)
        chr_cost = getattr(card.characteristics, "mana_cost", None)
        if top_cost is None:
            # Token-only / flagship-style; both should be None and that's fine.
            if chr_cost is not None:
                mismatched.append(f"{name}: top=None but characteristics.mana_cost={chr_cost!r}")
            continue
        if chr_cost is None:
            missing.append(name)
        elif top_cost != chr_cost:
            mismatched.append(f"{name}: top={top_cost!r} but characteristics.mana_cost={chr_cost!r}")
    assert not missing, (
        f"{len(missing)} SUBS cards have a top-level mana_cost but "
        f"characteristics.mana_cost is None — engine will treat them as free. "
        f"First few: {missing[:5]}"
    )
    assert not mismatched, f"Cost mismatches: {mismatched[:5]}"


def test_cast_effect_fn_actually_runs():
    """Regression: cast_spell must invoke card.cast_effect_fn after SPELL_CAST.

    Pre-fix, ~25 SUBS Action cards had silent-no-op effects because cast_spell
    emitted SPELL_CAST + routed the card to the graveyard but never called
    cast_effect_fn. Surfaced by ultra-loop iter-1 Pilot A: Saturation Strike's
    +2 power buff never reached the DAMAGE event in 38 turns of play.
    """
    import asyncio
    from src.engine.game import Game
    from src.engine.types import EventType, ZoneType, CardType
    from src.engine.depths import cast_spell, deploy_vessel
    from src.engine.depths_turn import DepthsTurnManager
    from src.cards.depths.submarine_fleet.decks import (
        SUBS_STARTER_DECKS, make_subs_flagship,
    )

    async def _run():
        g = Game(mode="depths")
        p1 = g.add_player("A"); p2 = g.add_player("B")
        tm = DepthsTurnManager(g.state); g.turn_manager = tm
        await tm.setup_game(
            g, SUBS_STARTER_DECKS["SUBS_wolfpack"](),
            SUBS_STARTER_DECKS["SUBS_silent_hunter"](),
            make_subs_flagship(), make_subs_flagship(),
        )
        # Force Saturation Strike into P1's hand, then deploy any Submarine.
        lib = g.state.zones.get(f"hand_{p1.id}").objects
        ss_id = None
        for oid in list(g.state.zones[f"library_{p1.id}"].objects):
            obj = g.state.objects.get(oid)
            if obj and obj.name == "Saturation Strike":
                g.state.zones[f"library_{p1.id}"].objects.remove(oid)
                g.state.zones[f"hand_{p1.id}"].objects.append(oid)
                obj.zone = ZoneType.HAND
                ss_id = oid
                break
        if ss_id is None:
            return None  # deck didn't have a Saturation Strike — skip
        p1.tc = 5  # ensure we can pay both deploys + cast
        sub_id = None
        for oid in list(g.state.zones[f"hand_{p1.id}"].objects):
            obj = g.state.objects.get(oid)
            if (obj
                and CardType.DEPTHS_VESSEL in obj.characteristics.types
                and "Submarine" in obj.characteristics.subtypes):
                ok, _, _ = deploy_vessel(g, p1.id, card_id=oid)
                if ok:
                    sub_id = oid
                    break
        assert sub_id is not None, "Setup: needed at least one Submarine to deploy"
        sub = g.state.objects.get(sub_id)
        ok, msg, evs = cast_spell(g, p1.id, card_id=ss_id)
        assert ok, f"cast_spell failed: {msg!r}"
        return sub, evs

    result = asyncio.run(_run())
    if result is None:
        return  # deck didn't include the test card
    sub, evs = result
    pt_events = [
        e for e in evs
        if getattr(e, "type", None).__class__.__name__ == "EventType"
        and e.type.name == "PT_MODIFICATION"
    ]
    assert pt_events, (
        "Saturation Strike's cast_effect_fn did not emit any PT_MODIFICATION "
        "events. cast_spell must invoke card.cast_effect_fn — see "
        "src/engine/depths.py:cast_spell."
    )
    pmods = list(sub.state.pt_modifiers or [])
    assert any(
        m.get("power", 0) >= 1 and m.get("duration") == "end_of_turn"
        for m in pmods
    ), f"Submarine's pt_modifiers should include +N power EOT after Saturation Strike. Got: {pmods}"


def test_deploy_refuses_when_cant_pay():
    """Regression: deploy_vessel must actually refuse when player can't afford.

    Catches the silent-failure mode where the cost was None and the pay-cost
    check was skipped entirely.
    """
    import asyncio
    from src.engine.game import Game
    from src.engine.depths import deploy_vessel
    from src.engine.depths_turn import DepthsTurnManager
    from src.cards.depths.submarine_fleet.decks import (
        SUBS_STARTER_DECKS, make_subs_flagship,
    )

    async def _run():
        g = Game(mode="depths")
        p1 = g.add_player("A"); p2 = g.add_player("B")
        tm = DepthsTurnManager(g.state); g.turn_manager = tm
        await tm.setup_game(
            g,
            SUBS_STARTER_DECKS["SUBS_silent_hunter"](),
            SUBS_STARTER_DECKS["SUBS_wolfpack"](),
            make_subs_flagship(), make_subs_flagship(),
        )
        # Find a costly card in P1's hand and try to deploy it with TC=0.
        hand = g.state.zones.get(f"hand_{p1.id}")
        for oid in hand.objects:
            obj = g.state.objects.get(oid)
            if not obj:
                continue
            cost = getattr(obj.characteristics, "mana_cost", None) or ""
            if "T" not in cost.replace("S", ""):  # need a TC-required card
                continue
            p1.tc, p1.sc = 0, 0
            ok, msg, _ = deploy_vessel(g, p1.id, card_id=obj.id)
            assert not ok, (
                f"deploy_vessel({obj.name!r}, cost={cost}) succeeded with TC=0 — "
                f"the cost check must refuse insufficient charges. msg={msg!r}"
            )
            return  # one example is enough
        assert False, "Hand had no TC-cost cards to test with"
    asyncio.run(_run())


def test_medium_ai_defense_sees_pumped_power():
    """Regression: the medium AI's defense triage must reflect runtime PT pumps.

    Pre-fix, ``_depth_modifier_damage`` (and ``_power``) read
    ``obj.characteristics.power`` (the printed value), so a Saturation Strike
    +2 EOT pump was invisible to ``_medium_detections``. Defender saw a
    base-power projection well below the lethal-buffer threshold and declined
    to detect — Pilot B iter-2 ate a 9-damage alpha as a result.

    Pure-unit test: constructs a minimal GameObject pair (attacker + flagship)
    with controlled stats and a fabricated GameState that holds them. Avoids
    deck-draw randomness so the assertion is deterministic.
    """
    from src.engine.types import GameObject, GameState, ObjectState, Characteristics, CardType, ZoneType
    from src.engine.depths import DepthBand
    from src.ai.depths_adapter import (
        _depth_modifier_damage, _power,
    )

    # Build a state with two GameObjects: attacker at SURFACE, flagship at PERISCOPE.
    state = GameState()
    state.interceptors = {}

    attacker = GameObject(
        id="att_1",
        name="Test Sub",
        owner="A",
        controller="A",
        zone=ZoneType.BATTLEFIELD,
        characteristics=Characteristics(
            types={CardType.DEPTHS_VESSEL},
            subtypes={"Submarine"},
            power=2,
            toughness=2,
        ),
        state=ObjectState(),
    )
    attacker.state.depth_band = DepthBand.SURFACE
    attacker.state.pt_modifiers = []

    flagship = GameObject(
        id="fs_1",
        name="Test Flagship",
        owner="B",
        controller="B",
        zone=ZoneType.BATTLEFIELD,
        characteristics=Characteristics(
            types={CardType.DEPTHS_VESSEL},
            subtypes={"Submarine", "Flagship"},
            power=0,
            toughness=25,
        ),
        state=ObjectState(),
    )
    flagship.state.depth_band = DepthBand.PERISCOPE
    flagship.state.pt_modifiers = []

    state.objects = {attacker.id: attacker, flagship.id: flagship}

    # Pre-pump baseline: SURFACE → PERISCOPE has 1 band of separation, so
    # damage = max(1, 2 - 1) = 1.
    unpumped_no_state = _depth_modifier_damage(attacker, flagship)
    unpumped_with_state = _depth_modifier_damage(attacker, flagship, state)
    assert unpumped_no_state == unpumped_with_state == 1, (
        f"Pre-pump baseline mismatch: no_state={unpumped_no_state}, "
        f"with_state={unpumped_with_state}; expected 1 = max(1, 2-1).")

    # Apply a +3 power EOT pump directly to pt_modifiers (skipping the
    # pipeline since this is a pure-unit test of the projection path).
    attacker.state.pt_modifiers.append({
        "power": 3, "toughness": 0, "duration": "end_of_turn", "source_id": "test",
    })

    pumped_with_state = _depth_modifier_damage(attacker, flagship, state)
    pumped_no_state = _depth_modifier_damage(attacker, flagship)

    # Effective power 5, depth penalty 1 → max(1, 5-1) = 4.
    assert pumped_with_state == 4, (
        f"Post-pump state-aware projection should be 4 (max(1, 5-1)), "
        f"got {pumped_with_state}.")
    assert pumped_no_state == 1, (
        f"State-less projection should still see printed-only power "
        f"(damage 1), got {pumped_no_state}.")

    # And the load-bearing assertion: _power(obj, state) routes through
    # get_power and reflects the pump.
    assert _power(attacker, state) == 5, (
        f"_power(obj, state) must include the pump; got {_power(attacker, state)}.")
    assert _power(attacker) == 2, (
        f"_power(obj) without state must return printed-only; got {_power(attacker)}.")


def test_medium_ai_detects_chip_stream():
    """Iter-5 regression: chip-damage stream escalates the lethal buffer.

    Pre-fix, the medium AI's _medium_detections only spent SC when a single
    swing's projection crossed ``hull - lethal_buffer``. So a 4-damage-per-turn
    chip stream stayed below the projection and was never intercepted, even
    while the defender's flagship dropped from 25 → 6 over five turns
    (Pilot B iter-3 + iter-4 evidence).

    This test wires up a Medium-difficulty adapter, simulates three turns of
    4-damage chip taken (by mutating the flagship hull and calling
    ``_medium_detections`` on each turn), and asserts the third call escalates
    detection because the cumulative damage is now above
    ``MEDIUM_RECENT_DAMAGE_TRIGGER``.
    """
    from src.engine.types import GameObject, GameState, ObjectState, Characteristics, CardType, ZoneType, Player
    from src.engine.depths import DepthBand
    from src.ai.depths_adapter import (
        DepthsAIAdapter,
        AttackerSpec,
        MEDIUM_RECENT_DAMAGE_TRIGGER,
    )

    adapter = DepthsAIAdapter(difficulty="medium")

    # Build a state with a flagship and a single 2-power attacker (chip).
    state = GameState()
    state.interceptors = {}

    # Two players so flagship lookup works.
    state.players = {
        "A": Player(id="A", name="A"),
        "B": Player(id="B", name="B"),
    }
    # Defender (B) has SC budget; attacker (A) has none.
    state.players["B"].sc = 4
    state.players["B"].tc = 0
    state.players["A"].sc = 0
    state.players["A"].tc = 0

    flagship = GameObject(
        id="fs_B",
        name="Test Flagship",
        owner="B",
        controller="B",
        zone=ZoneType.BATTLEFIELD,
        characteristics=Characteristics(
            types={CardType.DEPTHS_VESSEL},
            subtypes={"Submarine", "Flagship"},
            power=0,
            toughness=25,
        ),
        state=ObjectState(),
    )
    flagship.state.depth_band = DepthBand.PERISCOPE
    flagship.state.pt_modifiers = []
    flagship.state.damage = 0

    attacker = GameObject(
        id="att_1",
        name="Test Sub",
        owner="A",
        controller="A",
        zone=ZoneType.BATTLEFIELD,
        characteristics=Characteristics(
            types={CardType.DEPTHS_VESSEL},
            subtypes={"Submarine"},
            power=3,
            toughness=2,
        ),
        state=ObjectState(),
    )
    attacker.state.depth_band = DepthBand.PERISCOPE  # no penalty against flagship
    attacker.state.pt_modifiers = []

    state.objects = {flagship.id: flagship, attacker.id: attacker}

    # Build a battlefield zone so any battlefield-based queries succeed.
    from src.engine.types import Zone
    bf = Zone(type=ZoneType.BATTLEFIELD, owner=None)
    bf.objects = [flagship.id, attacker.id]
    state.zones = {"battlefield": bf}

    spec = AttackerSpec(
        vessel_id=attacker.id,
        target_id=flagship.id,
        firing_depth_band=DepthBand.PERISCOPE,
    )

    # Mid-game scenario (mirrors Pilot B iter-3 T14/T18/T22 chip stream).
    # Turn 14: hull 16 (already took 9 chip in untracked turns). 3-dmg single
    # swing leaves hull 13. Threshold = 16 - 3 = 13; danger 3 < threshold —
    # without escalation, AI declines detection.
    state.turn_number = 14
    flagship.state.damage = 9  # effective hull 16
    plan_t14 = adapter._medium_detections(state, "B", [spec])
    assert plan_t14 == {}, (
        f"T14 (first sample) should not yet escalate — history just started; "
        f"got {plan_t14}"
    )

    # Turn 15: hull 13 (took another 3). Recent damage in window = 3 (16→13).
    # Below trigger (6), so still no escalation.
    state.turn_number = 15
    flagship.state.damage = 12
    plan_t15 = adapter._medium_detections(state, "B", [spec])
    assert plan_t15 == {}, (
        f"T15 should not escalate — only 3 hull lost in window; got {plan_t15}"
    )

    # Turn 16: hull 10 (took yet another 3). Recent damage = 6 (16→10) trips
    # MEDIUM_RECENT_DAMAGE_TRIGGER. cumulative_unintercepted = 3 (this swing)
    # + 6 (chip stream forward projection) = 9. Threshold = 10 - 3 = 7.
    # 9 > 7 → AI escalates detection.
    state.turn_number = 16
    flagship.state.damage = 15
    plan_t16 = adapter._medium_detections(state, "B", [spec])
    assert plan_t16, (
        f"T16 should escalate detection — cumulative damage in window is "
        f">= {MEDIUM_RECENT_DAMAGE_TRIGGER} and SC budget is 4. Got empty plan."
    )
    assert attacker.id in plan_t16, (
        f"T16 escalation should target the chip attacker; plan={plan_t16}"
    )


if __name__ == "__main__":
    test_every_card_loads()
    test_deck_wolfpack_builds()
    test_deck_silent_hunter_builds()
    test_deck_carrier_builds()
    test_deck_deep_strike_builds()
    test_card_costs_propagate_to_characteristics()
    test_deploy_refuses_when_cant_pay()
    test_cast_effect_fn_actually_runs()
    test_medium_ai_defense_sees_pumped_power()
    test_medium_ai_detects_chip_stream()
    print("OK — SUBS smoke tests pass.")
