"""Auto-generated interceptor verification for Minecraft TCG. See /test-interceptors.

Generated by /ng-plus iter 1 polish pass on Minecraft.

Catches the "depths trap": interceptor is wired but effect_fn returns [] silently.
Each test manually invokes the callback and asserts at least one Event of the
expected category is returned.

Event-type mapping used:
  - material gain  → EventType.MC_MATERIAL_GAIN
  - draw           → EventType.DRAW
  - damage         → EventType.DAMAGE
  - life/heal      → EventType.LIFE_CHANGE
  - token create   → EventType.CREATE_TOKEN
  - zone change    → EventType.ZONE_CHANGE  (opp discard / mill)
  - destroy        → EventType.OBJECT_DESTROYED
  - untap          → EventType.UNTAP
  - explore biome  → EventType.MC_EXPLORE_BIOME
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.engine.types import CardType, Event, EventType, GameState, ZoneType
from src.engine.game import Game
from src.cards.minecraft import MINECRAFT_CARDS


# ---------------------------------------------------------------------------
# Cards whose effects can't be auto-tested — one-line reason each.
# ---------------------------------------------------------------------------

SKIPPED_CARDS = {
    # on_play effects that mutate state only (no events emitted by design)
    "Enchanting Table":    "on_play mutates weapon.mc_attack in-place; returns [] by design",
    # Conditional on opponent grid/mobs being non-empty — returns [] in empty state
    "Warden":              "on_play hits enemy mobs — returns [] when opp battlefield is empty",
    "Entity 303":          "on_play hits enemy grid — returns [] when opp grid is empty",
    "Wither Storm":        "on_play hits enemy mobs+grid — returns [] when both are empty",
    "Wither":              "on_play damage scales with your Hostile count — returns [] with no Hostiles",
    "Ender Dragon":        "on_play damage scales with diamond-cost permanents — returns [] with none",
    "Iron Golem":          "on_play damage scales with Worker count — returns [] with no Workers",
    "Elder Guardian":      "on_event only (no on_play) — generic listener not auto-testable",
    "Ravager":             "on_event only — generic listener not auto-testable",
    "Blaze":               "on_event only — generic listener not auto-testable",
    "Phyrexian Negator":   "on_damage hook (not on_play/attack/block) — custom trigger path",
    # Target-dependent removals — return [] with target_id=None
    "Glistening Oil":      "on_play needs a target enemy mob with HP ≤ 2 to convert",
    "Compleat":            "on_play needs a valid target_id of a friendly mob",
    "Mass Compleation":    "on_play mutates subtypes in-place; emits [] by design",
    "Hex Parasite":        "on_play needs a target mob — returns [] with target_id=None",
    "Inkmoth Surge":       "on_play needs target mob and target_id — returns [] without one",
    "Possession":          "on_play needs a target enemy mob with ≤2 HP — returns [] without target",
    "Drag to the Dark":    "on_play needs a target with ≤3 HP — returns [] without target",
    "Fog Roll":            "on_play grants keyword to target — mutates in-place, returns [] by design",
    "Bloodmoon Ritual":    "on_play grants aerial to target — mutates in-place, returns [] by design",
    "Skinwalker, Wearer of Faces": "on_play needs a target enemy mob — returns [] without one",
    "The Mimicer":         "on_play needs a target enemy mob — returns [] without one",
    # These damage/destroy based on opponents — return [] with no opponent
    "Tyrant of Kher Ridges": "on_play hits enemy mobs — returns [] when opp battlefield is empty",
    "Elesh Norn, Grand Cenobite": "on_play hits enemy mobs — returns [] when opp battlefield is empty",
    "Null, the Empty Skin":   "on_play discards from opponent's hand — returns [] when hand is empty",
    "Ratman":              "on_play discards from opponent's hand — returns [] when hand is empty",
    "Sleep-Stealer":       "on_play hits opponent avatar — returns [] when no opponent",
    "Cave Dweller":        "on_attack discards from opp hand — returns [] when hand is empty",
    "Goatman, Crooked Stalker": "on_attack discards from opp hand — returns [] when hand is empty",
    "Elder Phantom":       "on_play discards from opp hand — returns [] when hand is empty",
    # Wither Skeleton on_attack: mutates target toughness in-place, emits []
    "Wither Skeleton":     "on_attack mutates toughness in-place; returns [] by design",
    # Yawgmoth's Will needs a target action in graveyard
    "Yawgmoth's Will":     "on_play replays action from graveyard — needs populated graveyard",
    # Reanimate needs a Compleated mob in graveyard
    "Reanimate":           "on_play moves obj from graveyard — needs populated graveyard",
    # Glistening Pool deathrattle — on_death path (not on_play/attack/block)
    "Glistening Pool":     "on_death only (no on_play/attack/block callbacks)",
    # Sickening Dreams AOE on all mobs — returns [] when battlefield empty
    "Sickening Dreams":    "on_play hits all mobs — returns [] when battlefield is empty",
    "Black Sun's Zenith":  "on_play hits all mobs — returns [] when battlefield is empty",
    # Toxic Deluge requires you.life > amount and all-mob targets
    "Toxic Deluge":        "on_play reduces your own HP and hits all mobs — complex setup",
    # Whispering Curse opp-discard: returns [] when opp hand is empty
    "Whispering Curse":    "on_play discards from opp hand — returns [] when hand is empty",
    # Sleep Deprivation: damage to opp + discard — damage returns [] with no opponent
    "Sleep Deprivation":   "on_play hits opp avatar — returns [] when no opponent",
    # Massacre and The Wither Calls and Goatman's Hex: aoe enemy mobs
    "Massacre":            "on_play hits enemy mobs — returns [] when opp battlefield empty",
    "The Wither Calls":    "on_play hits enemy mobs — returns [] when opp battlefield empty",
    "Goatman's Hex":       "on_play hits enemy mobs — returns [] when opp battlefield empty",
    # Backrooms Trip: mill opp library — returns [] when library empty
    "Backrooms Trip":      "on_play mills opp library — returns [] when library is empty",
    # Wither Storm handled above already
    # Herobrine needs a target mob
    "Herobrine, World's Eye": "on_play destroys target mob — returns [] without target",
    # Putrefy needs a target mob
    "Putrefy":             "on_play destroys target mob — returns [] without target",
    # Disfigure: returns [] with no opponent and no target
    "Disfigure":           "on_play damages frontmost or avatar — returns [] with no opponent",
    # Voltage Surge: same
    "Voltage Surge":       "on_play damages frontmost or avatar — returns [] with no opponent",
    # Wither Skull: same
    "Wither Skull":        "on_play damages frontmost or avatar — returns [] with no opponent",
    # TNT Blast: same
    "TNT Blast":           "on_play damages frontmost or target — returns [] with no opponent",
    # Creeper Ambush: token summon (has an opponent requirement in targeting fallback,
    #   but the token itself is unconditional — we DO test this one)
}


# ---------------------------------------------------------------------------
# Scaffold helpers — mirrored from test_minecraft_tcg.py patterns
# ---------------------------------------------------------------------------

def _build_game():
    """Minimal 2-player Minecraft game with both players set up."""
    game = Game(mode="minecraft")
    p1 = game.add_player("P1")
    p2 = game.add_player("P2")
    game.setup_minecraft_player(p1, [])
    game.setup_minecraft_player(p2, [])
    return game, p1, p2


def _place_on_battlefield(game, player_id, card_def):
    """Create a GameObject for card_def in BATTLEFIELD owned by player_id."""
    obj = game.create_object(
        name=card_def.name,
        owner_id=player_id,
        zone=ZoneType.BATTLEFIELD,
        characteristics=card_def.characteristics,
        card_def=card_def,
    )
    obj.controller = player_id
    return obj


def _place_in_hand(game, player_id, card_def):
    obj = game.create_object(
        name=card_def.name,
        owner_id=player_id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=card_def,
    )
    obj.controller = player_id
    return obj


def _place_in_library(game, player_id, card_def):
    obj = game.create_object(
        name=card_def.name,
        owner_id=player_id,
        zone=ZoneType.LIBRARY,
        characteristics=card_def.characteristics,
        card_def=card_def,
    )
    obj.controller = player_id
    return obj


def _place_in_graveyard(game, player_id, card_def):
    obj = game.create_object(
        name=card_def.name,
        owner_id=player_id,
        zone=ZoneType.GRAVEYARD,
        characteristics=card_def.characteristics,
        card_def=card_def,
    )
    obj.controller = player_id
    return obj


def _add_to_hand_zone(game, player_id, obj):
    """Move obj to a player's hand zone (for discard-trigger testing)."""
    zone = game.state.zones.get(f"hand_{player_id}")
    if zone and obj.id not in zone.objects:
        zone.objects.append(obj.id)


def _add_to_library_zone(game, player_id, obj):
    zone = game.state.zones.get(f"library_{player_id}")
    if zone and obj.id not in zone.objects:
        zone.objects.append(obj.id)


# ---------------------------------------------------------------------------
# Auto-generated card tests — alphabetical within callback type group
# ---------------------------------------------------------------------------

# ─── on_play: material gain ────────────────────────────────────────────────

def test_card_chop_trees_on_play():
    """Chop Trees: on_play — expects MC_MATERIAL_GAIN (2 wood)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Chop Trees"])
    fn = MINECRAFT_CARDS["Chop Trees"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Chop Trees on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_strip_mine_on_play():
    """Strip Mine: on_play — expects MC_MATERIAL_GAIN (iron + redstone)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Strip Mine"])
    fn = MINECRAFT_CARDS["Strip Mine"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Strip Mine on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_find_diamonds_on_play():
    """Find Diamonds: on_play — expects MC_MATERIAL_GAIN (1 diamond)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Find Diamonds"])
    fn = MINECRAFT_CARDS["Find Diamonds"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Find Diamonds on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_nether_expedition_on_play():
    """Nether Expedition: on_play — expects MC_MATERIAL_GAIN and DRAW."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Nether Expedition"])
    fn = MINECRAFT_CARDS["Nether Expedition"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) >= 2, f"Nether Expedition on_play returned {len(events)} events, expected ≥2"
    types = {e.type for e in events}
    assert EventType.MC_MATERIAL_GAIN in types, f"Expected MC_MATERIAL_GAIN in {types}"
    assert EventType.DRAW in types, f"Expected DRAW in {types}"


def test_card_phyrexian_vault_on_play():
    """Phyrexian Vault: on_play — expects MC_MATERIAL_GAIN (2 redstone)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Phyrexian Vault"])
    fn = MINECRAFT_CARDS["Phyrexian Vault"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Phyrexian Vault on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_yawgmoths_mandate_on_play():
    """Yawgmoth's Mandate: on_play — expects MC_MATERIAL_GAIN (1 of every material)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Yawgmoth's Mandate"])
    fn = MINECRAFT_CARDS["Yawgmoth's Mandate"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Yawgmoth's Mandate on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_praetor_bounty_on_play():
    """Praetor's Bounty: on_play — expects MC_MATERIAL_GAIN (3 wood)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Praetor's Bounty"])
    fn = MINECRAFT_CARDS["Praetor's Bounty"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Praetor's Bounty on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_annihilator_symbol_on_play():
    """Annihilator Symbol: on_play — expects MC_MATERIAL_GAIN (5 redstone)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Annihilator Symbol"])
    fn = MINECRAFT_CARDS["Annihilator Symbol"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Annihilator Symbol on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_realmbreakers_reach_on_play():
    """Realmbreaker's Reach: on_play — expects MC_MATERIAL_GAIN."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Realmbreaker's Reach"])
    fn = MINECRAFT_CARDS["Realmbreaker's Reach"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Realmbreaker's Reach on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_geth_lord_of_vault_on_play():
    """Geth, Lord of the Vault: on_play — expects MC_MATERIAL_GAIN (2 redstone)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Geth, Lord of the Vault"])
    fn = MINECRAFT_CARDS["Geth, Lord of the Vault"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Geth on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_vorinclex_on_play():
    """Vorinclex, Voice of Hunger: on_play — expects MC_MATERIAL_GAIN (all materials)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Vorinclex, Voice of Hunger"])
    fn = MINECRAFT_CARDS["Vorinclex, Voice of Hunger"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Vorinclex on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_atraxa_on_play():
    """Atraxa, Grand Unifier: on_play — expects MC_MATERIAL_GAIN and DRAW."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Atraxa, Grand Unifier"])
    fn = MINECRAFT_CARDS["Atraxa, Grand Unifier"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) >= 2, f"Atraxa on_play returned {len(events)} events, expected ≥2"
    types = {e.type for e in events}
    assert EventType.MC_MATERIAL_GAIN in types, f"Expected MC_MATERIAL_GAIN in {types}"
    assert EventType.DRAW in types, f"Expected DRAW in {types}"


def test_card_phyrexian_tower_on_play():
    """Phyrexian Tower: on_play — expects MC_MATERIAL_GAIN (2 iron)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Phyrexian Tower"])
    fn = MINECRAFT_CARDS["Phyrexian Tower"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Phyrexian Tower on_play returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_mycosynth_wellspring_on_play():
    """Mycosynth Wellspring: on_play — expects MC_MATERIAL_GAIN and DRAW."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Mycosynth Wellspring"])
    fn = MINECRAFT_CARDS["Mycosynth Wellspring"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) >= 2, f"Mycosynth Wellspring on_play returned {len(events)}, expected ≥2"
    types = {e.type for e in events}
    assert EventType.MC_MATERIAL_GAIN in types, f"Expected MC_MATERIAL_GAIN in {types}"
    assert EventType.DRAW in types, f"Expected DRAW in {types}"


# ─── on_play: draw ─────────────────────────────────────────────────────────

def test_card_villager_trade_on_play():
    """Villager Trade: on_play — expects DRAW (1 card)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Villager Trade"])
    fn = MINECRAFT_CARDS["Villager Trade"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Villager Trade on_play returned no events"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


def test_card_enderman_on_play():
    """Enderman: on_play — expects DRAW (1 card)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Enderman"])
    fn = MINECRAFT_CARDS["Enderman"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Enderman on_play returned no events"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


def test_card_compulsive_research_on_play():
    """Compulsive Research: on_play — expects DRAW (3 cards)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Compulsive Research"])
    fn = MINECRAFT_CARDS["Compulsive Research"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Compulsive Research on_play returned no events"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


def test_card_jin_gitaxias_on_play():
    """Jin-Gitaxias, Core Augur: on_play — expects DRAW (3 cards)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Jin-Gitaxias, Core Augur"])
    fn = MINECRAFT_CARDS["Jin-Gitaxias, Core Augur"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Jin-Gitaxias on_play returned no events"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


def test_card_surgical_extraction_on_play():
    """Surgical Extraction: on_play — expects DRAW (simplified effect)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Surgical Extraction"])
    fn = MINECRAFT_CARDS["Surgical Extraction"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Surgical Extraction on_play returned no events"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


def test_card_cremate_on_play():
    """Cremate: on_play — expects DRAW."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Cremate"])
    fn = MINECRAFT_CARDS["Cremate"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Cremate on_play returned no events"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


def test_card_despise_on_play():
    """Despise: on_play — expects DRAW (simplified effect)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Despise"])
    fn = MINECRAFT_CARDS["Despise"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Despise on_play returned no events"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


def test_card_praetors_grasp_on_play():
    """Praetor's Grasp: on_play — expects DRAW (simplified: draw 2)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Praetor's Grasp"])
    fn = MINECRAFT_CARDS["Praetor's Grasp"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Praetor's Grasp on_play returned no events"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


def test_card_eldritch_insight_on_play():
    """Eldritch Insight: on_play — expects DRAW (2 cards)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Eldritch Insight"])
    fn = MINECRAFT_CARDS["Eldritch Insight"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Eldritch Insight on_play returned no events"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


def test_card_sheoldreds_restoration_on_play():
    """Sheoldred's Restoration: on_play — expects LIFE_CHANGE and DRAW."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Sheoldred's Restoration"])
    fn = MINECRAFT_CARDS["Sheoldred's Restoration"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) >= 2, f"Sheoldred's Restoration returned {len(events)}, expected ≥2"
    types = {e.type for e in events}
    assert EventType.LIFE_CHANGE in types, f"Expected LIFE_CHANGE in {types}"
    assert EventType.DRAW in types, f"Expected DRAW in {types}"


def test_card_eldritch_altar_on_play():
    """Eldritch Altar: on_play — expects DRAW (1 card)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Eldritch Altar"])
    fn = MINECRAFT_CARDS["Eldritch Altar"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Eldritch Altar on_play returned no events"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


# ─── on_play: life / heal ──────────────────────────────────────────────────

def test_card_mooshroom_herd_on_play():
    """Mooshroom Herd: on_play — expects LIFE_CHANGE (heal 2)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Mooshroom Herd"])
    fn = MINECRAFT_CARDS["Mooshroom Herd"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Mooshroom Herd on_play returned no events"
    assert any(e.type == EventType.LIFE_CHANGE for e in events), \
        f"Expected LIFE_CHANGE, got {[e.type for e in events]}"


def test_card_farm_plot_on_play():
    """Farm Plot: on_play — expects LIFE_CHANGE (heal 2)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Farm Plot"])
    fn = MINECRAFT_CARDS["Farm Plot"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Farm Plot on_play returned no events"
    assert any(e.type == EventType.LIFE_CHANGE for e in events), \
        f"Expected LIFE_CHANGE, got {[e.type for e in events]}"


def test_card_totem_of_undying_on_play():
    """Totem of Undying: on_play — expects LIFE_CHANGE (heal to 20)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Totem of Undying"])
    fn = MINECRAFT_CARDS["Totem of Undying"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Totem of Undying on_play returned no events"
    assert any(e.type == EventType.LIFE_CHANGE for e in events), \
        f"Expected LIFE_CHANGE, got {[e.type for e in events]}"


def test_card_sangromancer_on_play():
    """Sangromancer: on_play — expects LIFE_CHANGE (heal 4)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Sangromancer"])
    fn = MINECRAFT_CARDS["Sangromancer"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Sangromancer on_play returned no events"
    assert any(e.type == EventType.LIFE_CHANGE for e in events), \
        f"Expected LIFE_CHANGE, got {[e.type for e in events]}"


def test_card_mycoid_shepherd_on_play():
    """Mycoid Shepherd: on_play — expects LIFE_CHANGE (heal 4)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Mycoid Shepherd"])
    fn = MINECRAFT_CARDS["Mycoid Shepherd"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Mycoid Shepherd on_play returned no events"
    assert any(e.type == EventType.LIFE_CHANGE for e in events), \
        f"Expected LIFE_CHANGE, got {[e.type for e in events]}"


def test_card_suspicious_stew_on_play():
    """Suspicious Stew: on_play — expects LIFE_CHANGE (heal 4)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Suspicious Stew"])
    fn = MINECRAFT_CARDS["Suspicious Stew"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Suspicious Stew on_play returned no events"
    assert any(e.type == EventType.LIFE_CHANGE for e in events), \
        f"Expected LIFE_CHANGE, got {[e.type for e in events]}"


# ─── on_play: drain (damage + life) ────────────────────────────────────────

def test_card_sheoldred_on_play():
    """Sheoldred, the Whispering One: on_play — expects DAMAGE and LIFE_CHANGE (drain 5)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Sheoldred, the Whispering One"])
    fn = MINECRAFT_CARDS["Sheoldred, the Whispering One"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) >= 2, f"Sheoldred on_play returned {len(events)}, expected ≥2"
    types = {e.type for e in events}
    assert EventType.DAMAGE in types, f"Expected DAMAGE in {types}"
    assert EventType.LIFE_CHANGE in types, f"Expected LIFE_CHANGE in {types}"


# ─── on_play: token summon ─────────────────────────────────────────────────

def test_card_creeper_ambush_on_play():
    """Creeper Ambush: on_play — expects CREATE_TOKEN (4/1 Creeper)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Creeper Ambush"])
    fn = MINECRAFT_CARDS["Creeper Ambush"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Creeper Ambush on_play returned no events"
    assert any(e.type == EventType.CREATE_TOKEN for e in events), \
        f"Expected CREATE_TOKEN, got {[e.type for e in events]}"


def test_card_village_reinforcements_on_play():
    """Village Reinforcements: on_play — expects CREATE_TOKEN (2/3 Village Guard)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Village Reinforcements"])
    fn = MINECRAFT_CARDS["Village Reinforcements"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Village Reinforcements on_play returned no events"
    assert any(e.type == EventType.CREATE_TOKEN for e in events), \
        f"Expected CREATE_TOKEN, got {[e.type for e in events]}"


def test_village_reinforcements_full_play_lands_guard():
    # Regression: iter-7 strategy doc reported Village Guards never appearing
    # on the battlefield. Drives the action through play_card() (the path
    # both human and AI take) and asserts the full effect: a 2/3 Village
    # Guard token on the battlefield, materials deducted, and the spent
    # Action card sent to the graveyard.
    from src.engine import minecraft as mc
    game, p1, p2 = _build_game()
    p1.mc_materials = {"wood": 5, "stone": 0, "iron": 5, "redstone": 0, "diamond": 0}
    card_def = MINECRAFT_CARDS["Village Reinforcements"]
    card = game.create_object(
        name=card_def.name, owner_id=p1.id, zone=ZoneType.HAND,
        characteristics=card_def.characteristics, card_def=card_def,
    )
    card.controller = p1.id

    ok, msg, _events = mc.play_card(game, p1.id, card.id)
    assert ok, f"play_card failed: {msg}"

    # Token landed.
    guards = [
        game.state.objects[oid]
        for oid in game.state.zones["battlefield"].objects
        if oid in game.state.objects
        and game.state.objects[oid].controller == p1.id
        and CardType.MC_MOB in game.state.objects[oid].characteristics.types
        and game.state.objects[oid].name == "Village Guard"
    ]
    assert len(guards) == 1, f"Expected one Village Guard on battlefield, got {len(guards)}"
    g = guards[0]
    assert g.characteristics.power == 2 and g.characteristics.toughness == 3
    assert "Villager" in g.characteristics.subtypes
    # Token is a token (not a real card), per CREATE_TOKEN handler.
    assert g.state.is_token is True

    # Materials actually deducted (catches a short-circuited pay_materials).
    assert p1.mc_materials["wood"] == 3
    assert p1.mc_materials["iron"] == 4

    # Spent action card moved to graveyard (catches play_card forgetting
    # to clean up the source card).
    gy = game.state.zones.get(f"graveyard_{p1.id}")
    assert gy is not None and card.id in gy.objects, \
        "Village Reinforcements card should be in p1's graveyard after resolve"
    # And not still in hand.
    hand = game.state.zones.get(f"hand_{p1.id}")
    assert hand is not None and card.id not in hand.objects


def test_card_evoker_on_play():
    """Evoker: on_play — expects CREATE_TOKEN (1/1 Vex)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Evoker"])
    fn = MINECRAFT_CARDS["Evoker"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Evoker on_play returned no events"
    assert any(e.type == EventType.CREATE_TOKEN for e in events), \
        f"Expected CREATE_TOKEN, got {[e.type for e in events]}"


def test_card_skinwalker_trick_on_play():
    """Skinwalker Trick: on_play — expects CREATE_TOKEN (3/3 Horror/Stalker)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Skinwalker Trick"])
    fn = MINECRAFT_CARDS["Skinwalker Trick"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Skinwalker Trick on_play returned no events"
    assert any(e.type == EventType.CREATE_TOKEN for e in events), \
        f"Expected CREATE_TOKEN, got {[e.type for e in events]}"


def test_card_phantom_flock_on_play():
    """Phantom Flock: on_play — expects 2x CREATE_TOKEN (2/2 Phantom)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Phantom Flock"])
    fn = MINECRAFT_CARDS["Phantom Flock"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) >= 2, f"Phantom Flock returned {len(events)} events, expected ≥2"
    token_events = [e for e in events if e.type == EventType.CREATE_TOKEN]
    assert len(token_events) >= 2, f"Expected ≥2 CREATE_TOKEN, got {len(token_events)}"


def test_card_cave_calls_on_play():
    """The Cave Calls: on_play — expects CREATE_TOKEN (4/2 Cave Crawler)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["The Cave Calls"])
    fn = MINECRAFT_CARDS["The Cave Calls"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "The Cave Calls on_play returned no events"
    assert any(e.type == EventType.CREATE_TOKEN for e in events), \
        f"Expected CREATE_TOKEN, got {[e.type for e in events]}"


def test_card_phyrexian_rebirth_on_play():
    """Phyrexian Rebirth: on_play — always emits a 4/4 Horror token (even with empty battlefield)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Phyrexian Rebirth"])
    fn = MINECRAFT_CARDS["Phyrexian Rebirth"].mc_on_play
    events = fn(card, game.state, target_id=None)
    # At minimum the Horror token is always created
    assert len(events) > 0, "Phyrexian Rebirth on_play returned no events"
    assert any(e.type == EventType.CREATE_TOKEN for e in events), \
        f"Expected CREATE_TOKEN, got {[e.type for e in events]}"


# ─── on_play: untap workers ────────────────────────────────────────────────

def test_card_bone_meal_on_play_with_worker():
    """Bone Meal: on_play — expects UNTAP when a Worker is present."""
    game, p1, p2 = _build_game()
    worker = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Steve's Helper"])
    worker.state.mc_exhausted = True
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Bone Meal"])
    fn = MINECRAFT_CARDS["Bone Meal"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Bone Meal on_play returned no events with an exhausted Worker"
    assert any(e.type == EventType.UNTAP for e in events), \
        f"Expected UNTAP, got {[e.type for e in events]}"


def test_card_redstone_contraption_on_play_with_worker():
    """Redstone Contraption: on_play — expects UNTAP when Workers are present."""
    game, p1, p2 = _build_game()
    for i in range(2):
        w = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Steve's Helper"])
        w.state.mc_exhausted = True
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Redstone Contraption"])
    fn = MINECRAFT_CARDS["Redstone Contraption"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Redstone Contraption returned no events with exhausted Workers"
    assert any(e.type == EventType.UNTAP for e in events), \
        f"Expected UNTAP, got {[e.type for e in events]}"


# ─── on_play: explore biome ────────────────────────────────────────────────

def test_card_explore_map_on_play_with_upgradeable_biome():
    """Explore Map: on_play — expects MC_EXPLORE_BIOME when a biome can be upgraded."""
    from src.engine.minecraft import BIOME_UPGRADES
    game, p1, p2 = _build_game()
    # Find a biome that has an upgrade and seed it
    upgradeable = next(iter(BIOME_UPGRADES.keys()), None)
    if upgradeable is None:
        # No upgrades defined — skip gracefully
        return
    biomes = game.state.minecraft_biomes.get(p1.id, [])
    if biomes:
        biomes[0]["name"] = upgradeable
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Explore Map"])
    fn = MINECRAFT_CARDS["Explore Map"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Explore Map on_play returned no events with upgradeable biome"
    assert any(e.type == EventType.MC_EXPLORE_BIOME for e in events), \
        f"Expected MC_EXPLORE_BIOME, got {[e.type for e in events]}"


# ─── on_play: Eyes of Ender (ZONE_CHANGE library→hand) ────────────────────

def test_card_eyes_of_ender_on_play_with_end_mob_in_library():
    """Eyes of Ender: on_play — expects ZONE_CHANGE when an End mob is in the top 5."""
    game, p1, p2 = _build_game()
    # Place an End mob in the library
    end_mob = _place_in_library(game, p1.id, MINECRAFT_CARDS["Enderman"])
    _add_to_library_zone(game, p1.id, end_mob)
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Eyes of Ender"])
    fn = MINECRAFT_CARDS["Eyes of Ender"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Eyes of Ender returned no events when End mob is in library"
    assert any(e.type == EventType.ZONE_CHANGE for e in events), \
        f"Expected ZONE_CHANGE, got {[e.type for e in events]}"


# ─── on_play: damage (with opponent present) ──────────────────────────────

def test_card_compleated_wither_on_play_with_grid_objects():
    """Compleated Wither: on_play — expects DAMAGE events against opp grid objects."""
    game, p1, p2 = _build_game()
    # Place a Block on p2's grid
    block = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Cobblestone Wall"])
    block.state.mc_grid_x = 0
    block.state.mc_grid_y = 0
    game.state.minecraft_grid[p2.id][0][0] = block.id
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Compleated Wither"])
    fn = MINECRAFT_CARDS["Compleated Wither"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Compleated Wither on_play returned no events with opp grid object"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_yawgmoth_father_on_play_with_targets():
    """Yawgmoth, Father of Machines: on_play — expects DAMAGE to opp mobs+grid."""
    game, p1, p2 = _build_game()
    # Put an enemy mob on the battlefield row
    enemy_mob = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    # Put a grid object
    block = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Oak Planks"])
    block.state.mc_grid_x = 0
    block.state.mc_grid_y = 0
    game.state.minecraft_grid[p2.id][0][0] = block.id
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Yawgmoth, Father of Machines"])
    fn = MINECRAFT_CARDS["Yawgmoth, Father of Machines"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Yawgmoth on_play returned no events with targets present"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


# ─── on_play: opp discard / mill (with populated hand/library) ────────────

def test_card_null_on_play_opp_discards():
    """Null, the Empty Skin: on_play — expects ZONE_CHANGE (opp discards 2)."""
    game, p1, p2 = _build_game()
    # Populate p2's hand zone
    for cd in ["Zombie", "Spider"]:
        obj = _place_in_hand(game, p2.id, MINECRAFT_CARDS[cd])
        _add_to_hand_zone(game, p2.id, obj)
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Null, the Empty Skin"])
    fn = MINECRAFT_CARDS["Null, the Empty Skin"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Null on_play returned no events with opp hand populated"
    assert any(e.type == EventType.ZONE_CHANGE for e in events), \
        f"Expected ZONE_CHANGE, got {[e.type for e in events]}"


def test_card_ratman_on_play_opp_discards():
    """Ratman: on_play — expects ZONE_CHANGE (opp discards 1)."""
    game, p1, p2 = _build_game()
    obj = _place_in_hand(game, p2.id, MINECRAFT_CARDS["Zombie"])
    _add_to_hand_zone(game, p2.id, obj)
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Ratman"])
    fn = MINECRAFT_CARDS["Ratman"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Ratman on_play returned no events with opp hand populated"
    assert any(e.type == EventType.ZONE_CHANGE for e in events), \
        f"Expected ZONE_CHANGE, got {[e.type for e in events]}"


def test_card_elder_phantom_on_play_opp_discards():
    """Elder Phantom: on_play — expects ZONE_CHANGE (opp discards 1)."""
    game, p1, p2 = _build_game()
    obj = _place_in_hand(game, p2.id, MINECRAFT_CARDS["Zombie"])
    _add_to_hand_zone(game, p2.id, obj)
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Elder Phantom"])
    fn = MINECRAFT_CARDS["Elder Phantom"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Elder Phantom on_play returned no events with opp hand populated"
    assert any(e.type == EventType.ZONE_CHANGE for e in events), \
        f"Expected ZONE_CHANGE, got {[e.type for e in events]}"


def test_card_whispering_curse_on_play_opp_discards():
    """Whispering Curse: on_play — expects ZONE_CHANGE (opp discards 1)."""
    game, p1, p2 = _build_game()
    obj = _place_in_hand(game, p2.id, MINECRAFT_CARDS["Zombie"])
    _add_to_hand_zone(game, p2.id, obj)
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Whispering Curse"])
    fn = MINECRAFT_CARDS["Whispering Curse"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Whispering Curse returned no events with opp hand populated"
    assert any(e.type == EventType.ZONE_CHANGE for e in events), \
        f"Expected ZONE_CHANGE, got {[e.type for e in events]}"


def test_card_backrooms_trip_on_play_mills():
    """Backrooms Trip: on_play — expects ZONE_CHANGE (mills 3 from opp library)."""
    game, p1, p2 = _build_game()
    for cd in ["Zombie", "Spider", "Creeper"]:
        obj = _place_in_library(game, p2.id, MINECRAFT_CARDS[cd])
        _add_to_library_zone(game, p2.id, obj)
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Backrooms Trip"])
    fn = MINECRAFT_CARDS["Backrooms Trip"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Backrooms Trip returned no events with opp library populated"
    assert any(e.type == EventType.ZONE_CHANGE for e in events), \
        f"Expected ZONE_CHANGE, got {[e.type for e in events]}"


# ─── on_play: damage to sleep-stealer (avatar-direct damage) ──────────────

def test_card_sleep_stealer_on_play():
    """Sleep-Stealer: on_play — expects DAMAGE (deal 1 to opp avatar)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Sleep-Stealer"])
    fn = MINECRAFT_CARDS["Sleep-Stealer"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Sleep-Stealer on_play returned no events"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


# ─── on_play: aoe enemy mobs (with enemy mobs present) ────────────────────

def test_card_elesh_norn_on_play_with_enemy_mobs():
    """Elesh Norn: on_play — expects DAMAGE to opp mobs."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Elesh Norn, Grand Cenobite"])
    fn = MINECRAFT_CARDS["Elesh Norn, Grand Cenobite"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Elesh Norn on_play returned no events with opp mobs"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_tyrant_of_kher_ridges_on_play_with_enemy_mobs():
    """Tyrant of Kher Ridges: on_play — expects DAMAGE to opp mobs."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Tyrant of Kher Ridges"])
    fn = MINECRAFT_CARDS["Tyrant of Kher Ridges"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Tyrant on_play returned no events with opp mobs"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_warden_on_play_with_enemy_mobs():
    """Warden: on_play — expects DAMAGE to opp mobs when present."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Warden"])
    fn = MINECRAFT_CARDS["Warden"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Warden on_play returned no events with opp mobs"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_entity303_on_play_with_grid():
    """Entity 303: on_play — expects DAMAGE to opp grid objects when present."""
    game, p1, p2 = _build_game()
    block = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Oak Planks"])
    block.state.mc_grid_x = 0
    block.state.mc_grid_y = 0
    game.state.minecraft_grid[p2.id][0][0] = block.id
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Entity 303"])
    fn = MINECRAFT_CARDS["Entity 303"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Entity 303 on_play returned no events with opp grid object"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_wither_storm_on_play_with_targets():
    """Wither Storm: on_play — expects DAMAGE when opp mobs and/or grid present."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Wither Storm"])
    fn = MINECRAFT_CARDS["Wither Storm"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Wither Storm on_play returned no events with opp mob"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_wither_on_play_with_hostiles():
    """Wither: on_play — expects DAMAGE (2x Hostile count) when you control Hostiles."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Wither"])
    fn = MINECRAFT_CARDS["Wither"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Wither on_play returned no events with Hostile present"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_ender_dragon_on_play_with_diamond_cost_perm():
    """Ender Dragon: on_play — expects DAMAGE (2x diamond-cost perm count)."""
    game, p1, p2 = _build_game()
    # Diamond Sword has cost diamond=2 — place on p1's battlefield
    _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Diamond Sword"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Ender Dragon"])
    fn = MINECRAFT_CARDS["Ender Dragon"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Ender Dragon on_play returned no events with diamond-cost perm"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_iron_golem_on_play_with_workers():
    """Iron Golem: on_play — expects DAMAGE (2x Worker count) when Workers present."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Steve's Helper"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Iron Golem"])
    fn = MINECRAFT_CARDS["Iron Golem"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Iron Golem on_play returned no events with Worker present"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_sickening_dreams_on_play_with_mobs():
    """Sickening Dreams: on_play — expects DAMAGE when mobs are present."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Sickening Dreams"])
    fn = MINECRAFT_CARDS["Sickening Dreams"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Sickening Dreams returned no events with mobs on battlefield"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_black_suns_zenith_on_play_with_mobs():
    """Black Sun's Zenith: on_play — expects DAMAGE when mobs are present."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Black Sun's Zenith"])
    fn = MINECRAFT_CARDS["Black Sun's Zenith"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Black Sun's Zenith returned no events with mobs on battlefield"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_massacre_on_play_with_enemy_mobs():
    """Massacre: on_play — expects DAMAGE to opp mobs."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Massacre"])
    fn = MINECRAFT_CARDS["Massacre"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Massacre returned no events with opp mobs"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_the_wither_calls_on_play_with_enemy_mobs():
    """The Wither Calls: on_play — expects DAMAGE to opp mobs."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["The Wither Calls"])
    fn = MINECRAFT_CARDS["The Wither Calls"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "The Wither Calls returned no events with opp mobs"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_goatmans_hex_on_play_with_enemy_mobs():
    """Goatman's Hex: on_play — expects DAMAGE (1 to each opp mob)."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Goatman's Hex"])
    fn = MINECRAFT_CARDS["Goatman's Hex"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Goatman's Hex returned no events with opp mobs"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_sleep_deprivation_on_play():
    """Sleep Deprivation: on_play — expects DAMAGE to opp avatar."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Sleep Deprivation"])
    fn = MINECRAFT_CARDS["Sleep Deprivation"].mc_on_play
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Sleep Deprivation on_play returned no events"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_disfigure_on_play_with_target():
    """Disfigure: on_play — expects DAMAGE when given a target or hitting frontmost."""
    game, p1, p2 = _build_game()
    target = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Disfigure"])
    fn = MINECRAFT_CARDS["Disfigure"].mc_on_play
    events = fn(card, game.state, target_id=target.id)
    assert len(events) > 0, "Disfigure on_play returned no events with explicit target"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_voltage_surge_on_play_with_target():
    """Voltage Surge: on_play — expects DAMAGE when given a target."""
    game, p1, p2 = _build_game()
    target = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Voltage Surge"])
    fn = MINECRAFT_CARDS["Voltage Surge"].mc_on_play
    events = fn(card, game.state, target_id=target.id)
    assert len(events) > 0, "Voltage Surge on_play returned no events with explicit target"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_wither_skull_on_play_with_target():
    """Wither Skull: on_play — expects DAMAGE when given a target."""
    game, p1, p2 = _build_game()
    target = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Wither Skull"])
    fn = MINECRAFT_CARDS["Wither Skull"].mc_on_play
    events = fn(card, game.state, target_id=target.id)
    assert len(events) > 0, "Wither Skull on_play returned no events with explicit target"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_tnt_blast_on_play_with_target():
    """TNT Blast: on_play — expects DAMAGE when given a target."""
    game, p1, p2 = _build_game()
    target = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["TNT Blast"])
    fn = MINECRAFT_CARDS["TNT Blast"].mc_on_play
    events = fn(card, game.state, target_id=target.id)
    assert len(events) > 0, "TNT Blast on_play returned no events with explicit target"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


# ─── on_play: destroy ──────────────────────────────────────────────────────

def test_card_herobrine_on_play_with_target():
    """Herobrine, World's Eye: on_play — expects OBJECT_DESTROYED when target mob given."""
    game, p1, p2 = _build_game()
    target = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Herobrine, World's Eye"])
    fn = MINECRAFT_CARDS["Herobrine, World's Eye"].mc_on_play
    events = fn(card, game.state, target_id=target.id)
    assert len(events) > 0, "Herobrine on_play returned no events with target mob"
    assert any(e.type == EventType.OBJECT_DESTROYED for e in events), \
        f"Expected OBJECT_DESTROYED, got {[e.type for e in events]}"


def test_card_putrefy_on_play_with_target():
    """Putrefy: on_play — expects OBJECT_DESTROYED when target mob given."""
    game, p1, p2 = _build_game()
    target = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Putrefy"])
    fn = MINECRAFT_CARDS["Putrefy"].mc_on_play
    events = fn(card, game.state, target_id=target.id)
    assert len(events) > 0, "Putrefy on_play returned no events with target mob"
    assert any(e.type == EventType.OBJECT_DESTROYED for e in events), \
        f"Expected OBJECT_DESTROYED, got {[e.type for e in events]}"


def test_card_drag_to_the_dark_on_play_with_low_hp_target():
    """Drag to the Dark: on_play — expects OBJECT_DESTROYED for mob with ≤3 HP."""
    game, p1, p2 = _build_game()
    target = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    # Zombie has 2 toughness — under threshold of 3
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Drag to the Dark"])
    fn = MINECRAFT_CARDS["Drag to the Dark"].mc_on_play
    events = fn(card, game.state, target_id=target.id)
    assert len(events) > 0, "Drag to the Dark returned no events with a low-HP target"
    assert any(e.type == EventType.OBJECT_DESTROYED for e in events), \
        f"Expected OBJECT_DESTROYED, got {[e.type for e in events]}"


def test_card_phyrexian_rebirth_on_play_with_mobs():
    """Phyrexian Rebirth: on_play with mobs — expects OBJECT_DESTROYED + CREATE_TOKEN."""
    game, p1, p2 = _build_game()
    _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Phyrexian Rebirth"])
    fn = MINECRAFT_CARDS["Phyrexian Rebirth"].mc_on_play
    events = fn(card, game.state, target_id=None)
    types = {e.type for e in events}
    assert EventType.OBJECT_DESTROYED in types or EventType.CREATE_TOKEN in types, \
        f"Expected OBJECT_DESTROYED or CREATE_TOKEN in {types}"


# ─── on_attack callbacks ───────────────────────────────────────────────────

def test_card_blaze_on_attack():
    """Blaze: on_attack — expects DAMAGE to opponent's avatar (1 chip damage)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Blaze"])
    fn = MINECRAFT_CARDS["Blaze"].mc_on_attack
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Blaze on_attack returned no events"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_the_man_from_the_fog_on_attack():
    """The Man From The Fog: on_attack — expects DAMAGE (2 to avatar)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["The Man From The Fog"])
    fn = MINECRAFT_CARDS["The Man From The Fog"].mc_on_attack
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "The Man From The Fog on_attack returned no events"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_urabrask_on_attack():
    """Urabrask, the Heretic: on_attack — expects DAMAGE (1 to opponent)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Urabrask, the Heretic"])
    fn = MINECRAFT_CARDS["Urabrask, the Heretic"].mc_on_attack
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Urabrask on_attack returned no events"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_glissa_on_attack_with_target():
    """Glissa, the Traitor: on_attack — expects DRAW when a valid target is given."""
    game, p1, p2 = _build_game()
    target = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Glissa, the Traitor"])
    fn = MINECRAFT_CARDS["Glissa, the Traitor"].mc_on_attack
    events = fn(card, game.state, target_id=target.id)
    assert len(events) > 0, "Glissa on_attack returned no events with target"
    assert any(e.type == EventType.DRAW for e in events), \
        f"Expected DRAW, got {[e.type for e in events]}"


def test_card_sculk_stalker_on_attack():
    """Sculk Stalker: on_attack — expects MC_MATERIAL_GAIN (1 redstone)."""
    game, p1, p2 = _build_game()
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Sculk Stalker"])
    fn = MINECRAFT_CARDS["Sculk Stalker"].mc_on_attack
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Sculk Stalker on_attack returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_cave_dweller_on_attack_with_opp_hand():
    """Cave Dweller: on_attack — expects ZONE_CHANGE (opp discards 1) with opp hand populated."""
    game, p1, p2 = _build_game()
    obj = _place_in_hand(game, p2.id, MINECRAFT_CARDS["Zombie"])
    _add_to_hand_zone(game, p2.id, obj)
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Cave Dweller"])
    fn = MINECRAFT_CARDS["Cave Dweller"].mc_on_attack
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Cave Dweller on_attack returned no events with opp hand populated"
    assert any(e.type == EventType.ZONE_CHANGE for e in events), \
        f"Expected ZONE_CHANGE, got {[e.type for e in events]}"


def test_card_goatman_on_attack_with_opp_hand():
    """Goatman, Crooked Stalker: on_attack — expects ZONE_CHANGE (opp discards 1)."""
    game, p1, p2 = _build_game()
    obj = _place_in_hand(game, p2.id, MINECRAFT_CARDS["Zombie"])
    _add_to_hand_zone(game, p2.id, obj)
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Goatman, Crooked Stalker"])
    fn = MINECRAFT_CARDS["Goatman, Crooked Stalker"].mc_on_attack
    events = fn(card, game.state, target_id=None)
    assert len(events) > 0, "Goatman on_attack returned no events with opp hand populated"
    assert any(e.type == EventType.ZONE_CHANGE for e in events), \
        f"Expected ZONE_CHANGE, got {[e.type for e in events]}"


# ─── on_block callbacks ────────────────────────────────────────────────────

def test_card_snow_golem_on_block():
    """Snow Golem: on_block — expects DAMAGE (1 to attacker)."""
    game, p1, p2 = _build_game()
    attacker = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Snow Golem"])
    fn = MINECRAFT_CARDS["Snow Golem"].mc_on_block
    events = fn(card, game.state, attacker_id=attacker.id)
    assert len(events) > 0, "Snow Golem on_block returned no events with attacker"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


def test_card_axolotl_guardian_on_block():
    """Axolotl Guardian: on_block — expects MC_MATERIAL_GAIN (1 wood)."""
    game, p1, p2 = _build_game()
    attacker = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Axolotl Guardian"])
    fn = MINECRAFT_CARDS["Axolotl Guardian"].mc_on_block
    events = fn(card, game.state, attacker_id=attacker.id)
    assert len(events) > 0, "Axolotl Guardian on_block returned no events"
    assert any(e.type == EventType.MC_MATERIAL_GAIN for e in events), \
        f"Expected MC_MATERIAL_GAIN, got {[e.type for e in events]}"


def test_card_shulker_sentry_on_block():
    """Shulker Sentry: on_block — expects CREATE_TOKEN (0/2 Shulker Bullet)."""
    game, p1, p2 = _build_game()
    attacker = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Shulker Sentry"])
    fn = MINECRAFT_CARDS["Shulker Sentry"].mc_on_block
    events = fn(card, game.state, attacker_id=attacker.id)
    assert len(events) > 0, "Shulker Sentry on_block returned no events"
    assert any(e.type == EventType.CREATE_TOKEN for e in events), \
        f"Expected CREATE_TOKEN, got {[e.type for e in events]}"


def test_card_whispering_wraith_on_block():
    """Whispering Wraith: on_block — expects DAMAGE (1 to attacker)."""
    game, p1, p2 = _build_game()
    attacker = _place_on_battlefield(game, p2.id, MINECRAFT_CARDS["Zombie"])
    card = _place_on_battlefield(game, p1.id, MINECRAFT_CARDS["Whispering Wraith"])
    fn = MINECRAFT_CARDS["Whispering Wraith"].mc_on_block
    events = fn(card, game.state, attacker_id=attacker.id)
    assert len(events) > 0, "Whispering Wraith on_block returned no events"
    assert any(e.type == EventType.DAMAGE for e in events), \
        f"Expected DAMAGE, got {[e.type for e in events]}"


# ---------------------------------------------------------------------------
# Entry point — run all tests and summarise
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import traceback

    tests = [(k, v) for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    passed, failed, errors = [], [], []
    for name, fn in tests:
        try:
            fn()
            passed.append(name)
        except AssertionError as exc:
            failed.append((name, str(exc)))
        except Exception as exc:
            errors.append((name, f"{type(exc).__name__}: {exc}"))

    print(f"\n=== Interceptor verification: minecraft ===")
    print(f"  passed:  {len(passed)}")
    print(f"  failed:  {len(failed)}")
    print(f"  errors:  {len(errors)}")
    print(f"  skipped: {len(SKIPPED_CARDS)} (see SKIPPED_CARDS dict at top of file)")
    total_run = len(passed) + len(failed) + len(errors)
    if total_run:
        rate = len(passed) / total_run * 100
        print(f"  pass rate: {rate:.1f}% (over {total_run} runnable tests)")
    if failed:
        print("\n--- FAILURES (first 30) ---")
        for n, msg in failed[:30]:
            print(f"  {n}: {msg}")
    if errors:
        print("\n--- ERRORS (first 30) ---")
        for n, msg in errors[:30]:
            print(f"  {n}: {msg}")
    sys.exit(0 if not failed and not errors else 1)
