"""
Smoke tests for FINA — generated by scripts/new_set/wire_set.py.

Asserts:
  - every card in the set imports without error
  - every card has a CardDefinition with name + characteristics
  - every starter deck builder runs without raising and returns a
    non-empty list of CardDefinitions

The "every card actually resolves in play" guarantee is enforced by the
balance-loop coverage stage (scripts/new_set/balance_loop.py +
scripts/new_set/coverage.py), which can detect missing implementations
via zero-play cards across the tournament — that check is engine-aware
where this scaffold is engine-agnostic by design.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src.cards.finance.fina import FINA_CARDS, build_high_frequency_deck, build_derivatives_deck, build_quant_deck, build_dark_arbitrage_deck


def test_every_card_loads():
    assert FINA_CARDS, "FINA card registry is empty"
    for name, card in FINA_CARDS.items():
        assert card is not None, f"{name}: card def is None"
        assert card.name, f"{name}: card has no .name"
        assert card.characteristics is not None, \
            f"{name}: card has no .characteristics"


def test_deck_FINA_high_frequency_builds():
    deck = build_high_frequency_deck()
    assert deck, "FINA_high_frequency builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "FINA_high_frequency contains a None card"
        assert getattr(cd, "name", None), "FINA_high_frequency contains a nameless card"

def test_deck_FINA_derivatives_builds():
    deck = build_derivatives_deck()
    assert deck, "FINA_derivatives builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "FINA_derivatives contains a None card"
        assert getattr(cd, "name", None), "FINA_derivatives contains a nameless card"

def test_deck_FINA_quant_builds():
    deck = build_quant_deck()
    assert deck, "FINA_quant builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "FINA_quant contains a None card"
        assert getattr(cd, "name", None), "FINA_quant contains a nameless card"

def test_deck_FINA_dark_arbitrage_builds():
    deck = build_dark_arbitrage_deck()
    assert deck, "FINA_dark_arbitrage builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "FINA_dark_arbitrage contains a None card"
        assert getattr(cd, "name", None), "FINA_dark_arbitrage contains a nameless card"



if __name__ == "__main__":
    test_every_card_loads()
    test_deck_FINA_high_frequency_builds()
    test_deck_FINA_derivatives_builds()
    test_deck_FINA_quant_builds()
    test_deck_FINA_dark_arbitrage_builds()
    print("OK — FINA smoke tests pass.")
