"""Auto-generated interceptor verification for custom/studio_ghibli.

Generated by /test-interceptors. Do not hand-edit -- regenerate via the skill.

Header in src/cards/custom/studio_ghibli.py at line 749 reads:

    # Slice-6C median-lift setup functions (2026-05-19)
    # Recipe (per DBZ slice-4 / 47a2c5cb + ZLD slice-8A / 64a11535): each effect_fn
    # reads state.zones (zone axis), counts allies/threats by subtype (state axis),
    # and emits SCRY/SURVEIL + cross-controller LIFE_CHANGE.

And at line 4803:

    # Slice-6A median-lift helpers (2026-05-19, Ghibli Forest Spirits)
    # Pattern mirrors ZLD slice-8C commits 64a11535/7c6862a9/f03164c5/...

This is a depth_v2 retrofit -- many setups are wrappers whose effect_fn emits
SCRY / SURVEIL / LIFE_CHANGE / DAMAGE / DRAW regardless of the card's actual
rules text. Tests sometimes pass on the wrong event type; compare expected vs
emitted in the failure message to diagnose.

Total: 215 cards. Sampled: 150 testable cards. 18 skipped.
"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.engine import Game, Event, EventType, ZoneType
from src.cards.custom.studio_ghibli import STUDIO_GHIBLI_CARDS


SKIPPED_CARDS = {
    'Aerial Reconnaissance': 'conditional — replacement effect or rider',
    'Burning Wrath': 'conditional — replacement effect or rider',
    "Calcifer's Flame": 'conditional — replacement effect or rider',
    'Counterspell of the Deep': 'counterspell — needs stack target',
    'Fire Breath': 'conditional — replacement effect or rider',
    "Granmamare's Hospitality": 'conditional — replacement effect or rider',
    'Kiki, Witch on Errands': 'modal — needs human mode selection',
    "Mei's Forest Friend": 'conditional — replacement effect or rider',
    'Ohmu, Forest Architect': 'modal — needs human mode selection',
    'Rapid Growth': 'conditional — replacement effect or rider',
    'San, Wolf-Sister Ascendant': 'modal — needs human mode selection',
    'Sheeta, Crystal Heir': 'modal — needs human mode selection',
    'Spirit Fire': 'conditional — replacement effect or rider',
    'Spirit Guidance': 'conditional — replacement effect or rider',
    'Suspect the Conspirators': 'modal — needs human mode selection',
    'Terror of the Deep': 'conditional — replacement effect or rider',
    'Totoro, Spirit of the Camphor Tree': 'modal — needs human mode selection',
    'Wind Shield': 'conditional — replacement effect or rider',
}


def create_permanent_on_battlefield(game, player, card_name):
    """Create a permanent in HAND then move to battlefield via ZONE_CHANGE so
    interceptors register exactly once."""
    card_def = STUDIO_GHIBLI_CARDS[card_name]
    obj = game.create_object(
        name=card_name,
        owner_id=player.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{player.id}',
            'to_zone': 'battlefield',
            'to_zone_type': ZoneType.BATTLEFIELD,
        },
    ))
    return obj


def assert_emit_or_register(game, expected, card_name):
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            raise AssertionError(
                f"expected one of {expected} in event_log, got {sorted(got_types - {'ZONE_CHANGE'})}"
            )
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_name}"


def test_card_chihiro_spirited_child():
    """Chihiro, Spirited Child: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Chihiro, Spirited Child')
    expected = []
    assert_emit_or_register(game, expected, 'Chihiro, Spirited Child')

def test_card_ashitaka_cursed_prince():
    """Ashitaka, Cursed Prince: expects ['OBJECT_DESTROYED']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Ashitaka, Cursed Prince')
    expected = ['OBJECT_DESTROYED']
    assert_emit_or_register(game, expected, 'Ashitaka, Cursed Prince')

def test_card_san_wolf_princess():
    """San, Wolf Princess: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'San, Wolf Princess')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'San, Wolf Princess')

def test_card_sophie_cursed_girl():
    """Sophie, Cursed Girl: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Sophie, Cursed Girl')
    expected = []
    assert_emit_or_register(game, expected, 'Sophie, Cursed Girl')

def test_card_sheeta_princess_of_laputa():
    """Sheeta, Princess of Laputa: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Sheeta, Princess of Laputa')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Sheeta, Princess of Laputa')

def test_card_pazu_young_mechanic():
    """Pazu, Young Mechanic: expects ['DRAW']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Pazu, Young Mechanic')
    expected = ['DRAW']
    assert_emit_or_register(game, expected, 'Pazu, Young Mechanic')

def test_card_nausicaa_princess_of_the_wind():
    """Nausicaa, Princess of the Wind: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Nausicaa, Princess of the Wind')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'Nausicaa, Princess of the Wind')

def test_card_no_face_hungry_spirit():
    """No-Face, Hungry Spirit: expects ['COUNTER_ADDED']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'No-Face, Hungry Spirit')
    expected = ['COUNTER_ADDED']
    assert_emit_or_register(game, expected, 'No-Face, Hungry Spirit')

def test_card_chihiro_bridge_between_worlds():
    """Chihiro, Bridge Between Worlds: expects ['SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Chihiro, Bridge Between Worlds')
    expected = ['SCRY']
    assert_emit_or_register(game, expected, 'Chihiro, Bridge Between Worlds')

def test_card_witch_of_the_waste_fading_splendor():
    """Witch of the Waste, Fading Splendor: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Witch of the Waste, Fading Splendor')
    expected = []
    assert_emit_or_register(game, expected, 'Witch of the Waste, Fading Splendor')

def test_card_mononoke_s_last_hunt():
    """Mononoke's Last Hunt: expects ['DRAW', 'DISCARD', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, "Mononoke's Last Hunt")
    expected = ['DRAW', 'DISCARD', 'SCRY']
    assert_emit_or_register(game, expected, "Mononoke's Last Hunt")

def test_card_lin_bathhouse_worker():
    """Lin, Bathhouse Worker: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Lin, Bathhouse Worker')
    expected = []
    assert_emit_or_register(game, expected, 'Lin, Bathhouse Worker')

def test_card_zeniba_the_good_witch():
    """Zeniba, the Good Witch: expects ['DRAW']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Zeniba, the Good Witch')
    expected = ['DRAW']
    assert_emit_or_register(game, expected, 'Zeniba, the Good Witch')

def test_card_satsuki_brave_sister():
    """Satsuki, Brave Sister: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Satsuki, Brave Sister')
    expected = []
    assert_emit_or_register(game, expected, 'Satsuki, Brave Sister')

def test_card_mei_curious_child():
    """Mei, Curious Child: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Mei, Curious Child')
    expected = []
    assert_emit_or_register(game, expected, 'Mei, Curious Child')

def test_card_turnip_head_cursed_prince():
    """Turnip Head, Cursed Prince: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Turnip Head, Cursed Prince')
    expected = []
    assert_emit_or_register(game, expected, 'Turnip Head, Cursed Prince')

def test_card_kiki_delivery_witch():
    """Kiki, Delivery Witch: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Kiki, Delivery Witch')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Kiki, Delivery Witch')

def test_card_jiji_black_cat_familiar():
    """Jiji, Black Cat Familiar: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Jiji, Black Cat Familiar')
    expected = []
    assert_emit_or_register(game, expected, 'Jiji, Black Cat Familiar')

def test_card_kaguya_moon_princess():
    """Kaguya, Moon Princess: expects ['DRAW']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Kaguya, Moon Princess')
    expected = ['DRAW']
    assert_emit_or_register(game, expected, 'Kaguya, Moon Princess')

def test_card_bathhouse_servant():
    """Bathhouse Servant: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Bathhouse Servant')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Bathhouse Servant')

def test_card_valley_villager():
    """Valley Villager: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Valley Villager')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Valley Villager')

def test_card_irontown_worker():
    """Irontown Worker: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Irontown Worker')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Irontown Worker')

def test_card_refugee_child():
    """Refugee Child: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Refugee Child')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Refugee Child')

def test_card_castle_guardian():
    """Castle Guardian: expects ['LIFE_CHANGE', 'COUNTER_ADDED']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Castle Guardian')
    expected = ['LIFE_CHANGE', 'COUNTER_ADDED']
    assert_emit_or_register(game, expected, 'Castle Guardian')

def test_card_wind_rider_cadet():
    """Wind Rider Cadet: expects ['DRAW']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Wind Rider Cadet')
    expected = ['DRAW']
    assert_emit_or_register(game, expected, 'Wind Rider Cadet')

def test_card_young_witch_apprentice():
    """Young Witch Apprentice: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Young Witch Apprentice')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Young Witch Apprentice')

def test_card_pejite_refugee():
    """Pejite Refugee: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Pejite Refugee')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Pejite Refugee')

def test_card_porco_rosso_sky_pirate():
    """Porco Rosso, Sky Pirate: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Porco Rosso, Sky Pirate')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'Porco Rosso, Sky Pirate')

def test_card_seaplane_mechanic():
    """Seaplane Mechanic: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Seaplane Mechanic')
    expected = []
    assert_emit_or_register(game, expected, 'Seaplane Mechanic')

def test_card_lady_eboshi_iron_town_leader():
    """Lady Eboshi, Iron Town Leader: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Lady Eboshi, Iron Town Leader')
    expected = []
    assert_emit_or_register(game, expected, 'Lady Eboshi, Iron Town Leader')

def test_card_spirit_protection():
    """Spirit Protection: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Spirit Protection')
    expected = []
    assert_emit_or_register(game, expected, 'Spirit Protection')

def test_card_bathhouse_sanctuary():
    """Bathhouse Sanctuary: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Bathhouse Sanctuary')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Bathhouse Sanctuary')

def test_card_haku_river_spirit():
    """Haku, River Spirit: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Haku, River Spirit')
    expected = []
    assert_emit_or_register(game, expected, 'Haku, River Spirit')

def test_card_river_spirit():
    """River Spirit: expects ['DRAW', 'LIFE_CHANGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'River Spirit')
    expected = ['DRAW', 'LIFE_CHANGE', 'SCRY']
    assert_emit_or_register(game, expected, 'River Spirit')

def test_card_stink_spirit():
    """Stink Spirit: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Stink Spirit')
    expected = []
    assert_emit_or_register(game, expected, 'Stink Spirit')

def test_card_laputa_robot_guardian():
    """Laputa Robot Guardian: expects ['DRAW']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Laputa Robot Guardian')
    expected = ['DRAW']
    assert_emit_or_register(game, expected, 'Laputa Robot Guardian')

def test_card_laputa_robot_gardener():
    """Laputa Robot Gardener: expects ['LIFE_CHANGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Laputa Robot Gardener')
    expected = ['LIFE_CHANGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Laputa Robot Gardener')

def test_card_muska_fallen_prince():
    """Muska, Fallen Prince: expects ['DRAW']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Muska, Fallen Prince')
    expected = ['DRAW']
    assert_emit_or_register(game, expected, 'Muska, Fallen Prince')

def test_card_ponyo_fish_girl():
    """Ponyo, Fish Girl: expects ['LIFE_CHANGE', 'COUNTER_ADDED']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Ponyo, Fish Girl')
    expected = ['LIFE_CHANGE', 'COUNTER_ADDED']
    assert_emit_or_register(game, expected, 'Ponyo, Fish Girl')

def test_card_sosuke_young_sailor():
    """Sosuke, Young Sailor: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Sosuke, Young Sailor')
    expected = []
    assert_emit_or_register(game, expected, 'Sosuke, Young Sailor')

def test_card_granmamare_sea_goddess():
    """Granmamare, Sea Goddess: expects ['LIFE_CHANGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Granmamare, Sea Goddess')
    expected = ['LIFE_CHANGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Granmamare, Sea Goddess')

def test_card_flying_fish_spirit():
    """Flying Fish Spirit: expects ['LIFE_CHANGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Flying Fish Spirit')
    expected = ['LIFE_CHANGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Flying Fish Spirit')

def test_card_cloud_elemental():
    """Cloud Elemental: expects ['LIFE_CHANGE', 'SCRY', 'SURVEIL']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Cloud Elemental')
    expected = ['LIFE_CHANGE', 'SCRY', 'SURVEIL']
    assert_emit_or_register(game, expected, 'Cloud Elemental')

def test_card_bathhouse_frog():
    """Bathhouse Frog: expects ['LIFE_CHANGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Bathhouse Frog')
    expected = ['LIFE_CHANGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Bathhouse Frog')

def test_card_minor_water_spirit():
    """Minor Water Spirit: expects ['LIFE_CHANGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Minor Water Spirit')
    expected = ['LIFE_CHANGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Minor Water Spirit')

def test_card_sky_pirate():
    """Sky Pirate: expects ['DAMAGE', 'DISCARD']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Sky Pirate')
    expected = ['DAMAGE', 'DISCARD']
    assert_emit_or_register(game, expected, 'Sky Pirate')

def test_card_tiger_moth_crew():
    """Tiger Moth Crew: expects ['DRAW', 'LIFE_CHANGE', 'DISCARD', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Tiger Moth Crew')
    expected = ['DRAW', 'LIFE_CHANGE', 'DISCARD', 'SCRY']
    assert_emit_or_register(game, expected, 'Tiger Moth Crew')

def test_card_dola_sky_pirate_captain():
    """Dola, Sky Pirate Captain: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Dola, Sky Pirate Captain')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'Dola, Sky Pirate Captain')

def test_card_wind_mage():
    """Wind Mage: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Wind Mage')
    expected = []
    assert_emit_or_register(game, expected, 'Wind Mage')

def test_card_airship_navigator():
    """Airship Navigator: expects ['SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Airship Navigator')
    expected = ['SCRY']
    assert_emit_or_register(game, expected, 'Airship Navigator')

def test_card_mystical_guardian():
    """Mystical Guardian: expects ['LIFE_CHANGE', 'SCRY', 'SURVEIL']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Mystical Guardian')
    expected = ['LIFE_CHANGE', 'SCRY', 'SURVEIL']
    assert_emit_or_register(game, expected, 'Mystical Guardian')

def test_card_howling_wind_spirit():
    """Howling Wind Spirit: expects ['SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Howling Wind Spirit')
    expected = ['SCRY']
    assert_emit_or_register(game, expected, 'Howling Wind Spirit')

def test_card_river_s_blessing():
    """River's Blessing: expects ['LIFE_CHANGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, "River's Blessing")
    expected = ['LIFE_CHANGE', 'SCRY']
    assert_emit_or_register(game, expected, "River's Blessing")

def test_card_sky_domain():
    """Sky Domain: expects ['DRAW', 'LIFE_CHANGE', 'DAMAGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Sky Domain')
    expected = ['DRAW', 'LIFE_CHANGE', 'DAMAGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Sky Domain')

def test_card_yubaba_bathhouse_witch():
    """Yubaba, Bathhouse Witch: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Yubaba, Bathhouse Witch')
    expected = []
    assert_emit_or_register(game, expected, 'Yubaba, Bathhouse Witch')

def test_card_boh_giant_baby():
    """Boh, Giant Baby: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Boh, Giant Baby')
    expected = []
    assert_emit_or_register(game, expected, 'Boh, Giant Baby')

def test_card_moro_wolf_god():
    """Moro, Wolf God: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Moro, Wolf God')
    expected = []
    assert_emit_or_register(game, expected, 'Moro, Wolf God')

def test_card_okkoto_boar_god():
    """Okkoto, Boar God: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Okkoto, Boar God')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'Okkoto, Boar God')

def test_card_demon_boar():
    """Demon Boar: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Demon Boar')
    expected = []
    assert_emit_or_register(game, expected, 'Demon Boar')

def test_card_god_warrior():
    """God Warrior: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'God Warrior')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'God Warrior')

def test_card_curse_spirit():
    """Curse Spirit: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Curse Spirit')
    expected = []
    assert_emit_or_register(game, expected, 'Curse Spirit')

def test_card_shadow_spirit():
    """Shadow Spirit: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Shadow Spirit')
    expected = []
    assert_emit_or_register(game, expected, 'Shadow Spirit')

def test_card_corrupted_kodama():
    """Corrupted Kodama: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Corrupted Kodama')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Corrupted Kodama')

def test_card_spirit_of_vengeance():
    """Spirit of Vengeance: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Spirit of Vengeance')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Spirit of Vengeance')

def test_card_dark_forest_creature():
    """Dark Forest Creature: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Dark Forest Creature')
    expected = []
    assert_emit_or_register(game, expected, 'Dark Forest Creature')

def test_card_witch_s_familiar():
    """Witch's Familiar: expects ['DRAW']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, "Witch's Familiar")
    expected = ['DRAW']
    assert_emit_or_register(game, expected, "Witch's Familiar")

def test_card_bathhouse_specter():
    """Bathhouse Specter: expects ['DAMAGE', 'DISCARD']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Bathhouse Specter')
    expected = ['DAMAGE', 'DISCARD']
    assert_emit_or_register(game, expected, 'Bathhouse Specter')

def test_card_nightmare_creature():
    """Nightmare Creature: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Nightmare Creature')
    expected = []
    assert_emit_or_register(game, expected, 'Nightmare Creature')

def test_card_toxic_jungle_lurker():
    """Toxic Jungle Lurker: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Toxic Jungle Lurker')
    expected = []
    assert_emit_or_register(game, expected, 'Toxic Jungle Lurker')

def test_card_fallen_samurai():
    """Fallen Samurai: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Fallen Samurai')
    expected = []
    assert_emit_or_register(game, expected, 'Fallen Samurai')

def test_card_curse_of_the_witch():
    """Curse of the Witch: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Curse of the Witch')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'Curse of the Witch')

def test_card_dark_forest_pact():
    """Dark Forest Pact: expects ['DRAW']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Dark Forest Pact')
    expected = ['DRAW']
    assert_emit_or_register(game, expected, 'Dark Forest Pact')

def test_card_calcifer_fire_demon():
    """Calcifer, Fire Demon: expects ['DRAW', 'DISCARD']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Calcifer, Fire Demon')
    expected = ['DRAW', 'DISCARD']
    assert_emit_or_register(game, expected, 'Calcifer, Fire Demon')

def test_card_howl_wandering_wizard():
    """Howl, Wandering Wizard: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Howl, Wandering Wizard')
    expected = []
    assert_emit_or_register(game, expected, 'Howl, Wandering Wizard')

def test_card_witch_of_the_waste():
    """Witch of the Waste: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Witch of the Waste')
    expected = []
    assert_emit_or_register(game, expected, 'Witch of the Waste')

def test_card_markl_howl_s_apprentice():
    """Markl, Howl's Apprentice: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, "Markl, Howl's Apprentice")
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, "Markl, Howl's Apprentice")

def test_card_torumekian_soldier():
    """Torumekian Soldier: expects ['DAMAGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Torumekian Soldier')
    expected = ['DAMAGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Torumekian Soldier')

def test_card_kushana_war_princess():
    """Kushana, War Princess: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Kushana, War Princess')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Kushana, War Princess')

def test_card_goliath_airship():
    """Goliath Airship: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Goliath Airship')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'Goliath Airship')

def test_card_fire_spirit():
    """Fire Spirit: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Fire Spirit')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'Fire Spirit')

def test_card_flame_elemental():
    """Flame Elemental: expects ['DAMAGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Flame Elemental')
    expected = ['DAMAGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Flame Elemental')

def test_card_volcanic_spirit():
    """Volcanic Spirit: expects ['DAMAGE', 'SURVEIL']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Volcanic Spirit')
    expected = ['DAMAGE', 'SURVEIL']
    assert_emit_or_register(game, expected, 'Volcanic Spirit')

def test_card_destruction_spirit():
    """Destruction Spirit: expects ['DAMAGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Destruction Spirit')
    expected = ['DAMAGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Destruction Spirit')

def test_card_pejite_warrior():
    """Pejite Warrior: expects ['DAMAGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Pejite Warrior')
    expected = ['DAMAGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Pejite Warrior')

def test_card_forest_arsonist():
    """Forest Arsonist: expects ['LIFE_CHANGE', 'DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Forest Arsonist')
    expected = ['LIFE_CHANGE', 'DAMAGE']
    assert_emit_or_register(game, expected, 'Forest Arsonist')

def test_card_wild_boar():
    """Wild Boar: expects ['DAMAGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Wild Boar')
    expected = ['DAMAGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Wild Boar')

def test_card_angry_spirit():
    """Angry Spirit: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Angry Spirit')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'Angry Spirit')

def test_card_ironworks_furnace():
    """Ironworks Furnace: expects ['DAMAGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Ironworks Furnace')
    expected = ['DAMAGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Ironworks Furnace')

def test_card_bombardment_crew():
    """Bombardment Crew: expects ['DAMAGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Bombardment Crew')
    expected = ['DAMAGE', 'SCRY']
    assert_emit_or_register(game, expected, 'Bombardment Crew')

def test_card_fires_of_destruction():
    """Fires of Destruction: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Fires of Destruction')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'Fires of Destruction')

def test_card_war_drums():
    """War Drums: expects ['DAMAGE', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'War Drums')
    expected = ['DAMAGE', 'SCRY']
    assert_emit_or_register(game, expected, 'War Drums')

def test_card_totoro_king_of_the_forest():
    """Totoro, King of the Forest: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Totoro, King of the Forest')
    expected = []
    assert_emit_or_register(game, expected, 'Totoro, King of the Forest')

def test_card_catbus_forest_transport():
    """Catbus, Forest Transport: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Catbus, Forest Transport')
    expected = []
    assert_emit_or_register(game, expected, 'Catbus, Forest Transport')

def test_card_chibi_totoro():
    """Chibi Totoro: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Chibi Totoro')
    expected = []
    assert_emit_or_register(game, expected, 'Chibi Totoro')

def test_card_medium_totoro():
    """Medium Totoro: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Medium Totoro')
    expected = []
    assert_emit_or_register(game, expected, 'Medium Totoro')

def test_card_forest_spirit_shishigami():
    """Forest Spirit, Shishigami: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Forest Spirit, Shishigami')
    expected = []
    assert_emit_or_register(game, expected, 'Forest Spirit, Shishigami')

def test_card_kodama_elder():
    """Kodama Elder: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Kodama Elder')
    expected = []
    assert_emit_or_register(game, expected, 'Kodama Elder')

def test_card_wolf_of_moro():
    """Wolf of Moro: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Wolf of Moro')
    expected = []
    assert_emit_or_register(game, expected, 'Wolf of Moro')

def test_card_ohmu_king_of_insects():
    """Ohmu, King of Insects: expects ['DAMAGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Ohmu, King of Insects')
    expected = ['DAMAGE']
    assert_emit_or_register(game, expected, 'Ohmu, King of Insects')

def test_card_baby_ohmu():
    """Baby Ohmu: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Baby Ohmu')
    expected = []
    assert_emit_or_register(game, expected, 'Baby Ohmu')

def test_card_toxic_jungle_guardian():
    """Toxic Jungle Guardian: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Toxic Jungle Guardian')
    expected = []
    assert_emit_or_register(game, expected, 'Toxic Jungle Guardian')

def test_card_forest_kodama():
    """Forest Kodama: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Forest Kodama')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Forest Kodama')

def test_card_kodama_of_growth():
    """Kodama of Growth: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Kodama of Growth')
    expected = []
    assert_emit_or_register(game, expected, 'Kodama of Growth')

def test_card_ancient_tree_spirit():
    """Ancient Tree Spirit: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Ancient Tree Spirit')
    expected = []
    assert_emit_or_register(game, expected, 'Ancient Tree Spirit')

def test_card_forest_guardian():
    """Forest Guardian: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Forest Guardian')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Forest Guardian')

def test_card_nature_sprite():
    """Nature Sprite: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Nature Sprite')
    expected = []
    assert_emit_or_register(game, expected, 'Nature Sprite')

def test_card_soot_sprites():
    """Soot Sprites: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Soot Sprites')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Soot Sprites')

def test_card_wild_wolf():
    """Wild Wolf: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Wild Wolf')
    expected = []
    assert_emit_or_register(game, expected, 'Wild Wolf')

def test_card_forest_deer():
    """Forest Deer: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Forest Deer')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Forest Deer')

def test_card_giant_camphor_tree():
    """Giant Camphor Tree: expects ['COUNTER_ADDED']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Giant Camphor Tree')
    expected = ['COUNTER_ADDED']
    assert_emit_or_register(game, expected, 'Giant Camphor Tree')

def test_card_insect_swarm():
    """Insect Swarm: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Insect Swarm')
    expected = []
    assert_emit_or_register(game, expected, 'Insect Swarm')

def test_card_moss_covered_golem():
    """Moss-Covered Golem: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Moss-Covered Golem')
    expected = []
    assert_emit_or_register(game, expected, 'Moss-Covered Golem')

def test_card_spirit_wolf_pup():
    """Spirit Wolf Pup: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Spirit Wolf Pup')
    expected = []
    assert_emit_or_register(game, expected, 'Spirit Wolf Pup')

def test_card_forest_s_blessing():
    """Forest's Blessing: expects [] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS["Forest's Blessing"]
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name="Forest's Blessing",
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = []
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_nature_s_shield():
    """Nature's Shield: expects [] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS["Nature's Shield"]
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name="Nature's Shield",
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = []
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_regrowth_spell():
    """Regrowth Spell: expects [] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS['Regrowth Spell']
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name='Regrowth Spell',
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = []
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_spirit_call():
    """Spirit Call: expects [] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS['Spirit Call']
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name='Spirit Call',
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = []
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_forest_awakening():
    """Forest Awakening: expects [] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS['Forest Awakening']
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name='Forest Awakening',
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = []
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_call_of_the_wild():
    """Call of the Wild: expects [] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS['Call of the Wild']
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name='Call of the Wild',
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = []
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_nature_s_reclamation():
    """Nature's Reclamation: expects ['LIFE_CHANGE', 'OBJECT_DESTROYED'] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS["Nature's Reclamation"]
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name="Nature's Reclamation",
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = ['LIFE_CHANGE', 'OBJECT_DESTROYED']
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_summon_the_forest():
    """Summon the Forest: expects [] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS['Summon the Forest']
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name='Summon the Forest',
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = []
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_forest_sanctuary():
    """Forest Sanctuary: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Forest Sanctuary')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Forest Sanctuary')

def test_card_blessing_of_the_spirits():
    """Blessing of the Spirits: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Blessing of the Spirits')
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Blessing of the Spirits')

def test_card_nature_s_wrath():
    """Nature's Wrath: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, "Nature's Wrath")
    expected = []
    assert_emit_or_register(game, expected, "Nature's Wrath")

def test_card_spirited_transformation():
    """Spirited Transformation: expects ['COUNTER_ADDED'] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS['Spirited Transformation']
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name='Spirited Transformation',
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = ['COUNTER_ADDED']
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_forest_and_sky():
    """Forest and Sky: expects ['DRAW'] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS['Forest and Sky']
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name='Forest and Sky',
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = ['DRAW']
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_curse_breaker():
    """Curse Breaker: expects ['LIFE_CHANGE'] (spell with resolve)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS['Curse Breaker']
    try:
        events = card_def.resolve(None, game.state) or []
    except Exception as e:
        raise AssertionError(f"resolve raised: {type(e).__name__}: {e}")
    expected = ['LIFE_CHANGE']
    if expected:
        got_types = {e.type.name for e in events}
        if not any(et in got_types for et in expected):
            raise AssertionError(
                f"expected one of {expected} in returned events, got {sorted(got_types)}"
            )
    else:
        assert len(events) > 0, "resolve emitted no events"

def test_card_nature_s_vengeance():
    """Nature's Vengeance: expects ['OBJECT_DESTROYED', 'COUNTER_ADDED'] (spell with setup_interceptors)"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    card_def = STUDIO_GHIBLI_CARDS["Nature's Vengeance"]
    # Spells with setup_interceptors (alt-cast mechanics): put in graveyard
    # so the setup runs there. Many register on cast or in graveyard.
    obj = game.create_object(
        name="Nature's Vengeance",
        owner_id=p1.id,
        zone=ZoneType.HAND,
        characteristics=card_def.characteristics,
        card_def=None,
    )
    obj.card_def = card_def
    # Try graveyard zone first
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{p1.id}',
            'to_zone': f'graveyard_{p1.id}',
            'to_zone_type': ZoneType.GRAVEYARD,
        },
    ))
    expected = ['OBJECT_DESTROYED', 'COUNTER_ADDED']
    if expected:
        got_types = {e.type.name for e in game.state.event_log}
        if not any(et in got_types for et in expected):
            # Weaker assertion: at least the interceptor must register
            ids = [iid for iid in game.state.interceptors]
            assert ids, f"no interceptors registered and no expected events for {card_def.name!r}"
    else:
        ids = [iid for iid in game.state.interceptors]
        assert ids, f"no interceptors registered for {card_def.name!r}"

def test_card_ancient_forest():
    """Ancient Forest: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Ancient Forest')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Ancient Forest')

def test_card_toxic_jungle():
    """Toxic Jungle: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Toxic Jungle')
    expected = []
    assert_emit_or_register(game, expected, 'Toxic Jungle')

def test_card_laputa_floating_castle():
    """Laputa, Floating Castle: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Laputa, Floating Castle')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Laputa, Floating Castle')

def test_card_spirit_realm_gate():
    """Spirit Realm Gate: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Spirit Realm Gate')
    expected = []
    assert_emit_or_register(game, expected, 'Spirit Realm Gate')

def test_card_forest_shrine():
    """Forest Shrine: expects ['DRAW']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Forest Shrine')
    expected = ['DRAW']
    assert_emit_or_register(game, expected, 'Forest Shrine')

def test_card_cursed_swamp():
    """Cursed Swamp: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Cursed Swamp')
    expected = []
    assert_emit_or_register(game, expected, 'Cursed Swamp')

def test_card_ohmu_nest():
    """Ohmu Nest: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Ohmu Nest')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Ohmu Nest')

def test_card_shuna_emissary_of_the_forest():
    """Shuna, Emissary of the Forest: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Shuna, Emissary of the Forest')
    expected = []
    assert_emit_or_register(game, expected, 'Shuna, Emissary of the Forest')

def test_card_chihiro_river_returned():
    """Chihiro, River-Returned: expects ['CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Chihiro, River-Returned')
    expected = ['CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'Chihiro, River-Returned')

def test_card_the_bathhouse_pure_retreat():
    """The Bathhouse, Pure Retreat: expects ['DRAW', 'LIFE_CHANGE', 'CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'The Bathhouse, Pure Retreat')
    expected = ['DRAW', 'LIFE_CHANGE', 'CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'The Bathhouse, Pure Retreat')

def test_card_howl_wandering_heart_wizard():
    """Howl, Wandering Heart-Wizard: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Howl, Wandering Heart-Wizard')
    expected = []
    assert_emit_or_register(game, expected, 'Howl, Wandering Heart-Wizard')

def test_card_yubaba_bathhouse_greed():
    """Yubaba, Bathhouse Greed: expects ['DRAW', 'LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Yubaba, Bathhouse Greed')
    expected = ['DRAW', 'LIFE_CHANGE']
    assert_emit_or_register(game, expected, 'Yubaba, Bathhouse Greed')

def test_card_no_face_devouring_spirit():
    """No-Face, Devouring Spirit: expects []"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'No-Face, Devouring Spirit')
    expected = []
    assert_emit_or_register(game, expected, 'No-Face, Devouring Spirit')

def test_card_the_spirit_realm_summoning():
    """The Spirit-Realm Summoning: expects ['DRAW', 'CREATE_TOKEN']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'The Spirit-Realm Summoning')
    expected = ['DRAW', 'CREATE_TOKEN']
    assert_emit_or_register(game, expected, 'The Spirit-Realm Summoning')

def test_card_princess_mononoke_s_curse():
    """Princess Mononoke's Curse: expects ['LIFE_CHANGE']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, "Princess Mononoke's Curse")
    expected = ['LIFE_CHANGE']
    assert_emit_or_register(game, expected, "Princess Mononoke's Curse")

def test_card_kaonashi_s_banquet():
    """Kaonashi's Banquet: expects ['DRAW', 'CREATE_TOKEN', 'DISCARD', 'SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, "Kaonashi's Banquet")
    expected = ['DRAW', 'CREATE_TOKEN', 'DISCARD', 'SCRY']
    assert_emit_or_register(game, expected, "Kaonashi's Banquet")

def test_card_ashitaka_iron_cursed_prince():
    """Ashitaka, Iron-Cursed Prince: expects ['DRAW']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Ashitaka, Iron-Cursed Prince')
    expected = ['DRAW']
    assert_emit_or_register(game, expected, 'Ashitaka, Iron-Cursed Prince')

def test_card_the_cursed_forest_awakens():
    """The Cursed Forest Awakens: expects ['DRAW', 'CREATE_TOKEN', 'DISCARD', 'SCRY', 'COUNTER_ADDED']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'The Cursed Forest Awakens')
    expected = ['DRAW', 'CREATE_TOKEN', 'DISCARD', 'SCRY', 'COUNTER_ADDED']
    assert_emit_or_register(game, expected, 'The Cursed Forest Awakens')

def test_card_haku_river_lord_bound():
    """Haku, River-Lord Bound: expects ['DISCARD']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Haku, River-Lord Bound')
    expected = ['DISCARD']
    assert_emit_or_register(game, expected, 'Haku, River-Lord Bound')

def test_card_boh_pacified_giant():
    """Boh, Pacified Giant: expects ['CREATE_TOKEN', 'DISCARD']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Boh, Pacified Giant')
    expected = ['CREATE_TOKEN', 'DISCARD']
    assert_emit_or_register(game, expected, 'Boh, Pacified Giant')

def test_card_castle_in_the_sky_reawakened():
    """Castle in the Sky, Reawakened: expects ['SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'Castle in the Sky, Reawakened')
    expected = ['SCRY']
    assert_emit_or_register(game, expected, 'Castle in the Sky, Reawakened')

def test_card_the_forest_watches():
    """The Forest Watches: expects ['SCRY']"""
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    create_permanent_on_battlefield(game, p1, 'The Forest Watches')
    expected = ['SCRY']
    assert_emit_or_register(game, expected, 'The Forest Watches')


if __name__ == "__main__":
    import traceback
    tests = [(k, v) for k, v in sorted(globals().items()) if k.startswith("test_")]
    passed, failed, errored = [], [], []
    for name, fn in tests:
        try:
            fn()
            passed.append(name)
        except AssertionError as e:
            failed.append((name, str(e)))
        except Exception as e:
            errored.append((name, f"{type(e).__name__}: {e}"))

    print(f"\n=== Interceptor verification: custom/studio_ghibli ===")
    print(f"  passed:  {len(passed)}")
    print(f"  failed:  {len(failed)}")
    print(f"  errored: {len(errored)}")
    print(f"  skipped: {len(SKIPPED_CARDS)} (see SKIPPED_CARDS)")
    if failed:
        print("\n--- FAILURES (top 20) ---")
        for name, msg in failed[:20]:
            print(f"  {name}: {msg}")
    if errored:
        print("\n--- ERRORS (top 20) ---")
        for name, msg in errored[:20]:
            print(f"  {name}: {msg}")
    total = len(passed) + len(failed) + len(errored)
    if total:
        pct = 100 * len(passed) / total
        print(f"\npass rate: {pct:.1f}%")
    sys.exit(0 if not failed and not errored else 1)
