"""Auto-generated interceptor verification for Wilds of Eldraine (WOE).

Generated by /test-interceptors. Re-running the skill overwrites this file.
Do NOT hand-edit -- if a test is wrong, fix the generator's heuristics.

Strategy: each wired card is exercised by firing its registered trigger
(ETB, death, attack, damage, spell cast, upkeep, end step) and asserting
that at least one of the expected EventTypes (parsed from the card's
rules text) appears in the resulting event log.

This catches the canonical depths-style bug: an interceptor that fires
but emits zero events (effect_fn = return []) -- it would appear as
"trigger fired but no expected EventType was emitted".
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src.engine import Game, Event, EventType, ZoneType, CardType
from src.cards.wilds_of_eldraine import WILDS_OF_ELDRAINE_CARDS


# ---------------------------------------------------------------------------
# Cards that cannot be auto-tested (modal, saga, replacement, target-choice,
# or interceptors that only register in non-HAND zones).
# ---------------------------------------------------------------------------

SKIPPED_CARDS: dict[str, str] = {
    "A Tale for the Ages": "static effect: needs attached/matching permanent setup",
    "Agatha of the Vile Cauldron": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Agatha's Soul Cauldron": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Archon of the Wild Rose": "static effect: needs attached/matching permanent setup",
    "Ashiok's Reaper": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Ashiok, Wicked Manipulator": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Barrow Naughty": "static effect: needs attached/matching permanent setup",
    "Belligerent of the Ball": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Bespoke Battlegarb": "static effect: needs attached/matching permanent setup",
    "Bestial Bloodline": "static effect: needs attached/matching permanent setup",
    "Blossoming Tortoise": "static effect: needs attached/matching permanent setup",
    "Boundary Lands Ranger": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Chancellor of Tales": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Charming Scoundrel": "modal: choose-one with bullets",
    "Cooped Up": "PREVENT interceptor: requires attempted attack/block",
    "Dream Spoilers": "other interceptor (prio=['REACT'], no parseable expected event)",
    "Dutiful Griffin": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Edgewall Inn": "as-enters choice (modal)",
    "Elvish Archivist": "complex reactive trigger (prio=['REACT', 'REACT']); needs custom test",
    "Embereth Veteran": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Eriette of the Charmed Apple": "kind=end_step but no parseable expected EventType from text",
    "Evolving Wilds": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Food Fight": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Frostbridge Guard": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Gadwick's First Duel": "saga: lore-counter chapter triggers",
    "Gingerbrute": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Goddric, Cloaked Reveler": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Howling Galefang": "static effect: needs attached/matching permanent setup",
    "Hylda of the Icy Crown": "modal: choose-one with bullets",
    "Hylda's Crown of Winter": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Imodane, the Pyrohammer": "other interceptor (prio=['REACT'], no parseable expected event)",
    "Johann, Apprentice Sorcerer": "static effect: needs attached/matching permanent setup",
    "Knight of Doves": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Korvold and the Noble Thief": "saga: lore-counter chapter triggers",
    "Likeness Looter": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Living Lectern": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Lord Skitter's Butcher": "modal: choose-one with bullets",
    "Lord Skitter, Sewer King": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Mocking Sprite": "static effect: needs attached/matching permanent setup",
    "Neva, Stalked by Nightmares": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Obyra, Dreaming Duelist": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Old Flitterfang": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Pests of Honor": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Raging Battle Mouse": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Redtooth Vanguard": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Regal Bunnicorn": "static effect: needs attached/matching permanent setup",
    "Restless Vinestalk": "kind=attack but no parseable expected EventType from text",
    "Rimefur Reindeer": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Savior of the Sleeping": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Sentinel of Lost Lore": "modal: choose-one with bullets",
    "Skewer Slinger": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Sleep-Cursed Faerie": "kind=etb but no parseable expected EventType from text",
    "Slumbering Keepguard": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Specter of Mortality": "kind=etb but no parseable expected EventType from text",
    "Spellbook Vendor": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Storyteller Pixie": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Syr Ginger, the Meal Ender": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Talion's Messenger": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Talion, the Kindly Lord": "as-enters choice (modal)",
    "Tangled Colony": "kind=death but no parseable expected EventType from text",
    "Tanglespan Lookout": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Tattered Ratter": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Territorial Witchstalker": "complex reactive trigger (prio=['REACT']); needs custom test",
    "The Apprentice's Folly": "saga: lore-counter chapter triggers",
    "The Huntsman's Redemption": "saga: lore-counter chapter triggers",
    "The Irencrag": "complex reactive trigger (prio=['REACT']); needs custom test",
    "The Princess Takes Flight": "saga: lore-counter chapter triggers",
    "The Witch's Vanity": "saga: lore-counter chapter triggers",
    "Three Blind Mice": "saga: lore-counter chapter triggers",
    "Three Bowls of Porridge": "modal: choose-one with bullets",
    "Toadstool Admirer": "ward: requires target-chosen flow + opponent caster",
    "Totentanz, Swarm Piper": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Troyan, Gutsy Explorer": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Verdant Outrider": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Virtue of Courage": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Virtue of Knowledge": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Virtue of Strength": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
    "Warehouse Tabby": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Welcome to Sweettooth": "saga: lore-counter chapter triggers",
    "Wicked Visitor": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Wildwood Mentor": "complex reactive trigger (prio=['REACT']); needs custom test",
    "Yenna, Redtooth Regent": "setup_interceptors returned [] for HAND obj (graveyard-only or zone-conditional setup)",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _new_game_with_two_players():
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    return game, p1, p2


def _create_in_hand(game, player, name):
    """Create the card in the player's HAND without firing interceptor setup."""
    cdef = WILDS_OF_ELDRAINE_CARDS[name]
    obj = game.create_object(
        name=name,
        owner_id=player.id,
        zone=ZoneType.HAND,
        characteristics=cdef.characteristics,
        card_def=None,  # delay setup until ZONE_CHANGE -> battlefield
    )
    obj.card_def = cdef
    return obj


def _move_to_battlefield(game, obj, player):
    """Move from HAND to BATTLEFIELD via ZONE_CHANGE so interceptors set up + ETB fires."""
    game.emit(Event(
        type=EventType.ZONE_CHANGE,
        payload={
            'object_id': obj.id,
            'from_zone': f'hand_{player.id}',
            'to_zone': 'battlefield',
            'to_zone_type': ZoneType.BATTLEFIELD,
        }
    ))


def _make_dummy_target(game, player):
    """Create a generic 2/2 creature on the battlefield for use as a target."""
    from src.engine import make_creature, Color
    cdef = make_creature(
        name="Dummy Target",
        power=2, toughness=2,
        mana_cost="{1}{G}",
        colors={Color.GREEN},
        subtypes={"Beast"},
        text="",
    )
    obj = game.create_object(
        name="Dummy Target",
        owner_id=player.id,
        zone=ZoneType.BATTLEFIELD,
        characteristics=cdef.characteristics,
        card_def=cdef,
    )
    return obj


def _make_dummy_enchantment(game, player):
    """Create a generic enchantment on the battlefield for use as a target."""
    from src.engine import make_enchantment, Color
    cdef = make_enchantment(
        name="Dummy Enchantment",
        mana_cost="{1}{W}",
        colors={Color.WHITE},
        text="",
    )
    obj = game.create_object(
        name="Dummy Enchantment",
        owner_id=player.id,
        zone=ZoneType.BATTLEFIELD,
        characteristics=cdef.characteristics,
        card_def=cdef,
    )
    return obj


def _seed_board(game, p1, p2):
    """Seed both players with a dummy creature + enchantment, a creature in
    each graveyard, and lopsided lands (opp > controller) so conditional
    triggers ('if opponent controls more lands', 'each creature you control',
    'creature card in a graveyard') have something to act on.
    """
    from src.engine import make_creature, Color, CardDefinition, Characteristics
    _make_dummy_target(game, p1)
    _make_dummy_target(game, p2)
    _make_dummy_enchantment(game, p1)
    _make_dummy_enchantment(game, p2)

    # Make sure graveyards exist + drop a creature card in each
    for pid in (p1.id, p2.id):
        gy_key = f"graveyard_{pid}"
        if gy_key not in game.state.zones:
            from src.engine.types import Zone
            game.state.zones[gy_key] = Zone(id=gy_key, zone_type=ZoneType.GRAVEYARD)
        cdef = make_creature(
            name="Dummy Graveyard Beast",
            power=2, toughness=2,
            mana_cost="{1}{G}",
            colors={Color.GREEN},
            subtypes={"Beast"},
            text="",
        )
        game.create_object(
            name="Dummy Graveyard Beast",
            owner_id=pid,
            zone=ZoneType.GRAVEYARD,
            characteristics=cdef.characteristics,
            card_def=cdef,
        )

    # Make opp have more lands than controller so "if opponent controls more
    # lands" triggers fire.
    from src.cards.card_factories import make_land
    for _ in range(3):
        land = make_land(name="Dummy Land", text="")
        game.create_object(
            name="Dummy Land",
            owner_id=p2.id,
            zone=ZoneType.BATTLEFIELD,
            characteristics=land.characteristics,
            card_def=land,
        )


def _collect_event_types(game, since_idx: int) -> set:
    """Return the set of EventType values emitted at index `since_idx` and later."""
    log = getattr(game.state, 'event_log', None)
    if log is None:
        # Fallback: try other locations
        log = getattr(game, 'event_log', []) or []
    return {ev.type for ev in log[since_idx:]}


def _event_log_len(game) -> int:
    log = getattr(game.state, 'event_log', None)
    if log is None:
        log = getattr(game, 'event_log', []) or []
    return len(log)


# Family equivalences: many cards implement these effects as ZONE_CHANGE / aliases.
# When the parsed expected event is X, *also* accept any event in EQUIVALENT[X].
EQUIVALENT = {
    EventType.EXILE: {EventType.ZONE_CHANGE, EventType.EXILE_FROM_TOP, EventType.EXILE_TOP, EventType.EXILE_TOP_CARD},
    EventType.RETURN_TO_HAND: {EventType.ZONE_CHANGE, EventType.BOUNCE},
    EventType.RETURN_FROM_GRAVEYARD: {EventType.ZONE_CHANGE, EventType.RETURN_TO_HAND_FROM_GRAVEYARD},
    EventType.DESTROY: {EventType.OBJECT_DESTROYED, EventType.ZONE_CHANGE},
    EventType.SACRIFICE: {EventType.OBJECT_DESTROYED, EventType.ZONE_CHANGE},
    EventType.DRAW: set(),
    EventType.DISCARD: {EventType.ZONE_CHANGE},
    EventType.MILL: {EventType.ZONE_CHANGE},
    EventType.SCRY: set(),
    EventType.SURVEIL: set(),
    EventType.OBJECT_CREATED: {EventType.CREATE_TOKEN},
    EventType.LIFE_CHANGE: {EventType.LIFE_GAIN, EventType.LIFE_LOSS},
    EventType.PT_MODIFICATION: {EventType.TEMPORARY_EFFECT, EventType.PUMP, EventType.GRANT_PT_MODIFIER, EventType.PT_MODIFIER, EventType.PT_CHANGE, EventType.PT_MODIFY, EventType.TEMPORARY_BOOST},
    EventType.TEMPORARY_EFFECT: {EventType.GRANT_KEYWORD, EventType.KEYWORD_GRANT, EventType.GRANT_ABILITY, EventType.PT_MODIFICATION, EventType.PUMP},
    EventType.TAP_TARGET: {EventType.TAP},
    EventType.UNTAP_TARGET: {EventType.UNTAP},
    EventType.DAMAGE: set(),
    EventType.COUNTER: {EventType.COUNTER_SPELL, EventType.SPELL_COUNTERED},
    EventType.COUNTER_ADDED: set(),
    EventType.COPY_SPELL: {EventType.COPY_STACK_ITEM},
}


def _expand_expected(expected_set: set) -> set:
    out = set(expected_set)
    for e in list(expected_set):
        out |= EQUIVALENT.get(e, set())
    return out


def _assert_expected_event_emitted(game, since_idx: int, expected_set: set, card_name: str, trigger_kind: str):
    """Assert that AT LEAST ONE of the expected EventTypes (or an equivalent)
    appears in events emitted after `since_idx`. Empty expected_set means we
    only check that SOMETHING (beyond the bookkeeping events) was emitted.

    Bookkeeping events (TRIGGERED_ABILITY_PUT_ON_STACK, the priming
    ZONE_CHANGE itself, PHASE_START, ATTACK_DECLARED, CAST, DAMAGE we fed in)
    don't count as "the effect" -- the trigger has to actually do something
    beyond them.
    """
    emitted = _collect_event_types(game, since_idx)
    # Strip bookkeeping events when judging emptiness
    bookkeeping = {
        EventType.TRIGGERED_ABILITY_PUT_ON_STACK,
        EventType.PHASE_START,
        EventType.PHASE_END,
        EventType.PHASE_CHANGE,
        EventType.PRIORITY_PASS,
    }
    effective = emitted - bookkeeping
    if not effective:
        expected_names = sorted(e.name for e in expected_set)
        emitted_names = sorted(e.name for e in emitted)
        raise AssertionError(
            f"{card_name}: {trigger_kind} fired but produced ZERO effect events "
            f"(depths trap). Emitted only bookkeeping: {emitted_names}. "
            f"Expected one of: {expected_names}"
        )
    if not expected_set:
        return  # we have effect events; can't be more specific
    expanded = _expand_expected(expected_set)
    overlap = effective & expanded
    if not overlap:
        emitted_names = sorted(e.name for e in emitted)
        expected_names = sorted(e.name for e in expected_set)
        raise AssertionError(
            f"{card_name}: {trigger_kind} emitted {emitted_names} "
            f"but expected at least one of {expected_names} "
            f"(or equivalents like ZONE_CHANGE for exile/bounce)"
        )


def test_agatha_s_champion():
    """<name>: ETB trigger emits one of ['SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, "Agatha's Champion")
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.SACRIFICE}, "Agatha's Champion", "ETB")
def test_archive_dragon():
    """<name>: ETB trigger emits one of ['SCRY']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Archive Dragon')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.SCRY}, 'Archive Dragon', "ETB")
def test_ash_party_crasher():
    """<name>: attack trigger emits one of ['COUNTER_ADDED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Ash, Party Crasher')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.ATTACK_DECLARED,
        payload={'attacker_id': card.id, 'defender_id': p2.id, 'controller': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.COUNTER_ADDED}, 'Ash, Party Crasher', "attack")
def test_bitter_chill():
    """<name>: ETB trigger emits one of ['DRAW', 'SCRY']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Bitter Chill')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DRAW, EventType.SCRY}, 'Bitter Chill', "ETB")
def test_candy_trail():
    """<name>: ETB trigger emits one of ['DRAW', 'LIFE_CHANGE', 'SCRY', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Candy Trail')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DRAW, EventType.LIFE_CHANGE, EventType.SCRY, EventType.SACRIFICE}, 'Candy Trail', "ETB")
def test_charging_hooligan():
    """<name>: attack trigger emits one of ['PT_MODIFICATION', 'TEMPORARY_EFFECT']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Charging Hooligan')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.ATTACK_DECLARED,
        payload={'attacker_id': card.id, 'defender_id': p2.id, 'controller': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.PT_MODIFICATION, EventType.TEMPORARY_EFFECT}, 'Charging Hooligan', "attack")
def test_charmed_clothier():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'PT_MODIFICATION']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Charmed Clothier')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.PT_MODIFICATION}, 'Charmed Clothier', "ETB")
def test_crystal_grotto():
    """<name>: ETB trigger emits one of ['SCRY']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Crystal Grotto')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.SCRY}, 'Crystal Grotto', "ETB")
def test_cursed_courtier():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Cursed Courtier')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED}, 'Cursed Courtier', "ETB")
def test_diminisher_witch():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Diminisher Witch')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.SACRIFICE}, 'Diminisher Witch', "ETB")
def test_discerning_financier():
    """<name>: upkeep trigger emits one of ['DRAW', 'OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Discerning Financier')
    _move_to_battlefield(game, card, p1)
    # Ensure controller is active player for upkeep filter
    game.state.active_player = p1.id
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.PHASE_START,
        payload={'phase': 'upkeep', 'player': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.DRAW, EventType.OBJECT_CREATED, EventType.SACRIFICE}, 'Discerning Financier', "upkeep")
def test_edgewall_pack():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Edgewall Pack')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED}, 'Edgewall Pack', "ETB")
def test_eriette_s_tempting_apple():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'TEMPORARY_EFFECT', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, "Eriette's Tempting Apple")
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.TEMPORARY_EFFECT, EventType.SACRIFICE}, "Eriette's Tempting Apple", "ETB")
def test_experimental_confectioner():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Experimental Confectioner')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.SACRIFICE}, 'Experimental Confectioner', "ETB")
def test_extraordinary_journey():
    """<name>: ETB trigger emits one of ['DRAW', 'EXILE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Extraordinary Journey')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DRAW, EventType.EXILE}, 'Extraordinary Journey', "ETB")
def test_faerie_dreamthief():
    """<name>: ETB trigger emits one of ['DRAW', 'LIFE_CHANGE', 'SURVEIL']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Faerie Dreamthief')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DRAW, EventType.LIFE_CHANGE, EventType.SURVEIL}, 'Faerie Dreamthief', "ETB")
def test_faunsbane_troll():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'PT_MODIFICATION', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Faunsbane Troll')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.PT_MODIFICATION, EventType.SACRIFICE}, 'Faunsbane Troll', "ETB")
def test_food_coma():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'EXILE', 'OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Food Coma')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.EXILE, EventType.OBJECT_CREATED, EventType.SACRIFICE}, 'Food Coma', "ETB")
def test_glass_casket():
    """<name>: ETB trigger emits one of ['EXILE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Glass Casket')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.EXILE}, 'Glass Casket', "ETB")
def test_greta_sweettooth_scourge():
    """<name>: ETB trigger emits one of ['DRAW', 'LIFE_CHANGE', 'OBJECT_CREATED', 'COUNTER_ADDED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Greta, Sweettooth Scourge')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DRAW, EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.COUNTER_ADDED, EventType.SACRIFICE}, 'Greta, Sweettooth Scourge', "ETB")
def test_gruff_triplets():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Gruff Triplets')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED}, 'Gruff Triplets', "ETB")
def test_hamlet_glutton():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Hamlet Glutton')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.SACRIFICE}, 'Hamlet Glutton', "ETB")
def test_harried_spearguard():
    """<name>: death trigger emits one of ['OBJECT_CREATED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1,'Harried Spearguard')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    # Send the creature to the graveyard
    gy_zone = f"graveyard_{p1.id}"
    if gy_zone not in game.state.zones:
        from src.engine import Zone
        game.state.zones[gy_zone] = Zone(id=gy_zone, zone_type=ZoneType.GRAVEYARD)
    game.emit(Event(
        type=EventType.OBJECT_DESTROYED,
        payload={'object_id': card.id, 'reason': 'lethal damage'},
    ))
    # If still on battlefield, emit ZONE_CHANGE BF->GY
    obj = game.state.objects.get(card.id)
    if obj and obj.zone == ZoneType.BATTLEFIELD:
        game.emit(Event(
            type=EventType.ZONE_CHANGE,
            payload={
                'object_id': card.id,
                'from_zone': 'battlefield',
                'to_zone': gy_zone,
                'from_zone_type': ZoneType.BATTLEFIELD,
                'to_zone_type': ZoneType.GRAVEYARD,
            }
        ))
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED}, 'Harried Spearguard', "death")
def test_high_fae_negotiator():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'High Fae Negotiator')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.SACRIFICE}, 'High Fae Negotiator', "ETB")
def test_hopeful_vigil():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'SCRY', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Hopeful Vigil')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.SCRY, EventType.SACRIFICE}, 'Hopeful Vigil', "ETB")
def test_hopeless_nightmare():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'SCRY', 'DISCARD', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Hopeless Nightmare')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.SCRY, EventType.DISCARD, EventType.SACRIFICE}, 'Hopeless Nightmare', "ETB")
def test_icewrought_sentry():
    """<name>: attack trigger emits one of ['TAP_TARGET', 'PT_MODIFICATION']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Icewrought Sentry')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.ATTACK_DECLARED,
        payload={'attacker_id': card.id, 'defender_id': p2.id, 'controller': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.TAP_TARGET, EventType.PT_MODIFICATION}, 'Icewrought Sentry', "attack")
def test_ingenious_prodigy():
    """<name>: upkeep trigger emits one of ['DRAW']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Ingenious Prodigy')
    _move_to_battlefield(game, card, p1)
    # Ensure controller is active player for upkeep filter
    game.state.active_player = p1.id
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.PHASE_START,
        payload={'phase': 'upkeep', 'player': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.DRAW}, 'Ingenious Prodigy', "upkeep")
def test_lady_of_laughter():
    """<name>: end_step trigger emits one of ['DRAW']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Lady of Laughter')
    _move_to_battlefield(game, card, p1)
    game.state.active_player = p1.id
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.PHASE_START,
        payload={'phase': 'end_step', 'player': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.DRAW}, 'Lady of Laughter', "end_step")
def test_lord_skitter_s_blessing():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'OBJECT_CREATED', 'PT_MODIFICATION']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, "Lord Skitter's Blessing")
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.PT_MODIFICATION}, "Lord Skitter's Blessing", "ETB")
def test_malevolent_witchkite():
    """<name>: ETB trigger emits one of ['SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Malevolent Witchkite')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.SACRIFICE}, 'Malevolent Witchkite', "ETB")
def test_merfolk_coralsmith():
    """<name>: death trigger emits one of ['SCRY']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1,'Merfolk Coralsmith')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    # Send the creature to the graveyard
    gy_zone = f"graveyard_{p1.id}"
    if gy_zone not in game.state.zones:
        from src.engine import Zone
        game.state.zones[gy_zone] = Zone(id=gy_zone, zone_type=ZoneType.GRAVEYARD)
    game.emit(Event(
        type=EventType.OBJECT_DESTROYED,
        payload={'object_id': card.id, 'reason': 'lethal damage'},
    ))
    # If still on battlefield, emit ZONE_CHANGE BF->GY
    obj = game.state.objects.get(card.id)
    if obj and obj.zone == ZoneType.BATTLEFIELD:
        game.emit(Event(
            type=EventType.ZONE_CHANGE,
            payload={
                'object_id': card.id,
                'from_zone': 'battlefield',
                'to_zone': gy_zone,
                'from_zone_type': ZoneType.BATTLEFIELD,
                'to_zone_type': ZoneType.GRAVEYARD,
            }
        ))
    _assert_expected_event_emitted(game, before, {EventType.SCRY}, 'Merfolk Coralsmith', "death")
def test_merry_bards():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'COUNTER_ADDED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Merry Bards')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.COUNTER_ADDED}, 'Merry Bards', "ETB")
def test_mintstrosity():
    """<name>: death trigger emits one of ['LIFE_CHANGE', 'OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1,'Mintstrosity')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    # Send the creature to the graveyard
    gy_zone = f"graveyard_{p1.id}"
    if gy_zone not in game.state.zones:
        from src.engine import Zone
        game.state.zones[gy_zone] = Zone(id=gy_zone, zone_type=ZoneType.GRAVEYARD)
    game.emit(Event(
        type=EventType.OBJECT_DESTROYED,
        payload={'object_id': card.id, 'reason': 'lethal damage'},
    ))
    # If still on battlefield, emit ZONE_CHANGE BF->GY
    obj = game.state.objects.get(card.id)
    if obj and obj.zone == ZoneType.BATTLEFIELD:
        game.emit(Event(
            type=EventType.ZONE_CHANGE,
            payload={
                'object_id': card.id,
                'from_zone': 'battlefield',
                'to_zone': gy_zone,
                'from_zone_type': ZoneType.BATTLEFIELD,
                'to_zone_type': ZoneType.GRAVEYARD,
            }
        ))
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.SACRIFICE}, 'Mintstrosity', "death")
def test_moonshaker_cavalry():
    """<name>: ETB trigger emits one of ['TEMPORARY_EFFECT']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Moonshaker Cavalry')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.TEMPORARY_EFFECT}, 'Moonshaker Cavalry', "ETB")
def test_night_of_the_sweets_revenge():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, "Night of the Sweets' Revenge")
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.SACRIFICE}, "Night of the Sweets' Revenge", "ETB")
def test_ogre_chitterlord():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'PT_MODIFICATION']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Ogre Chitterlord')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.PT_MODIFICATION}, 'Ogre Chitterlord', "ETB")
def test_prophetic_prism():
    """<name>: ETB trigger emits one of ['DRAW']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Prophetic Prism')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DRAW}, 'Prophetic Prism', "ETB")
def test_protective_parents():
    """<name>: death trigger emits one of ['OBJECT_CREATED', 'COUNTER_ADDED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1,'Protective Parents')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    # Send the creature to the graveyard
    gy_zone = f"graveyard_{p1.id}"
    if gy_zone not in game.state.zones:
        from src.engine import Zone
        game.state.zones[gy_zone] = Zone(id=gy_zone, zone_type=ZoneType.GRAVEYARD)
    game.emit(Event(
        type=EventType.OBJECT_DESTROYED,
        payload={'object_id': card.id, 'reason': 'lethal damage'},
    ))
    # If still on battlefield, emit ZONE_CHANGE BF->GY
    obj = game.state.objects.get(card.id)
    if obj and obj.zone == ZoneType.BATTLEFIELD:
        game.emit(Event(
            type=EventType.ZONE_CHANGE,
            payload={
                'object_id': card.id,
                'from_zone': 'battlefield',
                'to_zone': gy_zone,
                'from_zone_type': ZoneType.BATTLEFIELD,
                'to_zone_type': ZoneType.GRAVEYARD,
            }
        ))
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.COUNTER_ADDED}, 'Protective Parents', "death")
def test_provisions_merchant():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'OBJECT_CREATED', 'PT_MODIFICATION', 'TEMPORARY_EFFECT', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Provisions Merchant')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.PT_MODIFICATION, EventType.TEMPORARY_EFFECT, EventType.SACRIFICE}, 'Provisions Merchant', "ETB")
def test_realm_scorcher_hellkite():
    """<name>: ETB trigger emits one of ['DAMAGE', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Realm-Scorcher Hellkite')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DAMAGE, EventType.SACRIFICE}, 'Realm-Scorcher Hellkite', "ETB")
def test_redcap_gutter_dweller():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'COUNTER_ADDED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Redcap Gutter-Dweller')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.COUNTER_ADDED, EventType.SACRIFICE}, 'Redcap Gutter-Dweller', "ETB")
def test_redcap_thief():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Redcap Thief')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.SACRIFICE}, 'Redcap Thief', "ETB")
def test_redtooth_genealogist():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'PT_MODIFICATION']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Redtooth Genealogist')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.PT_MODIFICATION}, 'Redtooth Genealogist', "ETB")
def test_restless_bivouac():
    """<name>: attack trigger emits one of ['COUNTER_ADDED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Restless Bivouac')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.ATTACK_DECLARED,
        payload={'attacker_id': card.id, 'defender_id': p2.id, 'controller': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.COUNTER_ADDED}, 'Restless Bivouac', "attack")
def test_restless_cottage():
    """<name>: attack trigger emits one of ['EXILE', 'OBJECT_CREATED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Restless Cottage')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.ATTACK_DECLARED,
        payload={'attacker_id': card.id, 'defender_id': p2.id, 'controller': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.EXILE, EventType.OBJECT_CREATED}, 'Restless Cottage', "attack")
def test_restless_fortress():
    """<name>: attack trigger emits one of ['LIFE_CHANGE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Restless Fortress')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.ATTACK_DECLARED,
        payload={'attacker_id': card.id, 'defender_id': p2.id, 'controller': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE}, 'Restless Fortress', "attack")
def test_restless_spire():
    """<name>: attack trigger emits one of ['SCRY']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Restless Spire')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.ATTACK_DECLARED,
        payload={'attacker_id': card.id, 'defender_id': p2.id, 'controller': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.SCRY}, 'Restless Spire', "attack")
def test_rotisserie_elemental():
    """<name>: damage trigger emits one of ['SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Rotisserie Elemental')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.DAMAGE,
        payload={'source': card.id, 'target': p2.id, 'amount': 2, 'is_combat': True},
    ))
    _assert_expected_event_emitted(game, before, {EventType.SACRIFICE}, 'Rotisserie Elemental', "damage")
def test_ruby_daring_tracker():
    """<name>: attack trigger emits one of ['PT_MODIFICATION']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Ruby, Daring Tracker')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.ATTACK_DECLARED,
        payload={'attacker_id': card.id, 'defender_id': p2.id, 'controller': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.PT_MODIFICATION}, 'Ruby, Daring Tracker', "attack")
def test_scream_puff():
    """<name>: damage trigger emits one of ['LIFE_CHANGE', 'OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Scream Puff')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.DAMAGE,
        payload={'source': card.id, 'target': p2.id, 'amount': 2, 'is_combat': True},
    ))
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.SACRIFICE}, 'Scream Puff', "damage")
def test_sharae_of_numbing_depths():
    """<name>: ETB trigger emits one of ['DRAW', 'TAP_TARGET']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Sharae of Numbing Depths')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DRAW, EventType.TAP_TARGET}, 'Sharae of Numbing Depths', "ETB")
def test_skybeast_tracker():
    """<name>: spell_cast trigger emits one of ['LIFE_CHANGE', 'OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Skybeast Tracker')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.CAST,
        payload={'spell_id': 'fake_spell_id', 'caster': p1.id, 'controller': p1.id,
                 'mana_value': 5, 'colors': set(), 'types': {CardType.INSTANT}},
    ))
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.SACRIFICE}, 'Skybeast Tracker', "spell_cast")
def test_snaremaster_sprite():
    """<name>: ETB trigger emits one of ['TAP_TARGET']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Snaremaster Sprite')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.TAP_TARGET}, 'Snaremaster Sprite', "ETB")
def test_solitary_sanctuary():
    """<name>: ETB trigger emits one of ['COUNTER_ADDED', 'TAP_TARGET']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Solitary Sanctuary')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.COUNTER_ADDED, EventType.TAP_TARGET}, 'Solitary Sanctuary', "ETB")
def test_soul_guide_lantern():
    """<name>: ETB trigger emits one of ['DRAW', 'EXILE', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Soul-Guide Lantern')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DRAW, EventType.EXILE, EventType.SACRIFICE}, 'Soul-Guide Lantern', "ETB")
def test_spiteful_hexmage():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Spiteful Hexmage')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED}, 'Spiteful Hexmage', "ETB")
def test_splashy_spellcaster():
    """<name>: spell_cast trigger emits one of ['OBJECT_CREATED', 'SCRY', 'PT_MODIFICATION']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Splashy Spellcaster')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.CAST,
        payload={'spell_id': 'fake_spell_id', 'caster': p1.id, 'controller': p1.id,
                 'mana_value': 5, 'colors': set(), 'types': {CardType.INSTANT}},
    ))
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.SCRY, EventType.PT_MODIFICATION}, 'Splashy Spellcaster', "spell_cast")
def test_stingblade_assassin():
    """<name>: ETB trigger emits one of ['DESTROY']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Stingblade Assassin')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DESTROY}, 'Stingblade Assassin', "ETB")
def test_stockpiling_celebrant():
    """<name>: ETB trigger emits one of ['SCRY']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Stockpiling Celebrant')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.SCRY}, 'Stockpiling Celebrant', "ETB")
def test_stormkeld_prowler():
    """<name>: spell_cast trigger emits one of ['COUNTER_ADDED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Stormkeld Prowler')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.CAST,
        payload={'spell_id': 'fake_spell_id', 'caster': p1.id, 'controller': p1.id,
                 'mana_value': 5, 'colors': set(), 'types': {CardType.INSTANT}},
    ))
    _assert_expected_event_emitted(game, before, {EventType.COUNTER_ADDED}, 'Stormkeld Prowler', "spell_cast")
def test_sweettooth_witch():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Sweettooth Witch')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.SACRIFICE}, 'Sweettooth Witch', "ETB")
def test_syr_armont_the_redeemer():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'PT_MODIFICATION']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Syr Armont, the Redeemer')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.PT_MODIFICATION}, 'Syr Armont, the Redeemer', "ETB")
def test_tenacious_tomeseeker():
    """<name>: ETB trigger emits one of ['RETURN_TO_HAND', 'RETURN_FROM_GRAVEYARD', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Tenacious Tomeseeker')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.RETURN_TO_HAND, EventType.RETURN_FROM_GRAVEYARD, EventType.SACRIFICE}, 'Tenacious Tomeseeker', "ETB")
def test_the_goose_mother():
    """<name>: attack trigger emits one of ['DRAW', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'The Goose Mother')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.ATTACK_DECLARED,
        payload={'attacker_id': card.id, 'defender_id': p2.id, 'controller': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.DRAW, EventType.SACRIFICE}, 'The Goose Mother', "attack")
def test_tough_cookie():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'OBJECT_CREATED', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Tough Cookie')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.SACRIFICE}, 'Tough Cookie', "ETB")
def test_troublemaker_ouphe():
    """<name>: ETB trigger emits one of ['EXILE', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Troublemaker Ouphe')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.EXILE, EventType.SACRIFICE}, 'Troublemaker Ouphe', "ETB")
def test_twisted_sewer_witch():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'OBJECT_CREATED', 'PT_MODIFICATION']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Twisted Sewer-Witch')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.OBJECT_CREATED, EventType.PT_MODIFICATION}, 'Twisted Sewer-Witch', "ETB")
def test_unassuming_sage():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'SCRY', 'PT_MODIFICATION']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Unassuming Sage')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.SCRY, EventType.PT_MODIFICATION}, 'Unassuming Sage', "ETB")
def test_unruly_catapult():
    """<name>: spell_cast trigger emits one of ['DAMAGE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Unruly Catapult')
    _move_to_battlefield(game, card, p1)
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.CAST,
        payload={'spell_id': 'fake_spell_id', 'caster': p1.id, 'controller': p1.id,
                 'mana_value': 5, 'colors': set(), 'types': {CardType.INSTANT}},
    ))
    _assert_expected_event_emitted(game, before, {EventType.DAMAGE}, 'Unruly Catapult', "spell_cast")
def test_up_the_beanstalk():
    """<name>: ETB trigger emits one of ['DRAW']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Up the Beanstalk')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.DRAW}, 'Up the Beanstalk', "ETB")
def test_virtue_of_loyalty():
    """<name>: end_step trigger emits one of ['OBJECT_CREATED', 'COUNTER_ADDED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Virtue of Loyalty')
    _move_to_battlefield(game, card, p1)
    game.state.active_player = p1.id
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.PHASE_START,
        payload={'phase': 'end_step', 'player': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.COUNTER_ADDED}, 'Virtue of Loyalty', "end_step")
def test_virtue_of_persistence():
    """<name>: upkeep trigger emits one of ['LIFE_CHANGE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Virtue of Persistence')
    _move_to_battlefield(game, card, p1)
    # Ensure controller is active player for upkeep filter
    game.state.active_player = p1.id
    before = _event_log_len(game)
    game.emit(Event(
        type=EventType.PHASE_START,
        payload={'phase': 'upkeep', 'player': p1.id},
    ))
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE}, 'Virtue of Persistence', "upkeep")
def test_voracious_vermin():
    """<name>: ETB trigger emits one of ['OBJECT_CREATED', 'COUNTER_ADDED']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Voracious Vermin')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.OBJECT_CREATED, EventType.COUNTER_ADDED}, 'Voracious Vermin', "ETB")
def test_werefox_bodyguard():
    """<name>: ETB trigger emits one of ['LIFE_CHANGE', 'EXILE', 'SACRIFICE']."""
    game, p1, p2 = _new_game_with_two_players()
    _seed_board(game, p1, p2)
    card = _create_in_hand(game, p1, 'Werefox Bodyguard')
    before = _event_log_len(game)
    _move_to_battlefield(game, card, p1)
    _assert_expected_event_emitted(game, before, {EventType.LIFE_CHANGE, EventType.EXILE, EventType.SACRIFICE}, 'Werefox Bodyguard', "ETB")


# ---------------------------------------------------------------------------
# Runner
# ---------------------------------------------------------------------------


if __name__ == "__main__":
    import traceback
    tests = sorted([(k, v) for k, v in globals().items() if k.startswith("test_")])
    passed, failed, errors = [], [], []
    for name, fn in tests:
        try:
            fn()
            passed.append(name)
        except AssertionError as e:
            failed.append((name, str(e)))
        except Exception as e:
            errors.append((name, f"{type(e).__name__}: {e}"))

    total = len(tests)
    print()
    print("=" * 70)
    print(f"WOE interceptor verification")
    print("=" * 70)
    print(f"  tests:   {total}")
    print(f"  passed:  {len(passed)}")
    print(f"  failed:  {len(failed)}")
    print(f"  errors:  {len(errors)}")
    print(f"  skipped: {len(SKIPPED_CARDS)} (see SKIPPED_CARDS)")

    if failed:
        print()
        print("--- FAILURES (first 20) ---")
        for n, msg in failed[:20]:
            print(f"  {n}: {msg}")
    if errors:
        print()
        print("--- ERRORS (first 20) ---")
        for n, msg in errors[:20]:
            print(f"  {n}: {msg}")

    pass_rate = (100.0 * len(passed) / total) if total else 0.0
    print()
    print(f"  pass rate: {pass_rate:.1f}%")
    sys.exit(0 if not failed and not errors else 1)
