"""Interceptor verification for Princess Catholicon (FINC custom set).

Auto-generated by the slice-16 recovery pass (see
docs/audits/princess_catholicon_slice16_detection.md). One test per wired card:
fire the card's trigger (per its rules text) and assert the effect events its
setup/resolve emits actually fire. Static lord/keyword/equipment cards get a
load + interceptor-presence check. Catches "interceptor wired but effect_fn
returns []" regressions and slice-N stub re-contamination.

Run:  HYPERDRAFT_STRICT=1 python tests/test_princess_catholicon_interceptors.py
"""

import sys
sys.path.insert(0, __import__("pathlib").Path(__file__).resolve().parents[1].as_posix())

from src.engine import Game, Event, EventType, ZoneType
from src.cards.custom.princess_catholicon import FINAL_FANTASY_CUSTOM_CARDS


SKIPPED_CARDS = {
    'Cecil Harvey, Paladin of Mysidia': 'conditional Limit-Break/threshold trigger — needs specific life/board state',
    'Celes Chere, Runic Knight': 'runic — fires on opponent instant/sorcery cast; needs opp-cast setup',
    'Chocobo': 'no-op setup (return []) — evasion/keyword handled elsewhere',
    'Cid Pollendina, Adamant Smith': 'modal/target-choice/search — needs human selection',
    'Monk': "conditional 'attacks alone' (COMBAT_DECLARED) — needs solo-attack setup",
    'Sephiroth, One-Winged Angel': 'conditional Limit-Break/threshold trigger — needs specific life/board state',
    'Tidus, Star Player': 'no-op setup (return []) — evasion/keyword handled elsewhere',
    "Yuna's Sending Ritual": 'modal/target-choice/search — needs human selection',
}


def _put_on_battlefield(game, player, card_name):
    card_def = FINAL_FANTASY_CUSTOM_CARDS[card_name]
    obj = game.create_object(name=card_name, owner_id=player.id, zone=ZoneType.HAND,
                             characteristics=card_def.characteristics, card_def=None)
    obj.card_def = card_def
    game.emit(Event(type=EventType.ZONE_CHANGE, payload={
        'object_id': obj.id, 'from_zone': f'hand_{player.id}',
        'to_zone': 'battlefield', 'to_zone_type': ZoneType.BATTLEFIELD}))
    return obj


def _new_game():
    game = Game()
    p1 = game.add_player("Alice")
    p2 = game.add_player("Bob")
    for _ in range(6):
        game.create_object(name="Chocobo", owner_id=p1.id, zone=ZoneType.LIBRARY,
                           characteristics=FINAL_FANTASY_CUSTOM_CARDS["Chocobo"].characteristics, card_def=None)
        game.create_object(name="Chocobo", owner_id=p2.id, zone=ZoneType.LIBRARY,
                           characteristics=FINAL_FANTASY_CUSTOM_CARDS["Chocobo"].characteristics, card_def=None)
    # opponent board + hand so opp-facing effects have legal targets
    for _ in range(2):
        game.create_object(name="Goblin", owner_id=p2.id, zone=ZoneType.BATTLEFIELD,
                           characteristics=FINAL_FANTASY_CUSTOM_CARDS["Goblin"].characteristics, card_def=None)
        game.create_object(name="Chocobo", owner_id=p2.id, zone=ZoneType.HAND,
                           characteristics=FINAL_FANTASY_CUSTOM_CARDS["Chocobo"].characteristics, card_def=None)
    # a friendly creature for self-buff / sacrifice fodder
    game.create_object(name="Chocobo", owner_id=p1.id, zone=ZoneType.BATTLEFIELD,
                       characteristics=FINAL_FANTASY_CUSTOM_CARDS["Chocobo"].characteristics, card_def=None)
    return game, p1, p2


def _settle(game):
    """Resolve any stacked triggered abilities so deferred effects emit."""
    try:
        game.resolve_stack()
    except Exception:
        pass


def _types_after(game, before):
    return {e.type.name for e in game.state.event_log[before:]}


def _kill(game, obj, owner):
    game.emit(Event(type=EventType.ZONE_CHANGE, payload={
        'object_id': obj.id, 'from_zone': 'battlefield', 'from_zone_type': ZoneType.BATTLEFIELD,
        'to_zone': f'graveyard_{owner.id}', 'to_zone_type': ZoneType.GRAVEYARD}, source=obj.id))


def _fire_etb(game, p1, p2, card):
    before = len(game.state.event_log)
    _put_on_battlefield(game, p1, card)
    _settle(game)
    return _types_after(game, before)


def _fire_attack(game, p1, p2, card):
    obj = _put_on_battlefield(game, p1, card)
    before = len(game.state.event_log)
    game.emit(Event(type=EventType.ATTACK_DECLARED, payload={
        'attacker_id': obj.id, 'attacker': obj.id, 'controller': p1.id}, source=obj.id))
    _settle(game)
    return _types_after(game, before)


def _fire_death_self(game, p1, p2, card):
    obj = _put_on_battlefield(game, p1, card)
    before = len(game.state.event_log)
    _kill(game, obj, p1)
    _settle(game)
    return _types_after(game, before)


def _fire_death_any(game, p1, p2, card):
    _put_on_battlefield(game, p1, card)
    # kill a separate opponent creature so the watcher is still on the battlefield
    victim = game.create_object(name="Goblin", owner_id=p2.id, zone=ZoneType.BATTLEFIELD,
                                characteristics=FINAL_FANTASY_CUSTOM_CARDS["Goblin"].characteristics, card_def=None)
    before = len(game.state.event_log)
    _kill(game, victim, p2)
    _settle(game)
    return _types_after(game, before)


def _fire_damage(game, p1, p2, card):
    obj = _put_on_battlefield(game, p1, card)
    before = len(game.state.event_log)
    game.emit(Event(type=EventType.DAMAGE, payload={
        'source': obj.id, 'target': p2.id, 'amount': obj.characteristics.power or 1,
        'is_combat': True}, source=obj.id))
    _settle(game)
    return _types_after(game, before)


def _fire_upkeep(game, p1, p2, card):
    _put_on_battlefield(game, p1, card)
    game.state.active_player = p1.id  # upkeep trigger filters on state.active_player
    before = len(game.state.event_log)
    game.emit(Event(type=EventType.PHASE_START, payload={
        'phase': 'upkeep', 'player': p1.id, 'active_player': p1.id}, source=None))
    _settle(game)
    return _types_after(game, before)


def _fire_end_step(game, p1, p2, card):
    _put_on_battlefield(game, p1, card)
    game.state.active_player = p1.id  # end-step trigger filters on state.active_player
    before = len(game.state.event_log)
    game.emit(Event(type=EventType.PHASE_START, payload={
        'phase': 'end_step', 'player': p1.id, 'active_player': p1.id}, source=None))
    _settle(game)
    return _types_after(game, before)


def _fire_spell_cast(game, p1, p2, card):
    obj = _put_on_battlefield(game, p1, card)
    before = len(game.state.event_log)
    game.emit(Event(type=EventType.CAST, payload={
        'caster': p1.id, 'controller': p1.id, 'spell_types': ['instant'],
        'types': ['instant']}, source=None))
    _settle(game)
    return _types_after(game, before)


def _fire_life(game, p1, p2, card):
    _put_on_battlefield(game, p1, card)
    before = len(game.state.event_log)
    game.emit(Event(type=EventType.LIFE_CHANGE, payload={'player': p1.id, 'amount': -2}, source=None))
    _settle(game)
    return _types_after(game, before)


def _fire_resolve(game, p1, p2, card):
    cd = FINAL_FANTASY_CUSTOM_CARDS[card]
    events = cd.resolve([], game.state) or []
    return {e.type.name for e in events}


_FIRE = {
    'etb': _fire_etb, 'attack': _fire_attack, 'death_self': _fire_death_self,
    'death_any': _fire_death_any, 'damage': _fire_damage, 'upkeep': _fire_upkeep,
    'end_step': _fire_end_step, 'spell_cast': _fire_spell_cast, 'life': _fire_life,
    'resolve': _fire_resolve,
}


def test_aerith_gainsborough():
    """Aerith Gainsborough, Flower Girl: etb -> emits one of ['LIFE_CHANGE']"""
    name = 'Aerith Gainsborough, Flower Girl'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'LIFE_CHANGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_aerith_great_gospel():
    """Aerith, Great Gospel: static — loads and registers >=1 interceptor."""
    name = 'Aerith, Great Gospel'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_terra_branford():
    """Terra Branford, Half-Esper: static — loads and registers >=1 interceptor."""
    name = 'Terra Branford, Half-Esper'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_yuna_summoner():
    """Yuna, High Summoner: attack -> emits one of ['CREATE_TOKEN', 'OBJECT_CREATED']"""
    name = 'Yuna, High Summoner'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'CREATE_TOKEN', 'OBJECT_CREATED'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_white_mage():
    """White Mage: etb -> emits one of ['LIFE_CHANGE']"""
    name = 'White Mage'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'LIFE_CHANGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_paladin():
    """Paladin of Light: static — loads and registers >=1 interceptor."""
    name = 'Paladin of Light'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_holy_knight():
    """Holy Knight: static — loads and registers >=1 interceptor."""
    name = 'Holy Knight'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_temple_knight():
    """Temple Knight: static — loads and registers >=1 interceptor."""
    name = 'Temple Knight'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_shiva():
    """Shiva, Diamond Dust: etb -> emits one of ['TAP']"""
    name = 'Shiva, Diamond Dust'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'TAP'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_leviathan():
    """Leviathan, Tidal Wave: etb -> emits one of ['ZONE_CHANGE']"""
    name = 'Leviathan, Tidal Wave'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'ZONE_CHANGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_ramuh():
    """Ramuh, Judgment Bolt: etb -> emits one of ['DRAW']"""
    name = 'Ramuh, Judgment Bolt'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'DRAW'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_rikku():
    """Rikku, Al Bhed Thief: etb -> emits one of ['CREATE_TOKEN', 'OBJECT_CREATED']"""
    name = 'Rikku, Al Bhed Thief'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'CREATE_TOKEN', 'OBJECT_CREATED'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_time_mage():
    """Time Mage: upkeep -> emits one of ['SCRY']"""
    name = 'Time Mage'
    game, p1, p2 = _new_game()
    emitted = _FIRE['upkeep'](game, p1, p2, name)
    expected = {'SCRY'}
    assert emitted & expected, f"{name}: upkeep fired but expected one of {expected}, got {emitted}"


def test_blue_mage():
    """Blue Mage: death_any -> emits one of ['DRAW']"""
    name = 'Blue Mage'
    game, p1, p2 = _new_game()
    emitted = _FIRE['death_any'](game, p1, p2, name)
    expected = {'DRAW'}
    assert emitted & expected, f"{name}: death_any fired but expected one of {expected}, got {emitted}"


def test_sephiroth_masamune():
    """Sephiroth, Masamune's Edge: damage -> emits one of ['TARGET_REQUIRED']"""
    name = "Sephiroth, Masamune's Edge"
    game, p1, p2 = _new_game()
    emitted = _FIRE['damage'](game, p1, p2, name)
    expected = {'TARGET_REQUIRED'}
    assert emitted & expected, f"{name}: damage fired but expected one of {expected}, got {emitted}"


def test_vincent_valentine():
    """Vincent Valentine, Chaos Host: death_self -> emits one of ['CREATE_TOKEN', 'OBJECT_CREATED']"""
    name = 'Vincent Valentine, Chaos Host'
    game, p1, p2 = _new_game()
    emitted = _FIRE['death_self'](game, p1, p2, name)
    expected = {'CREATE_TOKEN', 'OBJECT_CREATED'}
    assert emitted & expected, f"{name}: death_self fired but expected one of {expected}, got {emitted}"


def test_kefka():
    """Kefka, Mad God: attack -> emits one of ['SACRIFICE']"""
    name = 'Kefka, Mad God'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'SACRIFICE'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_shadow_ff6():
    """Shadow, Ninja Assassin: damage -> emits one of ['DISCARD']"""
    name = 'Shadow, Ninja Assassin'
    game, p1, p2 = _new_game()
    emitted = _FIRE['damage'](game, p1, p2, name)
    expected = {'DISCARD'}
    assert emitted & expected, f"{name}: damage fired but expected one of {expected}, got {emitted}"


def test_odin():
    """Odin, Zantetsuken: etb -> emits one of ['DESTROY', 'OBJECT_DESTROYED']"""
    name = 'Odin, Zantetsuken'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'OBJECT_DESTROYED', 'DESTROY'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_anima():
    """Anima, Pain Incarnate: etb -> emits one of ['LIFE_CHANGE']"""
    name = 'Anima, Pain Incarnate'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'LIFE_CHANGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_dark_knight():
    """Dark Knight: static — loads and registers >=1 interceptor."""
    name = 'Dark Knight'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_reaper():
    """Reaper: damage -> emits one of ['LIFE_CHANGE']"""
    name = 'Reaper'
    game, p1, p2 = _new_game()
    emitted = _FIRE['damage'](game, p1, p2, name)
    expected = {'LIFE_CHANGE'}
    assert emitted & expected, f"{name}: damage fired but expected one of {expected}, got {emitted}"


def test_cloud_strife():
    """Cloud Strife, Ex-SOLDIER: static — loads and registers >=1 interceptor."""
    name = 'Cloud Strife, Ex-SOLDIER'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_tifa_lockhart():
    """Tifa Lockhart, Seventh Heaven: static — loads and registers >=1 interceptor."""
    name = 'Tifa Lockhart, Seventh Heaven'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_barret_wallace():
    """Barret Wallace, AVALANCHE Leader: static — loads and registers >=1 interceptor."""
    name = 'Barret Wallace, AVALANCHE Leader'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_red_xiii():
    """Red XIII, Nanaki: static — loads and registers >=1 interceptor."""
    name = 'Red XIII, Nanaki'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_locke_cole():
    """Locke Cole, Treasure Hunter: damage -> emits one of ['ZONE_CHANGE']"""
    name = 'Locke Cole, Treasure Hunter'
    game, p1, p2 = _new_game()
    emitted = _FIRE['damage'](game, p1, p2, name)
    expected = {'ZONE_CHANGE'}
    assert emitted & expected, f"{name}: damage fired but expected one of {expected}, got {emitted}"


def test_sabin():
    """Sabin, Blitzing Monk: attack -> emits one of ['DAMAGE']"""
    name = 'Sabin, Blitzing Monk'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'DAMAGE'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_auron():
    """Auron, Legendary Guardian: static — loads and registers >=1 interceptor."""
    name = 'Auron, Legendary Guardian'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_ifrit():
    """Ifrit, Hellfire: etb -> emits one of ['DAMAGE']"""
    name = 'Ifrit, Hellfire'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'DAMAGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_bahamut():
    """Bahamut, King of Dragons: etb -> emits one of ['DAMAGE']"""
    name = 'Bahamut, King of Dragons'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'DAMAGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_phoenix():
    """Phoenix, Flames of Rebirth: etb -> emits one of ['DAMAGE', 'ZONE_CHANGE']"""
    name = 'Phoenix, Flames of Rebirth'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'ZONE_CHANGE', 'DAMAGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_black_mage():
    """Black Mage: static — loads and registers >=1 interceptor."""
    name = 'Black Mage'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_berserker():
    """Berserker: attack -> emits one of ['PT_MODIFICATION']"""
    name = 'Berserker'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'PT_MODIFICATION'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_titan():
    """Titan, Gaia's Wrath: etb -> emits one of ['DESTROY', 'OBJECT_DESTROYED']"""
    name = "Titan, Gaia's Wrath"
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'OBJECT_DESTROYED', 'DESTROY'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_alexander():
    """Alexander, Divine Judgment: etb -> emits one of ['ZONE_CHANGE']"""
    name = 'Alexander, Divine Judgment'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'ZONE_CHANGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_knights_of_round():
    """Knights of the Round: etb -> emits one of ['CREATE_TOKEN', 'OBJECT_CREATED']"""
    name = 'Knights of the Round'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'CREATE_TOKEN', 'OBJECT_CREATED'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_dragoon():
    """Dragoon: etb -> emits one of ['DAMAGE']"""
    name = 'Dragoon'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'DAMAGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_kain_highwind():
    """Kain Highwind, Dragoon Commander: static — loads and registers >=1 interceptor."""
    name = 'Kain Highwind, Dragoon Commander'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_beastmaster():
    """Beastmaster: static — loads and registers >=1 interceptor."""
    name = 'Beastmaster'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_gold_chocobo():
    """Gold Chocobo: attack -> emits one of ['MANA_ADDED']"""
    name = 'Gold Chocobo'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'MANA_ADDED'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_moogle():
    """Moogle: etb -> emits one of ['DRAW']"""
    name = 'Moogle'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'DRAW'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_mog_king():
    """Mog, King of Moogles: static — loads and registers >=1 interceptor."""
    name = 'Mog, King of Moogles'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_buster_sword():
    """Buster Sword: static — loads and registers >=1 interceptor."""
    name = 'Buster Sword'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_ff7_party():
    """AVALANCHE Strike Team: attack -> emits one of ['COUNTER_ADDED']"""
    name = 'AVALANCHE Strike Team'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'COUNTER_ADDED'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_limit_charge():
    """Limit Charge: static — loads and registers >=1 interceptor."""
    name = 'Limit Charge'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_zack_fair():
    """Zack Fair, SOLDIER First Class: attack -> emits one of ['COUNTER_ADDED']"""
    name = 'Zack Fair, SOLDIER First Class'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'COUNTER_ADDED'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_edgar():
    """Edgar, King of Figaro: etb -> emits one of ['CREATE_TOKEN', 'OBJECT_CREATED']"""
    name = 'Edgar, King of Figaro'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'CREATE_TOKEN', 'OBJECT_CREATED'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_cadet_mage():
    """Cadet Mage: etb -> emits one of ['LIFE_CHANGE', 'SCRY']"""
    name = 'Cadet Mage'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'LIFE_CHANGE', 'SCRY'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_junior_summoner():
    """Junior Summoner: etb -> emits one of ['LIFE_CHANGE', 'SCRY']"""
    name = 'Junior Summoner'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'LIFE_CHANGE', 'SCRY'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_apprentice_scholar():
    """Apprentice Scholar: etb -> emits one of ['LIFE_CHANGE', 'SCRY']"""
    name = 'Apprentice Scholar'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'LIFE_CHANGE', 'SCRY'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_cadet_knight():
    """Cadet Knight: attack -> emits one of ['LIFE_CHANGE', 'SCRY']"""
    name = 'Cadet Knight'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'LIFE_CHANGE', 'SCRY'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_trance_mage():
    """Trance Mage: etb -> emits one of ['REVEAL_HAND', 'SCRY', 'SURVEIL']"""
    name = 'Trance Mage'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'SURVEIL', 'SCRY', 'REVEAL_HAND'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_recruit_soldier():
    """Recruit Soldier: etb -> emits one of ['LIFE_CHANGE', 'SCRY']"""
    name = 'Recruit Soldier'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'LIFE_CHANGE', 'SCRY'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_pixie_mage():
    """Pixie Mage: etb -> emits one of ['LIFE_CHANGE', 'SCRY', 'SURVEIL']"""
    name = 'Pixie Mage'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'LIFE_CHANGE', 'SCRY', 'SURVEIL'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_royal_knight():
    """Royal Knight: attack -> emits one of ['LIFE_CHANGE', 'SCRY']"""
    name = 'Royal Knight'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'LIFE_CHANGE', 'SCRY'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_sephiroth_avatar():
    """Sephiroth, Avatar of the Calamity: attack -> emits one of ['LIFE_CHANGE']"""
    name = 'Sephiroth, Avatar of the Calamity'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'LIFE_CHANGE'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_cid_highwind_sky_engine():
    """Cid Highwind, Sky-Engine Pilot: static — loads and registers >=1 interceptor."""
    name = 'Cid Highwind, Sky-Engine Pilot'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_cid_garlond_magitek():
    """Cid Garlond, Magitek Architect: etb -> emits one of ['LIFE_CHANGE']"""
    name = 'Cid Garlond, Magitek Architect'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'LIFE_CHANGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_black_mage_calamity():
    """Black Mage, Calamity Channeler: etb -> emits one of ['LIFE_CHANGE']"""
    name = 'Black Mage, Calamity Channeler'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'LIFE_CHANGE'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_white_mage_trinity():
    """White Mage, Trinity Healing: static — loads and registers >=1 interceptor."""
    name = 'White Mage, Trinity Healing'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


def test_sephiroth_reunion():
    """Sephiroth, Reunion Catalyst: death_self -> emits one of ['REVEAL_HAND']"""
    name = 'Sephiroth, Reunion Catalyst'
    game, p1, p2 = _new_game()
    emitted = _FIRE['death_self'](game, p1, p2, name)
    expected = {'REVEAL_HAND'}
    assert emitted & expected, f"{name}: death_self fired but expected one of {expected}, got {emitted}"


def test_cloud_strife_omnislash():
    """Cloud Strife, Limit Break Edge: attack -> emits one of ['COUNTER_ADDED']"""
    name = 'Cloud Strife, Limit Break Edge'
    game, p1, p2 = _new_game()
    emitted = _FIRE['attack'](game, p1, p2, name)
    expected = {'COUNTER_ADDED'}
    assert emitted & expected, f"{name}: attack fired but expected one of {expected}, got {emitted}"


def test_tifa_final_heaven():
    """Tifa, Final Heaven Master: etb -> emits one of ['SCRY']"""
    name = 'Tifa, Final Heaven Master'
    game, p1, p2 = _new_game()
    emitted = _FIRE['etb'](game, p1, p2, name)
    expected = {'SCRY'}
    assert emitted & expected, f"{name}: etb fired but expected one of {expected}, got {emitted}"


def test_materia_mastery_crescendo():
    """Materia Mastery, Limit Crescendo: static — loads and registers >=1 interceptor."""
    name = 'Materia Mastery, Limit Crescendo'
    game, p1, p2 = _new_game()
    obj = _put_on_battlefield(game, p1, name)
    assert obj.interceptor_ids, f"{name}: static card registered no interceptors"


if __name__ == "__main__":
    import traceback
    tests = sorted([(k, v) for k, v in globals().items()
                    if k.startswith("test_") and callable(v)])
    passed, failed, errors = [], [], []
    for name, t in tests:
        try:
            t(); passed.append(name)
        except AssertionError as e:
            failed.append((name, str(e)))
        except Exception as e:
            errors.append((name, f"{type(e).__name__}: {e}"))
    print("\n=== Princess Catholicon interceptor verification ===")
    print(f"  passed:  {len(passed)}")
    print(f"  failed:  {len(failed)}")
    print(f"  errors:  {len(errors)}")
    print(f"  skipped: {len(SKIPPED_CARDS)} (see SKIPPED_CARDS)")
    if failed:
        print("\n--- FAILURES ---")
        for n, m in failed[:50]:
            print(f"  {n}: {m}")
    if errors:
        print("\n--- ERRORS ---")
        for n, m in errors[:50]:
            print(f"  {n}: {m}")
    sys.exit(0 if not failed and not errors else 1)
