"""
Smoke tests for SUBS — generated by scripts/new_set/wire_set.py.

Asserts:
  - every card in the set imports without error
  - every card has a CardDefinition with name + characteristics
  - every starter deck builder runs without raising and returns a
    non-empty list of CardDefinitions

The "every card actually resolves in play" guarantee is enforced by the
balance-loop coverage stage (scripts/new_set/balance_loop.py +
scripts/new_set/coverage.py), which can detect missing implementations
via zero-play cards across the tournament — that check is engine-aware
where this scaffold is engine-agnostic by design.
"""

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from src.cards.depths.submarine_fleet import SUBS_CARDS
from src.cards.depths.submarine_fleet.decks import make_subs_wolfpack_deck, make_subs_silent_hunter_deck, make_subs_carrier_deck, make_subs_deep_strike_deck


def test_every_card_loads():
    assert SUBS_CARDS, "SUBS card registry is empty"
    for name, card in SUBS_CARDS.items():
        assert card is not None, f"{name}: card def is None"
        assert card.name, f"{name}: card has no .name"
        assert card.characteristics is not None, \
            f"{name}: card has no .characteristics"


def test_deck_wolfpack_builds():
    deck = make_subs_wolfpack_deck()
    assert deck, "wolfpack builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "wolfpack contains a None card"
        assert getattr(cd, "name", None), "wolfpack contains a nameless card"

def test_deck_silent_hunter_builds():
    deck = make_subs_silent_hunter_deck()
    assert deck, "silent_hunter builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "silent_hunter contains a None card"
        assert getattr(cd, "name", None), "silent_hunter contains a nameless card"

def test_deck_carrier_builds():
    deck = make_subs_carrier_deck()
    assert deck, "carrier builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "carrier contains a None card"
        assert getattr(cd, "name", None), "carrier contains a nameless card"

def test_deck_deep_strike_builds():
    deck = make_subs_deep_strike_deck()
    assert deck, "deep_strike builder returned an empty deck"
    for cd in deck:
        assert cd is not None, "deep_strike contains a None card"
        assert getattr(cd, "name", None), "deep_strike contains a nameless card"



if __name__ == "__main__":
    test_every_card_loads()
    test_deck_wolfpack_builds()
    test_deck_silent_hunter_builds()
    test_deck_carrier_builds()
    test_deck_deep_strike_builds()
    print("OK — SUBS smoke tests pass.")
