"""
Hyperdraft Stack Manager

Implements the MTG stack - a LIFO zone where spells and abilities
wait to resolve. Players can respond to items on the stack.
"""

from dataclasses import dataclass, field
from typing import Callable, Literal, Optional, Any
from enum import Enum, auto
import inspect
import os

from .types import (
    GameState, GameObject, ZoneType, CardType, Color,
    Event, EventType, new_id
)
from .targeting import Target, TargetRequirement, TargetingSystem
from .mana import ManaCost


class StackItemType(Enum):
    """Types of items that can be on the stack."""
    SPELL = auto()           # A spell being cast
    ACTIVATED_ABILITY = auto()
    TRIGGERED_ABILITY = auto()


@dataclass
class StackItem:
    """
    An item on the stack (spell or ability).
    """
    id: str
    type: StackItemType
    source_id: str           # Card/permanent that created this
    controller_id: str       # Who controls this spell/ability

    # For spells
    card_id: Optional[str] = None

    # Targeting
    target_requirements: list[TargetRequirement] = field(default_factory=list)
    chosen_targets: list[list[Target]] = field(default_factory=list)  # One list per requirement

    # Resolution
    resolve_fn: Optional[Callable[[list[list[Target]], GameState], list[Event]]] = None

    # X value (for spells with {X} in cost)
    x_value: int = 0

    # Modes (for modal spells)
    chosen_modes: list[int] = field(default_factory=list)

    # Additional data
    additional_data: dict = field(default_factory=dict)

    # Metadata
    timestamp: int = 0
    can_be_countered: bool = True

    def __repr__(self) -> str:
        return f"StackItem({self.type.name}, source={self.source_id})"


@dataclass
class StackEvent:
    """Event emitted when stack changes."""
    event_type: Literal['push', 'pop', 'counter', 'resolve']
    item: StackItem
    result: Any = None


class StackManager:
    """
    Manages the stack - spells and abilities waiting to resolve.

    The stack is LIFO (Last In, First Out):
    - Items are added to the top
    - The top item resolves first
    - Players get priority between each resolution
    """

    def __init__(self, state: GameState):
        self.state = state
        self.items: list[StackItem] = []
        self.targeting_system = TargetingSystem(state)
        self._event_listeners: list[Callable[[StackEvent], None]] = []

    def is_empty(self) -> bool:
        """Check if the stack is empty."""
        return len(self.items) == 0

    def size(self) -> int:
        """Get number of items on the stack."""
        return len(self.items)

    def top(self) -> Optional[StackItem]:
        """Get the top item without removing it."""
        return self.items[-1] if self.items else None

    def get_items(self) -> list[StackItem]:
        """Get all items (bottom to top)."""
        return list(self.items)

    def get_item(self, item_id: str) -> Optional[StackItem]:
        """Get a specific item by ID."""
        for item in self.items:
            if item.id == item_id:
                return item
        return None

    def push(self, item: StackItem) -> None:
        """
        Push an item onto the stack.
        """
        item.timestamp = self.state.next_timestamp()
        item.id = item.id or new_id()
        self.items.append(item)

        # If it's a spell, move the card to the stack zone
        if item.type == StackItemType.SPELL and item.card_id:
            self._move_to_stack(item.card_id)

        self._emit_event(StackEvent('push', item))

    def pop(self) -> Optional[StackItem]:
        """
        Remove and return the top item.
        """
        if not self.items:
            return None

        item = self.items.pop()
        self._emit_event(StackEvent('pop', item))
        return item

    def resolve_top(self) -> list[Event]:
        """
        Resolve the top item of the stack.

        Returns events generated by the resolution.
        """
        if not self.items:
            return []

        item = self.items.pop()

        # Determine targets to pass to resolve function
        # If we have formal target_requirements, validate them
        # Otherwise, use chosen_targets directly (for text-parsed spells)
        if item.target_requirements:
            all_legal_targets = []
            has_any_legal = True

            for i, requirement in enumerate(item.target_requirements):
                if i < len(item.chosen_targets):
                    chosen = item.chosen_targets[i]
                    _, legal = self.targeting_system.validate_targets(
                        chosen,
                        requirement,
                        self.state.objects.get(item.source_id),
                        item.controller_id
                    )
                    all_legal_targets.append(legal)

                    # If this requirement needs targets and has none legal, spell fizzles
                    if requirement.min_targets() > 0 and len(legal) == 0:
                        has_any_legal = False
                else:
                    all_legal_targets.append([])

            # If spell has targets but none are legal, it's countered (fizzles)
            if not has_any_legal:
                return self._counter_item(item, reason='no_legal_targets')

            targets_for_resolve = all_legal_targets
        else:
            # No formal requirements - use chosen_targets directly
            # (Common for text-parsed spells)
            targets_for_resolve = item.chosen_targets

        # Resolve the spell/ability
        events = []
        if item.resolve_fn:
            try:
                fn = item.resolve_fn

                # Card scripts vary in their resolve signature:
                # - Newer scripts: resolve(targets, state)
                # - Legacy scripts: resolve(event, state)
                use_event = False
                try:
                    sig = inspect.signature(fn)
                    params = list(sig.parameters.values())
                    if len(params) >= 2:
                        p0 = params[0]
                        if p0.name in {"event", "spell_event", "resolve_event"}:
                            use_event = True
                        elif p0.annotation is Event:
                            use_event = True
                except Exception:
                    # Fall back to targets-style.
                    use_event = False

                if use_event:
                    resolve_event = Event(
                        type=EventType.CAST,
                        payload={
                            "targets": targets_for_resolve,
                            # Carry casting metadata through to legacy card scripts
                            # that resolve via an Event (e.g. "if this spell was cast
                            # from a graveyard...").
                            **(item.additional_data or {}),
                        },
                        source=item.source_id,
                        controller=item.controller_id,
                    )
                    events = fn(resolve_event, self.state) or []
                else:
                    events = fn(targets_for_resolve, self.state) or []
            except Exception as e:
                # Log error but don't crash the game.
                card_name = None
                if item.card_id and item.card_id in self.state.objects:
                    card_name = self.state.objects[item.card_id].name
                elif item.source_id in self.state.objects:
                    card_name = self.state.objects[item.source_id].name
                fn_name = getattr(item.resolve_fn, "__name__", repr(item.resolve_fn))
                print(f"Error resolving {item} ({card_name or 'unknown'} resolve={fn_name}): {e}")
                if os.environ.get("HYPERDRAFT_STRICT_STACK") == "1":
                    raise

        # Handle post-resolution
        if item.type == StackItemType.SPELL and item.card_id:
            events.extend(self._handle_spell_resolution(item))

        self._emit_event(StackEvent('resolve', item, result=events))
        return events

    def counter(self, item_id: str, reason: str = 'countered') -> list[Event]:
        """
        Counter a spell or ability on the stack.
        """
        # Find and remove the item
        for i, item in enumerate(self.items):
            if item.id == item_id:
                if not item.can_be_countered:
                    return []  # Can't be countered (e.g., "can't be countered" clause)

                self.items.pop(i)
                return self._counter_item(item, reason)

        return []

    def _counter_item(self, item: StackItem, reason: str) -> list[Event]:
        """Handle a countered spell/ability."""
        events = []

        if item.type == StackItemType.SPELL and item.card_id:
            # Replacement effects (Flashback/Harmonize/etc.): exile the card
            # instead of putting it anywhere else when it leaves the stack.
            if item.additional_data.get('exile_on_leave_stack'):
                events.append(Event(
                    type=EventType.ZONE_CHANGE,
                    payload={
                        'object_id': item.card_id,
                        'from_zone': 'stack',
                        'to_zone': 'exile',
                        'to_zone_type': ZoneType.EXILE,
                        'reason': reason,
                    }
                ))
            else:
                # Default: countered spells go to graveyard.
                events.append(Event(
                    type=EventType.ZONE_CHANGE,
                    payload={
                        'object_id': item.card_id,
                        'from_zone': 'stack',
                        'to_zone': f'graveyard_{self.state.objects[item.card_id].owner}',
                        'to_zone_type': ZoneType.GRAVEYARD,
                        'reason': reason
                    }
                ))

        self._emit_event(StackEvent('counter', item, result=reason))
        return events

    def _handle_spell_resolution(self, item: StackItem) -> list[Event]:
        """
        Handle what happens to a spell after it resolves.
        """
        events = []
        card = self.state.objects.get(item.card_id)

        if not card:
            return events

        card_types = card.characteristics.types

        # Permanents enter the battlefield
        if any(t in card_types for t in [
            CardType.CREATURE, CardType.ARTIFACT, CardType.ENCHANTMENT,
            CardType.LAND, CardType.PLANESWALKER
        ]):
            events.append(Event(
                type=EventType.ZONE_CHANGE,
                payload={
                    'object_id': item.card_id,
                    'from_zone': 'stack',
                    'to_zone': 'battlefield',
                    'to_zone_type': ZoneType.BATTLEFIELD
                }
            ))
        else:
            # Instants and sorceries go to graveyard unless a replacement
            # effect like flashback/harmonize exiles them.
            if item.additional_data.get('exile_on_leave_stack'):
                events.append(Event(
                    type=EventType.ZONE_CHANGE,
                    payload={
                        'object_id': item.card_id,
                        'from_zone': 'stack',
                        'to_zone': 'exile',
                        'to_zone_type': ZoneType.EXILE,
                    }
                ))
            else:
                events.append(Event(
                    type=EventType.ZONE_CHANGE,
                    payload={
                        'object_id': item.card_id,
                        'from_zone': 'stack',
                        'to_zone': f'graveyard_{card.owner}',
                        'to_zone_type': ZoneType.GRAVEYARD
                    }
                ))

        return events

    def _move_to_stack(self, card_id: str) -> None:
        """Move a card to the stack zone."""
        card = self.state.objects.get(card_id)
        if not card:
            return

        # Remove from current zone
        for zone in self.state.zones.values():
            while card_id in zone.objects:
                zone.objects.remove(card_id)

        # Add to stack zone
        stack_zone = self.state.zones.get('stack')
        if stack_zone:
            stack_zone.objects.append(card_id)

        card.zone = ZoneType.STACK
        card.entered_zone_at = self.state.timestamp

    def add_event_listener(self, listener: Callable[[StackEvent], None]) -> None:
        """Add a listener for stack events."""
        self._event_listeners.append(listener)

    def remove_event_listener(self, listener: Callable[[StackEvent], None]) -> None:
        """Remove a stack event listener."""
        if listener in self._event_listeners:
            self._event_listeners.remove(listener)

    def _emit_event(self, event: StackEvent) -> None:
        """Emit a stack event to all listeners."""
        for listener in self._event_listeners:
            try:
                listener(event)
            except Exception as e:
                print(f"Error in stack event listener: {e}")


class SpellBuilder:
    """
    Helper for building spells to put on the stack.
    """

    def __init__(self, state: GameState, stack: StackManager):
        self.state = state
        self.stack = stack

    def cast_spell(
        self,
        card_id: str,
        controller_id: str,
        targets: list[list[Target]] = None,
        x_value: int = 0,
        modes: list[int] = None,
        additional_data: Optional[dict] = None,
    ) -> StackItem:
        """
        Create a spell stack item for a card.
        """
        card = self.state.objects.get(card_id)
        if not card:
            raise ValueError(f"Card {card_id} not found")

        item = StackItem(
            id=new_id(),
            type=StackItemType.SPELL,
            source_id=card_id,
            controller_id=controller_id,
            card_id=card_id,
            chosen_targets=targets or [],
            x_value=x_value,
            chosen_modes=modes or []
        )

        if additional_data:
            # Spell metadata used by rules glue (e.g., flashback exile).
            item.additional_data.update(dict(additional_data))

        # Get resolve function from card definition
        if card.card_def and card.card_def.resolve:
            item.resolve_fn = card.card_def.resolve

        # If no explicit resolve function, try to create one from text
        if not item.resolve_fn and card.card_def and card.card_def.text:
            item.resolve_fn = self._create_resolve_from_text(card.card_def.text, card_id)

        return item

    def _create_resolve_from_text(self, text: str, source_id: str) -> Callable:
        """
        Create a resolve function by parsing card text.

        Patterns are checked in priority order; the first matching pattern wins.
        Newer/specific patterns (token creation, counters, scry/surveil/mill,
        pump, discard, tap, investigate, basic-land tutor) are checked before
        the legacy generic patterns (damage, destroy, exile, counterspell,
        bounce, draw, gain/lose life). See ``src/engine/spell_resolve.py`` for
        composable resolve helpers card scripts can use directly.
        """
        text_lower = text.lower()

        import re

        # ---------------------------------------------------------------
        # Helpers shared by the patterns below.
        # ---------------------------------------------------------------
        def _caster_id() -> Optional[str]:
            """Return the controller of the resolving spell, if known."""
            obj = self.state.objects.get(source_id) if self.state else None
            if obj is None:
                return None
            return obj.controller

        _NUMBER_WORDS = {
            'a': 1, 'an': 1, 'one': 1, 'two': 2, 'three': 3,
            'four': 4, 'five': 5, 'six': 6, 'seven': 7,
            'eight': 8, 'nine': 9, 'ten': 10,
        }

        def _word_or_int(s: str) -> int:
            s = s.strip().lower()
            if s in _NUMBER_WORDS:
                return _NUMBER_WORDS[s]
            try:
                return int(s)
            except ValueError:
                return 1

        # Color word -> Color enum.
        _COLOR_WORDS = {
            'white': Color.WHITE, 'blue': Color.BLUE, 'black': Color.BLACK,
            'red': Color.RED, 'green': Color.GREEN, 'colorless': Color.COLORLESS,
        }
        # Mana symbols -> Color enum.
        _MANA_SYMBOL = {
            'w': Color.WHITE, 'u': Color.BLUE, 'b': Color.BLACK,
            'r': Color.RED, 'g': Color.GREEN,
        }

        # Common token subtypes that show up in modern set text. The tuple
        # below is ordered roughly by how unambiguous each subtype is when it
        # appears in card text — multi-word names go first so we don't match
        # a substring of one in another.
        _TOKEN_SUBTYPES = [
            'Treasure', 'Food', 'Clue', 'Map', 'Blood', 'Powerstone',
            'Soldier', 'Goblin', 'Spirit', 'Zombie', 'Saproling',
            'Knight', 'Elf', 'Wolf', 'Wolves', 'Cat', 'Bird',
            'Drake', 'Beast', 'Dragon', 'Insect', 'Snake', 'Rat',
            'Skeleton', 'Servo', 'Thopter', 'Squirrel', 'Pirate',
            'Vampire', 'Demon', 'Angel', 'Faerie', 'Frog',
        ]
        # Subtypes that produce non-creature artifact tokens.
        _NONCREATURE_ARTIFACT_TOKENS = {'Treasure', 'Food', 'Clue', 'Map',
                                        'Blood', 'Powerstone'}

        def _build_token_event(
            count: int,
            power: Optional[int],
            toughness: Optional[int],
            colors: list,
            subtypes: list,
            types: list,
        ) -> list[Event]:
            """Emit `count` OBJECT_CREATED events for tokens."""
            caster = _caster_id()
            evs: list[Event] = []
            for _ in range(max(count, 0)):
                payload: dict = {
                    'name': (subtypes[0] if subtypes else 'Token') + ' Token',
                    'controller': caster,
                    'types': list(types),
                    'subtypes': list(subtypes),
                    'colors': list(colors),
                    'is_token': True,
                }
                if power is not None:
                    payload['power'] = power
                if toughness is not None:
                    payload['toughness'] = toughness
                evs.append(Event(
                    type=EventType.OBJECT_CREATED,
                    payload=payload,
                    source=source_id,
                    controller=caster,
                ))
            return evs

        # ---------------------------------------------------------------
        # 1. Token creation. "Create a 1/1 white Soldier creature token"
        #    "Create N [color]* [subtype] creature tokens"
        #    Also handles non-creature tokens with known names: Treasure,
        #    Food, Clue, Map, Blood, Powerstone (those are colorless artifacts
        #    that don't have P/T).
        # ---------------------------------------------------------------
        # Creature token: "create [count] X/Y [colors] [subtype] creature token(s)"
        creature_token_re = re.compile(
            r'create\s+(?P<count>a|an|one|two|three|four|five|six|seven|eight|nine|ten|\d+)'
            r'(?:\s+(?P<plusone>\+1/\+1\s+counter))?'  # avoid colliding with counters pattern
            r'\s+(?P<power>\d+)/(?P<toughness>\d+)'
            r'(?P<rest>[^.]*)\bcreature token',
            re.IGNORECASE,
        )
        m = creature_token_re.search(text_lower)
        if m and not m.group('plusone'):
            count = _word_or_int(m.group('count'))
            power = int(m.group('power'))
            toughness = int(m.group('toughness'))
            rest = m.group('rest') or ''

            colors: list = []
            for word, color in _COLOR_WORDS.items():
                if re.search(rf'\b{word}\b', rest):
                    colors.append(color)
            for sym, color in _MANA_SYMBOL.items():
                if '{' + sym + '}' in rest or '{' + sym.upper() + '}' in rest:
                    if color not in colors:
                        colors.append(color)

            subtypes: list[str] = []
            for sub in _TOKEN_SUBTYPES:
                if re.search(rf'\b{sub.lower()}\b', rest):
                    # Normalize plural (Wolves -> Wolf etc.); we keep the
                    # canonical form found in _TOKEN_SUBTYPES.
                    subtypes.append('Wolf' if sub == 'Wolves' else sub)

            def token_creature_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                return _build_token_event(
                    count=count,
                    power=power,
                    toughness=toughness,
                    colors=colors,
                    subtypes=subtypes,
                    types=[CardType.CREATURE],
                )

            return token_creature_resolve

        # Non-creature artifact tokens (Treasure/Food/Clue/Map/Blood/Powerstone).
        # "Create N [Treasure|Food|Clue|Map|Blood|Powerstone] token(s)"
        nc_token_re = re.compile(
            r'create\s+(?P<count>a|an|one|two|three|four|five|six|seven|eight|nine|ten|\d+)'
            r'\s+(?P<sub>treasure|food|clue|map|blood|powerstone)\s+tokens?',
            re.IGNORECASE,
        )
        m = nc_token_re.search(text_lower)
        if m:
            count = _word_or_int(m.group('count'))
            sub_raw = m.group('sub').strip().capitalize()

            def token_artifact_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                return _build_token_event(
                    count=count,
                    power=None,
                    toughness=None,
                    colors=[Color.COLORLESS],
                    subtypes=[sub_raw],
                    types=[CardType.ARTIFACT],
                )

            return token_artifact_resolve

        # ---------------------------------------------------------------
        # 7. Investigate / Investigate N times.  (Earlier than counters so
        #    "Investigate. Put a +1/+1 counter on..." doesn't get hijacked.)
        # ---------------------------------------------------------------
        investigate_re = re.compile(
            r'\binvestigate(?:\s+(?P<count>a|an|one|two|three|four|five|six|seven|eight|nine|ten|\d+)\s+times?)?\b',
            re.IGNORECASE,
        )
        m = investigate_re.search(text_lower)
        if m:
            count = _word_or_int(m.group('count')) if m.group('count') else 1

            def investigate_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                return _build_token_event(
                    count=count,
                    power=None,
                    toughness=None,
                    colors=[Color.COLORLESS],
                    subtypes=['Clue'],
                    types=[CardType.ARTIFACT],
                )

            return investigate_resolve

        # ---------------------------------------------------------------
        # 2. +1/+1 counter on target creature. "Put a +1/+1 counter on
        #    target X" / "Put N +1/+1 counters on target X".
        # ---------------------------------------------------------------
        counter_plusone_re = re.compile(
            r'put\s+(?P<count>a|an|one|two|three|four|five|six|seven|eight|nine|ten|\d+)\s+'
            r'\+1/\+1\s+counters?\s+on\s+target',
            re.IGNORECASE,
        )
        m = counter_plusone_re.search(text_lower)
        if m:
            count = _word_or_int(m.group('count'))

            def plus_one_counter_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                events: list[Event] = []
                if targets and targets[0]:
                    for target in targets[0]:
                        if target.is_player:
                            continue
                        events.append(Event(
                            type=EventType.COUNTER_ADDED,
                            payload={
                                'object_id': target.id,
                                'counter_type': '+1/+1',
                                'amount': count,
                            },
                            source=source_id,
                        ))
                return events

            return plus_one_counter_resolve

        # ---------------------------------------------------------------
        # 3. Scry / Surveil / Mill / "target player mills N".
        # ---------------------------------------------------------------
        # Mill-target form: "target player mills N"
        mill_target_re = re.compile(
            r'target\s+(?:opponent|player)\s+mills?\s+'
            r'(?P<count>a|an|one|two|three|four|five|six|seven|eight|nine|ten|\d+)',
            re.IGNORECASE,
        )
        m = mill_target_re.search(text_lower)
        if m:
            count = _word_or_int(m.group('count'))

            def mill_target_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                events: list[Event] = []
                if targets and targets[0]:
                    for target in targets[0]:
                        if target.is_player:
                            events.append(Event(
                                type=EventType.MILL,
                                payload={'player': target.id, 'amount': count},
                                source=source_id,
                            ))
                return events

            return mill_target_resolve

        # Plain mill (controller mills): "mill N", "mill N cards"
        mill_re = re.compile(
            r'\bmill\s+(?P<count>a|an|one|two|three|four|five|six|seven|eight|nine|ten|\d+)\s*(?:cards?)?',
            re.IGNORECASE,
        )
        m = mill_re.search(text_lower)
        if m and 'opponent mills' not in text_lower and 'player mills' not in text_lower:
            count = _word_or_int(m.group('count'))

            def mill_self_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                caster = _caster_id()
                if not caster:
                    return []
                return [Event(
                    type=EventType.MILL,
                    payload={'player': caster, 'amount': count},
                    source=source_id,
                    controller=caster,
                )]

            return mill_self_resolve

        # Surveil N (controller surveils — surveil targets are unusual).
        surveil_re = re.compile(
            r'\bsurveil\s+(?P<count>a|an|one|two|three|four|five|six|seven|eight|nine|ten|\d+)',
            re.IGNORECASE,
        )
        m = surveil_re.search(text_lower)
        if m:
            count = _word_or_int(m.group('count'))

            def surveil_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                caster = _caster_id()
                if not caster:
                    return []
                return [Event(
                    type=EventType.SURVEIL,
                    payload={'player': caster, 'amount': count},
                    source=source_id,
                    controller=caster,
                )]

            return surveil_resolve

        # Scry N (controller scries).
        scry_re = re.compile(
            r'\bscry\s+(?P<count>a|an|one|two|three|four|five|six|seven|eight|nine|ten|\d+)',
            re.IGNORECASE,
        )
        m = scry_re.search(text_lower)
        if m:
            count = _word_or_int(m.group('count'))

            def scry_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                caster = _caster_id()
                if not caster:
                    return []
                return [Event(
                    type=EventType.SCRY,
                    payload={'player': caster, 'amount': count},
                    source=source_id,
                    controller=caster,
                )]

            return scry_resolve

        # ---------------------------------------------------------------
        # 4. Pump until end of turn. "Target creature gets +N/+M until end
        #    of turn" — also matches negative modifiers ("-2/-0" etc.).
        # ---------------------------------------------------------------
        pump_re = re.compile(
            r'target\s+(?:creature|permanent|player)?\s*gets?\s+'
            r'(?P<p>[+-]\d+)/(?P<t>[+-]\d+)\s+until\s+end\s+of\s+turn',
            re.IGNORECASE,
        )
        m = pump_re.search(text_lower)
        if m:
            p_mod = int(m.group('p'))
            t_mod = int(m.group('t'))

            def pump_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                events: list[Event] = []
                if targets and targets[0]:
                    for target in targets[0]:
                        if target.is_player:
                            continue
                        events.append(Event(
                            type=EventType.PT_MODIFICATION,
                            payload={
                                'object_id': target.id,
                                'power_mod': p_mod,
                                'toughness_mod': t_mod,
                                'duration': 'end_of_turn',
                            },
                            source=source_id,
                        ))
                return events

            return pump_resolve

        # ---------------------------------------------------------------
        # 5. Discard. "Target player discards N cards" /
        #    "Each opponent discards a card".
        # ---------------------------------------------------------------
        # "each opponent discards [N] card(s)"
        each_opp_discard_re = re.compile(
            r'each\s+opponent\s+discards?\s+'
            r'(?P<count>a|an|one|two|three|four|five|six|seven|eight|nine|ten|\d+)\s*cards?',
            re.IGNORECASE,
        )
        m = each_opp_discard_re.search(text_lower)
        if m:
            count = _word_or_int(m.group('count'))

            def each_opp_discard_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                caster = _caster_id()
                if not caster:
                    return []
                events: list[Event] = []
                for pid in state.players:
                    if pid == caster:
                        continue
                    events.append(Event(
                        type=EventType.DISCARD,
                        payload={'player': pid, 'amount': count},
                        source=source_id,
                    ))
                return events

            return each_opp_discard_resolve

        # "target player discards N card(s)" / "target opponent discards N card(s)"
        target_discard_re = re.compile(
            r'target\s+(?:player|opponent)\s+discards?\s+'
            r'(?P<count>a|an|one|two|three|four|five|six|seven|eight|nine|ten|\d+)\s*cards?',
            re.IGNORECASE,
        )
        m = target_discard_re.search(text_lower)
        if m:
            count = _word_or_int(m.group('count'))

            def target_discard_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                events: list[Event] = []
                if targets and targets[0]:
                    for target in targets[0]:
                        if target.is_player:
                            events.append(Event(
                                type=EventType.DISCARD,
                                payload={'player': target.id, 'amount': count},
                                source=source_id,
                            ))
                return events

            return target_discard_resolve

        # ---------------------------------------------------------------
        # 6. Tap target. "Tap target [creature/permanent]"
        # ---------------------------------------------------------------
        if re.search(r'\btap\s+target\b', text_lower):
            def tap_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                events: list[Event] = []
                if targets and targets[0]:
                    for target in targets[0]:
                        if target.is_player:
                            continue
                        events.append(Event(
                            type=EventType.TAP,
                            payload={'object_id': target.id},
                            source=source_id,
                        ))
                return events

            return tap_resolve

        # ---------------------------------------------------------------
        # 8. Search your library for a basic land card, put it onto the
        #    battlefield tapped, then shuffle.
        # ---------------------------------------------------------------
        if re.search(
            r'search your library for a basic land card.*battlefield tapped.*shuffle',
            text_lower,
        ):
            def basic_land_search_resolve(
                targets: list[list[Target]], state: GameState
            ) -> list[Event]:
                caster = _caster_id()
                if not caster:
                    return []
                # Try the player-choice library_search subsystem first.
                try:
                    from .library_search import create_library_search_choice

                    def is_basic_land(obj: GameObject, _state: GameState) -> bool:
                        if not obj.characteristics:
                            return False
                        if CardType.LAND not in obj.characteristics.types:
                            return False
                        return 'basic' in {
                            s.lower() for s in obj.characteristics.supertypes
                        }

                    create_library_search_choice(
                        state, caster, source_id,
                        filter_fn=is_basic_land,
                        destination='battlefield_tapped',
                        shuffle_after=True,
                        prompt='Search your library for a basic land card',
                    )
                    # Side-effect path: choice opened, no synchronous events.
                    return []
                except Exception:
                    # Fallback marker event so callers see the tutor was attempted.
                    return [Event(
                        type=EventType.LIBSEARCH_BEGIN,
                        payload={
                            'player': caster,
                            'destination': 'battlefield_tapped',
                            'filter': 'basic_land',
                            'shuffle_after': True,
                        },
                        source=source_id,
                        controller=caster,
                    )]

            return basic_land_search_resolve

        # ---------------------------------------------------------------
        # Existing legacy patterns follow.
        # ---------------------------------------------------------------

        # "deals X damage to any target" or "deals X damage to target creature"
        damage_match = re.search(r'deals (\d+) damage', text_lower)
        if damage_match:
            amount = int(damage_match.group(1))

            def damage_resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
                events = []
                if targets and targets[0]:
                    for target in targets[0]:
                        events.append(Event(
                            type=EventType.DAMAGE,
                            payload={
                                'target': target.id,
                                'amount': amount,
                                'is_combat': False,
                                'is_player': target.is_player
                            },
                            source=source_id
                        ))
                return events

            return damage_resolve

        # "destroy target creature/permanent"
        if 'destroy target' in text_lower:
            def destroy_resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
                events = []
                if targets and targets[0]:
                    for target in targets[0]:
                        if not target.is_player:
                            events.append(Event(
                                type=EventType.OBJECT_DESTROYED,
                                payload={'object_id': target.id},
                                source=source_id
                            ))
                return events

            return destroy_resolve

        # "exile target creature/permanent"
        if 'exile target' in text_lower:
            def exile_resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
                events = []
                if targets and targets[0]:
                    for target in targets[0]:
                        if not target.is_player:
                            events.append(Event(
                                type=EventType.ZONE_CHANGE,
                                payload={
                                    'object_id': target.id,
                                    'to_zone_type': ZoneType.EXILE,
                                    'to_zone': 'exile'
                                },
                                source=source_id
                            ))
                return events

            return exile_resolve

        # "counter target spell"
        if 'counter target spell' in text_lower:
            def counter_resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
                events = []
                if targets and targets[0]:
                    for target in targets[0]:
                        # The stack manager will handle this
                        events.append(Event(
                            type=EventType.ZONE_CHANGE,
                            payload={
                                'object_id': target.id,
                                'to_zone_type': ZoneType.GRAVEYARD,
                                'reason': 'countered'
                            },
                            source=source_id
                        ))
                return events

            return counter_resolve

        # "return target ... to ... hand" - bounce spells
        if 'return target' in text_lower and 'hand' in text_lower:
            def bounce_resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
                events = []
                if targets and targets[0]:
                    for target in targets[0]:
                        if not target.is_player:
                            target_obj = state.objects.get(target.id)
                            if target_obj:
                                owner_id = target_obj.owner
                                events.append(Event(
                                    type=EventType.ZONE_CHANGE,
                                    payload={
                                        'object_id': target.id,
                                        'to_zone_type': ZoneType.HAND,
                                        'to_zone': f'hand_{owner_id}',
                                        'reason': 'bounced'
                                    },
                                    source=source_id
                                ))
                return events

            return bounce_resolve

        # "draw X cards" or "draw a card"
        draw_match = re.search(r'draw (\d+|a|an) cards?', text_lower)
        if draw_match:
            count_str = draw_match.group(1)
            count = 1 if count_str in ('a', 'an') else int(count_str)

            def draw_resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
                # Drawing doesn't target - controller draws
                return [Event(
                    type=EventType.DRAW,
                    payload={'count': count},
                    source=source_id
                )]

            return draw_resolve

        # "gains X life" or "gain X life"
        life_match = re.search(r'gains? (\d+) life', text_lower)
        if life_match:
            amount = int(life_match.group(1))

            def lifegain_resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
                return [Event(
                    type=EventType.LIFE_CHANGE,
                    payload={'amount': amount},
                    source=source_id
                )]

            return lifegain_resolve

        # "loses X life" or "lose X life" targeting a player
        lifeloss_match = re.search(r'loses? (\d+) life', text_lower)
        if lifeloss_match and 'target' in text_lower:
            amount = int(lifeloss_match.group(1))

            def lifeloss_resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
                events = []
                if targets and targets[0]:
                    for target in targets[0]:
                        if target.is_player:
                            events.append(Event(
                                type=EventType.LIFE_CHANGE,
                                payload={'player': target.id, 'amount': -amount},
                                source=source_id
                            ))
                return events

            return lifeloss_resolve

        return None

    def create_ability(
        self,
        source_id: str,
        controller_id: str,
        ability_type: StackItemType,
        resolve_fn: Callable,
        targets: list[list[Target]] = None,
        target_requirements: list[TargetRequirement] = None
    ) -> StackItem:
        """
        Create an ability stack item.
        """
        return StackItem(
            id=new_id(),
            type=ability_type,
            source_id=source_id,
            controller_id=controller_id,
            resolve_fn=resolve_fn,
            target_requirements=target_requirements or [],
            chosen_targets=targets or []
        )


# Utility functions for common stack operations

def create_damage_spell(
    amount: int,
    target_filter,
    card_id: str = None,
    source_id: str = None
) -> Callable:
    """
    Create a resolve function for a damage spell.

    Example: Lightning Bolt deals 3 damage
    """
    def resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
        events = []
        if targets and targets[0]:
            for target in targets[0]:
                events.append(Event(
                    type=EventType.DAMAGE,
                    payload={
                        'target': target.id,
                        'amount': amount,
                        'is_combat': False
                    },
                    source=source_id or card_id
                ))
        return events
    return resolve


def create_draw_spell(count: int) -> Callable:
    """
    Create a resolve function for a draw spell.
    """
    def resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
        # Draw spells typically don't target (the controller draws)
        # The controller would be set elsewhere
        return [Event(
            type=EventType.DRAW,
            payload={'count': count}
        )]
    return resolve


def create_destroy_spell(target_filter) -> Callable:
    """
    Create a resolve function for a destroy spell.
    """
    def resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
        events = []
        if targets and targets[0]:
            for target in targets[0]:
                if not target.is_player:
                    events.append(Event(
                        type=EventType.OBJECT_DESTROYED,
                        payload={'object_id': target.id}
                    ))
        return events
    return resolve


def create_counter_spell(target_filter=None) -> Callable:
    """
    Create a resolve function for a counterspell.
    """
    def resolve(targets: list[list[Target]], state: GameState) -> list[Event]:
        # Counterspells target spells on the stack
        # The actual countering is handled by the stack manager
        # This just marks what should be countered
        if targets and targets[0]:
            return [Event(
                type=EventType.ZONE_CHANGE,  # Countered spells go to graveyard
                payload={
                    'object_id': targets[0][0].id,
                    'to_zone_type': ZoneType.GRAVEYARD,
                    'reason': 'countered'
                }
            )]
        return []
    return resolve
