from .fina import FINA_CARDS, FINA_STARTER_DECKS
from .finm import FINM_CARDS, FINM_STARTER_DECKS
from .decks import FINANCE_CONSTRUCTED_DECKS
# Finance TCG card sets

FINANCE_CARDS: dict = {**FINA_CARDS, **FINM_CARDS}
FINANCE_STARTER_DECKS = {
    **FINA_STARTER_DECKS,
    **FINM_STARTER_DECKS,
}
FINANCE_DECKS = {
    **FINANCE_STARTER_DECKS,
    **FINANCE_CONSTRUCTED_DECKS,
}
