"""Aggregate Phase B per-set missing-card reports into a punch list.

Reads .missing_reports/<set>.json files. Emits a markdown summary appended
to engine_gaps.md and a per-set tally.
"""
from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REPORTS = ROOT / ".missing_reports"
GAP_OUT = ROOT / "engine_gaps.md"


def main() -> None:
    if not REPORTS.exists():
        print(f"No reports directory at {REPORTS}")
        return
    reports = sorted(REPORTS.glob("*.json"))
    if not reports:
        print("No report JSON files found.")
        return

    per_set: dict[str, Counter] = {}
    gaps: dict[str, list[dict]] = defaultdict(list)
    totals = Counter()

    for path in reports:
        data = json.loads(path.read_text())
        set_name = data.get("set", path.stem + ".py")
        results = data.get("results", [])
        counts = Counter(r["disposition"] for r in results)
        per_set[set_name] = counts
        totals.update(counts)
        for r in results:
            gap = (r.get("engine_gap") or "").strip()
            if gap:
                gaps[gap].append({
                    "set": set_name,
                    "fn": r.get("fn"),
                    "card_var": r.get("card_var"),
                    "notes": r.get("notes", ""),
                })

    lines = []
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("# Missing-Interceptor Sweep — Per-Set Dispositions")
    lines.append("")
    lines.append("Generated by `scripts/aggregate_missing_reports.py` from "
                 "`.missing_reports/*.json`. Counts cards that previously had no "
                 "`setup_interceptors=` and got one written by the sweep.")
    lines.append("")
    cats = ["wired_full", "wired_stub", "skipped"]
    header = "| set | " + " | ".join(cats) + " | total |"
    sep = "|" + "---|" * (len(cats) + 2)
    lines.append(header)
    lines.append(sep)
    for set_name, counts in sorted(per_set.items()):
        total = sum(counts.values())
        row = f"| {set_name} | " + " | ".join(str(counts.get(c, 0)) for c in cats) + f" | {total} |"
        lines.append(row)
    lines.append("")
    lines.append(f"**Totals:** wired_full={totals.get('wired_full', 0)}, "
                 f"wired_stub={totals.get('wired_stub', 0)}, "
                 f"skipped={totals.get('skipped', 0)}")
    lines.append("")

    if gaps:
        lines.append("## Engine gaps surfaced by the sweep")
        lines.append("")
        sorted_gaps = sorted(gaps.items(), key=lambda kv: -len(kv[1]))
        for gap_desc, items in sorted_gaps[:25]:  # cap to top 25 to keep file manageable
            lines.append(f"### {gap_desc} ({len(items)} cards)")
            lines.append("")
            # Show first 8 examples per gap
            for it in items[:8]:
                lines.append(f"- `{it['set']}` :: `{it['fn']}` (card `{it['card_var']}`)")
            if len(items) > 8:
                lines.append(f"- ... and {len(items) - 8} more")
            lines.append("")
        if len(gaps) > 25:
            lines.append(f"_({len(gaps) - 25} additional gap categories omitted for brevity.)_")
            lines.append("")

    # Append to engine_gaps.md (after a separator)
    existing = GAP_OUT.read_text() if GAP_OUT.exists() else ""
    GAP_OUT.write_text(existing + "\n".join(lines) + "\n")
    print(f"Appended missing-sweep summary to {GAP_OUT}")
    print(f"Totals: wired_full={totals.get('wired_full',0)} "
          f"wired_stub={totals.get('wired_stub',0)} "
          f"skipped={totals.get('skipped',0)}")
    print(f"Distinct engine gaps: {len(gaps)}")


if __name__ == "__main__":
    main()
