"""
Fetch Yu-Gi-Oh! card art from the YGOProDeck API.

For each card in our YGO sets, queries the API for the card ID,
then builds the cropped art URL. Outputs:
1. Patches image_url into card defs (printed to stdout for manual patching)
2. Generates frontend/src/data/ygoCardArt.ts fallback map
"""

import json
import sys
import time
import urllib.request
import urllib.parse
import urllib.error


def fetch_card_id(card_name: str) -> int | None:
    """Query YGOProDeck API for a card's ID."""
    encoded = urllib.parse.quote(card_name)
    url = f"https://db.ygoprodeck.com/api/v7/cardinfo.php?name={encoded}"
    try:
        req = urllib.request.Request(url, headers={'User-Agent': 'Hyperdraft/1.0'})
        with urllib.request.urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode())
            if 'data' in data and len(data['data']) > 0:
                return data['data'][0]['id']
    except (urllib.error.HTTPError, urllib.error.URLError, json.JSONDecodeError, KeyError) as e:
        print(f"  Warning: Could not fetch '{card_name}': {e}", file=sys.stderr)
    return None


def cropped_url(card_id: int) -> str:
    return f"https://images.ygoprodeck.com/images/cards_cropped/{card_id}.jpg"


# All unique card names from our two sets
CARD_NAMES = [
    # ygo_starter.py
    "Battle Ox",
    "Giant Soldier of Stone",
    "Mystical Elf",
    "Dark Blade",
    "Alexandrite Dragon",
    "Gene-Warped Warwolf",
    "Luster Dragon",
    "Vorse Raider",
    "Summoned Skull",
    "Cosmo Queen",
    "Man-Eater Bug",
    "Magician of Faith",
    "Spear Dragon",
    "Breaker the Magical Warrior",
    "Effect Veiler",
    "Witch of the Black Forest",
    "Marauding Captain",
    "Dark Hole",
    "Mystical Space Typhoon",
    "Swords of Revealing Light",
    "Sword of Dark Destruction",
    "Mountain",
    "Monster Reborn",
    "Black Illusion Ritual",
    "Mirror Force",
    "Sakuretsu Armor",
    "Call of the Haunted",
    "Solemn Judgment",
    "Flame Swordsman",
    "Relinquished",
    # ygo_classic.py
    "Dark Magician",
    "Dark Magician Girl",
    "Kuriboh",
    "Celtic Guardian",
    "Feral Imp",
    "Buster Blader",
    "Marshmallon",
    "Gamma The Magnet Warrior",
    "Beta The Magnet Warrior",
    "Blue-Eyes White Dragon",
    "Blue-Eyes Ultimate Dragon",
    "Lord of D.",
    "Saggi the Dark Clown",
    "La Jinn the Mystical Genie",
    "Judge Man",
    "Kaiser Sea Horse",
    "Blade Knight",
    "X-Head Cannon",
    "Y-Dragon Head",
    "Z-Metal Tank",
    "Book of Moon",
    "Polymerization",
    "Flute of Summoning Dragon",
    "Enemy Controller",
    "Cost Down",
    "Magic Cylinder",
    "Negate Attack",
    "Ring of Destruction",
    "Crush Card Virus",
    "Interdimensional Matter Transporter",
]

# Cards with names that differ from our code vs the real API
NAME_OVERRIDES = {
    "Kuriboh Token": None,  # Custom card, skip
    "Sangan Scout": None,   # Custom card, skip
    "Tune Warrior": "Tune Warrior",
    "Stardust Warrior": "Stardust Warrior",
    "Utopia Knight": None,  # Custom name
}


def main():
    art_map: dict[str, str] = {}

    print(f"Fetching art for {len(CARD_NAMES)} cards...", file=sys.stderr)

    for name in CARD_NAMES:
        if name in NAME_OVERRIDES and NAME_OVERRIDES[name] is None:
            print(f"  Skipping custom card: {name}", file=sys.stderr)
            continue

        lookup_name = NAME_OVERRIDES.get(name, name)
        card_id = fetch_card_id(lookup_name)

        if card_id:
            url = cropped_url(card_id)
            art_map[name] = url
            print(f"  OK: {name} -> {card_id}", file=sys.stderr)
        else:
            print(f"  MISS: {name}", file=sys.stderr)

        time.sleep(0.15)  # Rate limit

    # Write frontend map
    ts_path = "frontend/src/data/ygoCardArt.ts"
    with open(ts_path, 'w') as f:
        f.write("/**\n * YGO Card Art URLs — auto-generated by scripts/fetch_ygo_art.py\n *\n")
        f.write(" * Cropped art from YGOProDeck API.\n */\n\n")
        f.write("export const YGO_CARD_ART: Record<string, string> = {\n")
        for name, url in sorted(art_map.items()):
            escaped_name = name.replace("'", "\\'")
            f.write(f"  '{escaped_name}': '{url}',\n")
        f.write("};\n")

    print(f"\nWrote {len(art_map)} entries to {ts_path}", file=sys.stderr)

    # Print image_url additions for card defs
    print("\n# Python image_url additions:", file=sys.stderr)
    for name, url in sorted(art_map.items()):
        print(f'    image_url="{url}",')


if __name__ == '__main__':
    main()
